let currentDay=0;
function showDay(i){currentDay=i;document.querySelectorAll('.day-chip').forEach((x,n)=>x.classList.toggle('active',n===i));document.querySelectorAll('.day').forEach((x,n)=>x.classList.toggle('active',n===i));const c=document.querySelectorAll('.day-chip')[i];if(c)c.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'});window.scrollTo(0,0)}
function switchView(btn,mode){const d=btn.closest('.day');if(!d)return;d.querySelectorAll('.view-tabs button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const l=d.querySelector('.list-view'),m=d.querySelector('.map-view');if(l)l.classList.toggle('hidden',mode==='map');if(m)m.classList.toggle('active',mode==='map')}
function openMenu(){document.getElementById('menu')?.classList.add('open');document.getElementById('overlay')?.classList.add('open')}
function closeMenu(){document.getElementById('menu')?.classList.remove('open');document.getElementById('overlay')?.classList.remove('open')}
function openPage(id){closeMenu();closePage();document.getElementById(id)?.classList.add('open')}
function closePage(){document.querySelectorAll('.sheet-page').forEach(x=>x.classList.remove('open'))}
function goTrip(){closePage();window.scrollTo(0,0)}
function showCurrentMap(){const d=document.querySelector('.day.active');const b=d?.querySelectorAll('.view-tabs button')[1];if(b)switchView(b,'map')}
let pf={cat:'הכול',city:'הכול'};
function setPF(k,v,b){pf[k]=v;b?.parentElement?.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b?.classList.add('active');applyPF()}
function applyPF(){const q=(document.getElementById('places-search')?.value||'').toLowerCase();document.querySelectorAll('#placesGrid .place-card').forEach(c=>{const ok=(pf.cat==='הכול'||(pf.cat==='במסלול'?c.dataset.scheduled==='1':c.dataset.cat===pf.cat))&&(pf.city==='הכול'||(c.dataset.city||'').includes(pf.city))&&(!q||c.innerText.toLowerCase().includes(q));c.style.display=ok?'':'none'})}
function setPlaceView(mode,btn){const g=document.getElementById('placesGrid');if(!g)return;g.classList.toggle('detail-view',mode==='detail');document.querySelectorAll('#placeViewToggle button').forEach(x=>x.classList.remove('active'));btn?.classList.add('active')}
const TK='japanTrip_take_v2';let items=[];
function loadTake(){try{items=JSON.parse(localStorage.getItem(TK)||'null')||['דרכונים','כרטיסי אשראי','רישיון נהיגה','טלפונים ומטענים','Power Bank','מתאם חשמל ליפן','תרופות קבועות','משקפיים / עדשות','בגדים','נעלי הליכה','מעיל / שכבה חמה','מטרייה קטנה'].map(text=>({text,done:false}))}catch(e){items=[]}renderTake()}
function saveTake(){localStorage.setItem(TK,JSON.stringify(items))}
function renderTake(){const b=document.getElementById('takeList');if(!b)return;b.innerHTML='';items.forEach((x,i)=>{const r=document.createElement('div');r.className='take-item'+(x.done?' done':'');const safe=String(x.text).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');r.innerHTML=`<input type="checkbox" ${x.done?'checked':''} onchange="toggleTake(${i})"><input type="text" value="${safe}" onchange="editTake(${i},this.value)"><div><button onclick="moveTake(${i},-1)">↑</button><button onclick="moveTake(${i},1)">↓</button><button onclick="deleteTake(${i})">🗑</button></div>`;b.appendChild(r)})}
function addTake(){const x=document.getElementById('newTakeItem');if(x?.value.trim()){items.push({text:x.value.trim(),done:false});x.value='';saveTake();renderTake()}}
function toggleTake(i){items[i].done=!items[i].done;saveTake();renderTake()}function editTake(i,v){items[i].text=v;saveTake()}function deleteTake(i){items.splice(i,1);saveTake();renderTake()}function moveTake(i,d){const j=i+d;if(j<0||j>=items.length)return;[items[i],items[j]]=[items[j],items[i]];saveTake();renderTake()}
function exportData(){const b=new Blob([JSON.stringify({take:items},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='JapanTrip_backup.json';a.click()}
function importData(f){if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(Array.isArray(d.take)){items=d.take;saveTake();renderTake()}}catch(e){alert('קובץ לא תקין')}};r.readAsText(f)}
function convertMoney(from){const rate=parseFloat(document.getElementById('yenRate')?.value)||45,ils=document.getElementById('ilsAmount'),jpy=document.getElementById('jpyAmount');if(!ils||!jpy)return;if(from==='ils'&&ils.value)jpy.value=(parseFloat(ils.value)*rate).toFixed(0);if(from==='jpy'&&jpy.value)ils.value=(parseFloat(jpy.value)/rate).toFixed(2)}
function saveYenRate(){try{localStorage.setItem('japanTrip_yen_rate',document.getElementById('yenRate')?.value||'45')}catch(e){}}
function setTranslate(t){const x=document.getElementById('translateText');if(x)x.value=t}function clearTranslate(){setTranslate('')}
function openGoogleTranslate(){const t=document.getElementById('translateText')?.value||'';if(t)window.open('https://translate.google.com/?sl=auto&tl=ja&text='+encodeURIComponent(t),'_blank')}
function speakJapanese(){const t=document.getElementById('jpSpeakText')?.value||'';if(!t||!('speechSynthesis'in window))return;const u=new SpeechSynthesisUtterance(t);u.lang='ja-JP';speechSynthesis.cancel();speechSynthesis.speak(u)}
function openPlaceModal(name){const modal=document.getElementById('placeModal');if(!modal)return;const title=modal.querySelector('h2,h3,.modal-title,[data-modal-title]');if(title)title.textContent=name;const body=modal.querySelector('.place-modal-body,.modal-body,[data-modal-body]');if(body){const card=[...document.querySelectorAll('.place-card,.stop-card')].find(c=>c.querySelector('h3')?.textContent.trim()===name);const p=card?.querySelector('p')?.textContent||'מידע נוסף על המקום יתווסף כאן.';body.innerHTML='<p>'+p+'</p>'}modal.classList.add('open');modal.style.display='flex'}
function closePlaceModal(){const m=document.getElementById('placeModal');if(m){m.classList.remove('open');m.style.display='none'}}
document.addEventListener('click',e=>{const b=e.target.closest('.guide-tips-btn');if(b){e.preventDefault();openPlaceModal(b.dataset.place||b.closest('.stop-card,.place-card')?.querySelector('h3')?.textContent||'מדריך וטיפים')}});
document.addEventListener('DOMContentLoaded',()=>{loadTake();applyPF();try{const r=localStorage.getItem('japanTrip_yen_rate');if(r&&document.getElementById('yenRate'))document.getElementById('yenRate').value=r}catch(e){};const today=new Date();if(today.getFullYear()===2026&&today.getMonth()===10&&today.getDate()>=3&&today.getDate()<=17)showDay(today.getDate()-3)});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));