// Japan Trip v9.12n - state/functionality rescue + final consistency fixes
(function(){'use strict';
const VERSION='v9.12n';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const TAKE_KEY='japanTrip_take_v2', SHOP_KEY='japanTrip_shop_v2';
const TAKE_DEFAULT=['דרכונים','ארנק + כרטיסי אשראי','ביטוח נסיעות','תרופות קבועות','מטענים לטלפונים','Power Bank','מתאם חשמל ליפן','eSIM / פרטי חיבור','משקפי שמש','נעלי הליכה נוחות','מעיל קל / שכבות','מטרייה מתקפלת','תיק יום קטן','צילום/עותק של מסמכי הנסיעה'];
const SHOP_DEFAULT=[
 {name:'משקפיים · JINS',done:false,note:'להזמין בתחילת הטיול כדי להשאיר זמן לאיסוף',maps:'https://www.google.com/maps/search/?api=1&query=JINS+Shinjuku+Tokyo'},
 {name:'נעלי ריצה',done:false,note:'Onitsuka Tiger / חנויות ספורט לפי התאמה',maps:'https://www.google.com/maps/search/?api=1&query=Onitsuka+Tiger+Omotesando+Tokyo'},
 {name:'מכונת גילוח',done:false,note:'Bic Camera / Yodobashi Camera',maps:'https://www.google.com/maps/search/?api=1&query=Bic+Camera+Shinjuku+Tokyo'},
 {name:'מכנסי ספורט',done:false,note:'Uniqlo / חנויות ספורט',maps:'https://www.google.com/maps/search/?api=1&query=Uniqlo+Tokyo'}
];
function load(keys,defaults){for(const k of keys){try{const a=JSON.parse(localStorage.getItem(k));if(Array.isArray(a)&&a.length)return a.map((x,i)=>typeof x==='string'?{id:Date.now()+i,name:x,done:false}:x)}catch(e){}}return defaults.map((x,i)=>typeof x==='string'?{id:Date.now()+i,name:x,done:false}:{id:Date.now()+i,...x})}
function save(k,a){try{localStorage.setItem(k,JSON.stringify(a))}catch(e){}}
let take=load([TAKE_KEY,'japanTrip_take_v1','takeList'],TAKE_DEFAULT);
let shop=load([SHOP_KEY,'japanTrip_shop_v1','shoppingList','shopList'],SHOP_DEFAULT);
function move(a,i,dir){const j=i+dir;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]]}
function renderTake(){const root=$('#takeList');if(!root)return;root.innerHTML='';take.forEach((x,i)=>{const r=document.createElement('div');r.className='take-item';r.style.cssText='display:flex;align-items:center;gap:8px;padding:10px 3px;border-bottom:1px solid #eee';r.innerHTML='<input type="checkbox" style="width:20px;height:20px"><span style="flex:1"></span><button type="button" title="למעלה">↑</button><button type="button" title="למטה">↓</button><button type="button" title="מחק">×</button>';const [cb]=r.querySelectorAll('input');const sp=r.querySelector('span'),bs=r.querySelectorAll('button');cb.checked=!!x.done;sp.textContent=x.name||x.text||'';if(x.done)sp.style.cssText='flex:1;text-decoration:line-through;opacity:.55';cb.onchange=()=>{x.done=cb.checked;save(TAKE_KEY,take);renderTake()};bs[0].onclick=()=>{move(take,i,-1);save(TAKE_KEY,take);renderTake()};bs[1].onclick=()=>{move(take,i,1);save(TAKE_KEY,take);renderTake()};bs[2].onclick=()=>{take.splice(i,1);save(TAKE_KEY,take);renderTake()};root.appendChild(r)});save(TAKE_KEY,take)}
window.addTake=window.addTakeItem=function(){const inp=$('#newTakeItem,#takeNew');if(!inp||!inp.value.trim())return;take.push({id:Date.now(),name:inp.value.trim(),done:false});inp.value='';save(TAKE_KEY,take);renderTake()};
function renderShop(){const root=$('#shoppingList');if(!root)return;root.innerHTML='';shop.forEach((x,i)=>{const r=document.createElement('div');r.className='shopping-item';r.style.cssText='background:#fff;border:1px solid #e5e7eb;border-radius:14px;padding:11px;margin:8px 0';r.innerHTML='<div style="display:flex;gap:8px;align-items:flex-start"><input type="checkbox" style="width:20px;height:20px"><div style="flex:1"><b></b><div class="shop-note" style="font-size:11px;color:#666;margin-top:4px"></div></div><button type="button" title="למעלה">↑</button><button type="button" title="למטה">↓</button><button type="button" title="מחק">×</button></div><div class="shop-map" style="margin-top:8px"></div>';const cb=r.querySelector('input'),b=r.querySelector('b'),note=r.querySelector('.shop-note'),bs=r.querySelectorAll('button'),map=r.querySelector('.shop-map');cb.checked=!!x.done;b.textContent=x.name||x.text||'';note.textContent=x.note||'';if(x.done)b.style.cssText='text-decoration:line-through;opacity:.55';if(x.maps){const a=document.createElement('a');a.className='map-btn';a.href=x.maps;a.target='_blank';a.rel='noopener';a.textContent='📍 חנויות / מפה ↗';map.appendChild(a)}cb.onchange=()=>{x.done=cb.checked;save(SHOP_KEY,shop);renderShop()};bs[0].onclick=()=>{move(shop,i,-1);save(SHOP_KEY,shop);renderShop()};bs[1].onclick=()=>{move(shop,i,1);save(SHOP_KEY,shop);renderShop()};bs[2].onclick=()=>{shop.splice(i,1);save(SHOP_KEY,shop);renderShop()};root.appendChild(r)});save(SHOP_KEY,shop)}
window.addShopItem=function(){const inp=$('#newShopItem');if(!inp||!inp.value.trim())return;shop.push({id:Date.now(),name:inp.value.trim(),done:false,note:'',maps:''});inp.value='';save(SHOP_KEY,shop);renderShop()};
function fixAliasesAndCats(){const aliases=[[/^Meiji Jingu$/i,'Meiji Shrine'],[/^Tokyo Station & Marunouchi$/i,'Tokyo Station / Marunouchi'],[/^(Fuji \/ Kawaguchiko|Kawaguchiko \/ Fuji)$/i,'Kawaguchiko'],[/^Fushimi Inari Taisha$/i,'Fushimi Inari'],[/^Sanjūsangen-dō$/i,'Sanjusangen-do'],[/^Kinkaku-ji · מקדש הזהב$/i,'Kinkaku-ji']];$$('.place-card,.stop-card').forEach(c=>{const h=c.querySelector('h3');if(!h)return;const hit=aliases.find(([re])=>re.test(h.textContent.trim()));if(hit)c.querySelectorAll('.guide-tips-btn,.info-modal-btn,.place-info-btn').forEach(b=>b.dataset.place=hit[1])});$$('#placesGrid .place-card').forEach(c=>{const h=c.querySelector('h3')?.textContent||'';if(/Gyukatsu Motomura|Uobei|AFURI|Afuri|Katsukura|Musashi Sushi|Mizuno|551 Horai|Namba Ramen Ichiza/i.test(h)){c.dataset.cat='🍽️ מסעדות';c.dataset.city=/Katsukura|Musashi/i.test(h)?'Kyoto':/Mizuno|551|Ramen Ichiza/i.test(h)?'Osaka':'Tokyo'}})}
function fixDay2Order(){const d=$('#day-2');if(!d)return;const s=$$('.stop',d).find(x=>/^Nakamise$/i.test(x.querySelector('h3')?.textContent||''));if(s){const t=s.querySelector('.time');if(t&&t.textContent.trim()==='08:45')t.textContent='09:15'}}
function fixOsakaArrival(){const d=$('#day-11');if(!d)return;const note=d.querySelector('.transit-day-note');if(note)note.innerHTML='<b>🧳 תוכנית מזוודות:</b> בבוקר נבדוק עם Richmond Hotel Premier Kyoto Shijo אפשרות לשליחת המזוודות ל-<b>Hotel Royal Classic Osaka</b>. רק לאחר אישור השירות בפועל נמסור אותן; אחרת ניקח אותן איתנו/נשתמש בפתרון חלופי. ב-Nara נשתמש בלוקר רק לציוד שאיתנו.';$$('.stop-card',d).forEach(c=>{const h=c.querySelector('h3')?.textContent||'';if(/Hotel Royal Classic Osaka|Check-in Osaka · Namba/i.test(h)){const p=c.querySelector('p');if(p)p.innerHTML='<b>Hotel Royal Classic Osaka</b> · המלון הסופי שלנו באוסקה, 14–16/11. מחובר ישירות ל-Osaka Metro Namba Exit 12. אחרי הצ׳ק-אין נצא ברגל ל-Hozenji ו-Dotonbori.';c.querySelectorAll('a[href*="Cross+Hotel"],a[href*="Cross%20Hotel"],a[href*="cross"]')?.forEach(a=>a.remove())}})}
function fixAoniyoshi(){const d=$('#day-11');if(!d)return;$$('.stop-card',d).forEach(c=>{if(!/AONIYOSHI · Kyoto → Kintetsu-Nara/i.test(c.querySelector('h3')?.textContent||''))return;const p=c.querySelector('p');if(p)p.textContent='רכבת התיירות המיוחדת AONIYOSHI. לפי לוח Kintetsu המעודכן למרץ 2026: בשבת Kyoto 10:55 → Kintetsu-Nara 11:31. נוודא שוב את יום ההפעלה והזמינות סמוך לפתיחת המכירה.'})}
function setVersion(){const v=$('header .logo .app-version')||$('header .logo small');if(v)v.textContent='2026 · '+VERSION;document.title='Japan Trip 2026 · '+VERSION;document.documentElement.dataset.appReady=VERSION}
function run(){renderTake();renderShop();fixAliasesAndCats();fixDay2Order();fixOsakaArrival();fixAoniyoshi();setVersion()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,350),{once:true});else setTimeout(run,350);setTimeout(run,1100);setTimeout(setVersion,2000);
})();