// Japan Trip v9.15.4 — stable hotels, single schedule badge, compact document controls
(()=>{'use strict';
const RATE=0.0196773;
const HOTELS=[
 {key:'hotel-jr-kyushu-shinjuku',name:'JR Kyushu Hotel Blossom Shinjuku',dates:'4–8 Nov 2026',address:'2-6-2 Yoyogi, Shibuya-ku, Tokyo',arrival:'JR Shinjuku · South Exit · כ־3 דקות',provider:'Agoda',booking:'696266027',ref:'6870831053',room:'Standard Double Room with Queen Bed · Non-Smoking',size:'19 m²',bed:'Queen · 160×200 cm',meal:'כולל ארוחת בוקר',jpy:311616,ils:Math.round(311616*RATE),payment:'תשלום מאוחר',cancel:'לפני 1 Nov 2026',map:'https://www.google.com/maps/search/?api=1&query=JR+Kyushu+Hotel+Blossom+Shinjuku'},
 {key:'hotel-daiwa-kyoto-shijo',name:'Daiwa Roynet Hotel Kyoto Shijo Karasuma',dates:'10–14 Nov 2026',address:'678 Omandokorocho, Karasumadori, Shimogyo-ku, Kyoto 600-8413',arrival:'Kyoto Subway Shijo · Exit 5 · כ־1 דקה מהיציאה',provider:'Agoda',booking:'2048972834',ref:'',room:'Moderate Double Room · Newly Renovated · Non-Smoking',size:'21.1 m²',bed:'Double רחבה · 168×203 cm',meal:'ללא ארוחת בוקר',jpy:116856,ils:Math.round(116856*RATE),payment:'תשלום מאוחר',cancel:'לפני 9 Nov 2026',map:'https://www.google.com/maps/search/?api=1&query=Daiwa+Roynet+Hotel+Kyoto+Shijo+Karasuma'},
 {key:'hotel-royal-classic-osaka',name:'Hotel Royal Classic Osaka',dates:'14–16 Nov 2026',address:'4-3-3 Namba, Chuo-ku, Osaka',arrival:'Osaka Metro Namba · Exit 12 · מחובר ישירות למלון',provider:'Agoda',booking:'693085383',ref:'GHT261114349164',room:'Standard Queen Room · Non-Smoking',size:'25.6–31 m²',bed:'מיטה זוגית אחת',meal:'כולל ארוחת בוקר',jpy:109398,ils:Math.round(109398*RATE),payment:'תשלום מאוחר',cancel:'לפני 12 Nov 2026',map:'https://www.google.com/maps/search/?api=1&query=Hotel+Royal+Classic+Osaka'},
 {key:'hotel-metropolitan-marunouchi',name:'Hotel Metropolitan Tokyo Marunouchi',dates:'16–17 Nov 2026',address:'Sapia Tower · 1-7-12 Marunouchi, Chiyoda-ku, Tokyo',arrival:'Tokyo Station · Nihombashi Exit · כ־1 דקה',provider:'Klook',booking:'QXU287073',ref:'',room:'UTSUROI (Renovated) · Queen · Non-Smoking',size:'18 m²',bed:'Queen',meal:'ללא ארוחת בוקר',jpy:Math.round(676.61/RATE),ils:676.61,payment:'שולם',cancel:'עד 15 Nov 2026 · 21:59 (שעון יפן)',map:'https://www.google.com/maps/search/?api=1&query=Hotel+Metropolitan+Tokyo+Marunouchi'}
];
const money=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(n);
const row=(l,v,c='')=>`<div class="hotel-detail-row ${c}"><span>${l}</span><strong>${v}</strong></div>`;
function card(h){return `<div class="hotel-card booked" data-hotel-key="${h.key}"><div class="hotel-title"><b>${h.name}</b><span>הוזמן ✅</span></div><div class="hotel-booking-details">${row('📅 תאריכים',h.dates)}${row('🏷️ הוזמן דרך',h.provider)}${row('🔢 מספר הזמנה',h.booking)}${h.ref?row('🧾 Reference',h.ref):''}${row('🛏️ סוג חדר',h.room)}${row('📐 גודל חדר',h.size)}${row('🛌 מיטה',h.bed)}${row('🍳 ארוחה',h.meal)}${row('💴 מחיר ביין',`¥${money(h.jpy)}`,'hotel-price')}${row('₪ מחיר בשקלים',`${h.payment==='שולם'?'':'≈ '}₪${money(h.ils)}`,'hotel-price')}${row('💳 מצב תשלום',h.payment)}${row('🟢 ביטול חינם',h.cancel)}${row('📍 כתובת',h.address)}${row('🚉 הגעה',h.arrival)}</div><div class="hotel-doc-heading">📎 אסמכתה</div><div class="hotel-map-actions"><a class="map-btn" href="${h.map}" target="_blank" rel="noopener">📍 פתח מפה ↗</a></div></div>`}
function rebuildHotels(){const p=document.getElementById('page-hotels');if(!p)return;p.innerHTML=`<div class="page-head"><button onclick="closePage()">←</button><h2>🏨 מלונות</h2></div><div class="hotel-city"><h3>🗼 Tokyo · 4–8 Nov</h3>${card(HOTELS[0])}</div><div class="hotel-city"><h3>♨️ Hakone / Fuji · 8–10 Nov</h3><div class="hotel-note">⏳ <b>המלון עדיין לא נסגר</b></div></div><div class="hotel-city"><h3>⛩️ Kyoto · 10–14 Nov</h3>${card(HOTELS[1])}</div><div class="hotel-city"><h3>🏯 Osaka · 14–16 Nov</h3>${card(HOTELS[2])}</div><div class="hotel-city"><h3>🗼 Tokyo · 16–17 Nov</h3>${card(HOTELS[3])}</div>`;window.JapanTripHotels=HOTELS;window.dispatchEvent(new CustomEvent('japanTripDriveSynced'))}
function compactDocs(){document.querySelectorAll('#page-hotels .reservation-doc-actions').forEach(a=>{const open=a.querySelector('.reservation-doc-open'),replace=a.querySelector('.reservation-doc-replace'),del=a.querySelector('.reservation-doc-unlink'),add=a.querySelector('.reservation-doc-link');if(open){open.textContent='👁️ צפייה באסמכתה';open.title='צפייה באסמכתה'}if(replace){replace.textContent='🔄';replace.title='החלפת אסמכתה';replace.setAttribute('aria-label','החלפת אסמכתה')}if(del){del.textContent='🗑️';del.title='מחיקת אסמכתה';del.setAttribute('aria-label','מחיקת אסמכתה')}if(add)add.textContent='➕ הוסף אסמכתה'});document.querySelectorAll('.day .reservation-doc-actions').forEach(x=>x.remove())}
function dedupeSchedules(){document.querySelectorAll('#placesGrid .place-card').forEach(c=>{const badges=[...c.querySelectorAll('.place-card-meta,.scheduled-badge')].filter(x=>/במסלול/.test(x.textContent||''));if(!badges.length)return;const parse=x=>{const t=x.textContent||'',m=t.match(/(\d{1,2}[\/.]\d{1,2}).*?(\d{1,2}:\d{2})/);return m?`${m[1]} · ${m[2]}`:''};const preferred=badges.find(x=>/אחרים|מקדשים|מסעדות|שווקים|קניות|טבע|תרבות|אטרקציות/.test(x.textContent||''))||badges[0];const dt=parse(preferred)||parse(badges[0]);preferred.textContent=`🟢 במסלול${dt?' · '+dt:''}`;preferred.classList.add('scheduled-badge','place-schedule-normalized');badges.forEach(x=>{if(x!==preferred)x.remove()})})}
function style(){if(document.getElementById('v9154UiStyle'))return;const s=document.createElement('style');s.id='v9154UiStyle';s.textContent=`#page-hotels .hotel-card{padding:14px;border:1px solid #e5e7eb;border-radius:16px;background:#fff;margin:8px 0 16px}#page-hotels .hotel-title{display:flex;gap:8px;justify-content:space-between}#page-hotels .hotel-title span{font-size:11px;background:#ecfdf3;color:#176b3a;padding:4px 7px;border-radius:99px}#page-hotels .hotel-booking-details{margin-top:10px;border-top:1px solid #e5e7eb}#page-hotels .hotel-detail-row{display:grid;grid-template-columns:118px 1fr;gap:9px;padding:7px 0;border-bottom:1px solid #f0f1f3;font-size:13px}#page-hotels .hotel-detail-row span{color:#667085}#page-hotels .hotel-doc-heading{font-weight:800;font-size:13px;margin-top:12px;padding-top:10px;border-top:1px solid #e5e7eb}#page-hotels .reservation-doc-actions{display:flex!important;align-items:center;gap:5px!important;flex-wrap:nowrap!important;margin-top:7px!important}#page-hotels .reservation-doc-actions button{border:0;border-radius:9px;padding:7px 9px!important;font-weight:700;white-space:nowrap}#page-hotels .reservation-doc-open{flex:0 1 auto}#page-hotels .reservation-doc-replace,#page-hotels .reservation-doc-unlink{width:34px;height:34px;padding:0!important;font-size:16px;display:inline-grid;place-items:center}#page-hotels .reservation-doc-actions span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}#placesGrid .scheduled-badge.place-schedule-normalized{display:inline-block!important;background:#eaf7ed!important;color:#26733b!important;border-radius:999px!important;padding:5px 8px!important;font-size:10px!important;font-weight:900!important;margin:3px 0 7px!important}@media(max-width:390px){#page-hotels .hotel-detail-row{grid-template-columns:102px 1fr;font-size:12px}}`;document.head.appendChild(s)}
function refresh(){style();rebuildHotels();setTimeout(()=>{compactDocs();dedupeSchedules()},100)}
function run(){refresh();setTimeout(()=>{compactDocs();dedupeSchedules()},600);setTimeout(()=>{compactDocs();dedupeSchedules()},1600)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();window.addEventListener('japanTripDriveSynced',()=>setTimeout(compactDocs,80));
})();