// Japan Trip v9.15.3 — canonical hotel source, stable hotel page, unified place schedule badges
(()=>{'use strict';
const RATE=0.0196773;
const HOTELS=[
 {key:'hotel-jr-kyushu-shinjuku',name:'JR Kyushu Hotel Blossom Shinjuku',city:'Tokyo',dates:'4–8 Nov 2026',address:'2-6-2 Yoyogi, Shibuya-ku, Tokyo',arrival:'JR Shinjuku · South Exit · כ־3 דקות',provider:'Agoda',booking:'696266027',ref:'6870831053',room:'Standard Double Room with Queen Bed · Non-Smoking',size:'19 m²',bed:'Queen · 160×200 cm',meal:'כולל ארוחת בוקר',jpy:311616,ils:Math.round(311616*RATE),payment:'תשלום מאוחר',cancel:'לפני 1 Nov 2026',map:'https://www.google.com/maps/search/?api=1&query=JR+Kyushu+Hotel+Blossom+Shinjuku'},
 {key:'hotel-daiwa-kyoto-shijo',name:'Daiwa Roynet Hotel Kyoto Shijo Karasuma',city:'Kyoto',dates:'10–14 Nov 2026',address:'678 Omandokorocho, Karasumadori, Shimogyo-ku, Kyoto 600-8413',arrival:'Kyoto Subway Shijo · Exit 5 · כ־1 דקה מהיציאה',provider:'Agoda',booking:'2048972834',ref:'',room:'Moderate Double Room · Newly Renovated · Non-Smoking',size:'21.1 m²',bed:'Double רחבה · 168×203 cm',meal:'ללא ארוחת בוקר',jpy:116856,ils:Math.round(116856*RATE),payment:'תשלום מאוחר',cancel:'לפני 9 Nov 2026',map:'https://www.google.com/maps/search/?api=1&query=Daiwa+Roynet+Hotel+Kyoto+Shijo+Karasuma'},
 {key:'hotel-royal-classic-osaka',name:'Hotel Royal Classic Osaka',city:'Osaka',dates:'14–16 Nov 2026',address:'4-3-3 Namba, Chuo-ku, Osaka',arrival:'Osaka Metro Namba · Exit 12 · מחובר ישירות למלון',provider:'Agoda',booking:'693085383',ref:'GHT261114349164',room:'Standard Queen Room · Non-Smoking',size:'25.6–31 m²',bed:'מיטה זוגית אחת',meal:'כולל ארוחת בוקר',jpy:109398,ils:Math.round(109398*RATE),payment:'תשלום מאוחר',cancel:'לפני 12 Nov 2026',map:'https://www.google.com/maps/search/?api=1&query=Hotel+Royal+Classic+Osaka'},
 {key:'hotel-metropolitan-marunouchi',name:'Hotel Metropolitan Tokyo Marunouchi',city:'Tokyo',dates:'16–17 Nov 2026',address:'Sapia Tower · 1-7-12 Marunouchi, Chiyoda-ku, Tokyo',arrival:'Tokyo Station · Nihombashi Exit · כ־1 דקה',provider:'Klook',booking:'QXU287073',ref:'',room:'UTSUROI (Renovated) · Queen · Non-Smoking',size:'18 m²',bed:'Queen',meal:'ללא ארוחת בוקר',jpy:Math.round(676.61/RATE),ils:676.61,payment:'שולם',cancel:'עד 15 Nov 2026 · 21:59 (שעון יפן)',map:'https://www.google.com/maps/search/?api=1&query=Hotel+Metropolitan+Tokyo+Marunouchi'}
];
const money=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(n);
function row(label,value,cls=''){return `<div class="hotel-detail-row ${cls}"><span>${label}</span><strong>${value}</strong></div>`}
function card(h){return `<div class="hotel-card booked" data-hotel-key="${h.key}"><div class="hotel-title"><b>${h.name}</b><span>הוזמן ✅</span></div><div class="hotel-booking-details">${row('📅 תאריכים',h.dates)}${row('🏷️ הוזמן דרך',h.provider)}${row('🔢 מספר הזמנה',h.booking)}${h.ref?row('🧾 Reference',h.ref):''}${row('🛏️ סוג חדר',h.room)}${row('📐 גודל חדר',h.size)}${row('🛌 מיטה',h.bed)}${row('🍳 ארוחה',h.meal)}${row('💴 מחיר ביין',`¥${money(h.jpy)}`,'hotel-price')}${row('₪ מחיר בשקלים',`${h.payment==='שולם'?'':'≈ '}₪${money(h.ils)}`,'hotel-price')}${row('💳 מצב תשלום',h.payment)}${row('🟢 ביטול חינם',h.cancel)}${row('📍 כתובת',h.address)}${row('🚉 הגעה',h.arrival)}</div><div class="hotel-doc-heading">📎 אסמכתה</div><div class="hotel-map-actions"><a class="map-btn" href="${h.map}" target="_blank" rel="noopener">📍 פתח מפה ↗</a></div></div>`}
function rebuildHotels(){const p=document.getElementById('page-hotels');if(!p)return;p.dataset.canonicalHotels='v9153';p.innerHTML=`<div class="page-head"><button onclick="closePage()">←</button><h2>🏨 מלונות</h2></div><div class="hotel-city"><h3>🗼 Tokyo · 4–8 Nov</h3>${card(HOTELS[0])}</div><div class="hotel-city"><h3>♨️ Hakone / Fuji · 8–10 Nov</h3><div class="hotel-note">⏳ <b>המלון עדיין לא נסגר</b></div></div><div class="hotel-city"><h3>⛩️ Kyoto · 10–14 Nov</h3>${card(HOTELS[1])}</div><div class="hotel-city"><h3>🏯 Osaka · 14–16 Nov</h3>${card(HOTELS[2])}</div><div class="hotel-city"><h3>🗼 Tokyo · 16–17 Nov</h3>${card(HOTELS[3])}</div>`;window.JapanTripHotels=HOTELS;window.dispatchEvent(new CustomEvent('japanTripDriveSynced',{detail:{reason:'hotel-page-rebuilt'}}));}
function decorateDocs(){document.querySelectorAll('#page-hotels .hotel-card').forEach(card=>{const a=card.querySelector('.reservation-doc-actions');if(!a)return;const heading=card.querySelector('.hotel-doc-heading');if(heading&&heading.nextElementSibling!==a)heading.after(a);const add=a.querySelector('.reservation-doc-link');if(add)add.textContent='➕ הוסף אסמכתה';const open=a.querySelector('.reservation-doc-open');if(open)open.textContent='👁️ צפייה באסמכתה';const replace=a.querySelector('.reservation-doc-replace');if(replace)replace.textContent='🔄 החלף אסמכתה';const del=a.querySelector('.reservation-doc-unlink');if(del)del.textContent='🗑️ מחק אסמכתה'});document.querySelectorAll('.day .reservation-doc-actions').forEach(x=>x.remove())}
function normalizePlaceScheduleBadges(){document.querySelectorAll('#placesGrid .place-card-meta').forEach(el=>{if(/במסלול|\d{1,2}[\/.]\d{1,2}|\d{1,2}:\d{2}/.test(el.textContent||''))el.classList.add('scheduled-badge','place-schedule-normalized')});}
function style(){if(document.getElementById('v9153UiStyle'))return;const s=document.createElement('style');s.id='v9153UiStyle';s.textContent=`#page-hotels .hotel-card{padding:14px;border:1px solid #e5e7eb;border-radius:16px;background:#fff;margin:8px 0 16px;box-shadow:0 2px 8px rgba(0,0,0,.03)}#page-hotels .hotel-title{display:flex;gap:8px;align-items:flex-start;justify-content:space-between}#page-hotels .hotel-title b{font-size:15px;line-height:1.35}#page-hotels .hotel-title span{font-size:11px;white-space:nowrap;background:#ecfdf3;color:#176b3a;padding:4px 7px;border-radius:99px}#page-hotels .hotel-booking-details{margin-top:10px;border-top:1px solid #e5e7eb}#page-hotels .hotel-detail-row{display:grid;grid-template-columns:118px 1fr;gap:9px;padding:7px 0;border-bottom:1px solid #f0f1f3;font-size:13px;align-items:start}#page-hotels .hotel-detail-row span{color:#667085}#page-hotels .hotel-detail-row strong{font-weight:600;color:#1f2937}#page-hotels .hotel-price strong{font-size:15px;color:#111827}#page-hotels .hotel-doc-heading{font-weight:800;font-size:13px;margin-top:12px;padding-top:10px;border-top:1px solid #e5e7eb}#page-hotels .reservation-doc-actions{display:flex!important;gap:7px;flex-wrap:wrap;margin-top:8px!important;padding-top:0!important;border-top:0!important}#page-hotels .reservation-doc-actions button{border:0;border-radius:10px;padding:9px 11px;font-weight:700}#page-hotels .hotel-map-actions{margin-top:10px}#placesGrid .scheduled-badge,#placesGrid .place-card-meta.place-schedule-normalized{display:inline-block!important;background:#eaf7ed!important;color:#26733b!important;border-radius:999px!important;padding:5px 8px!important;font-size:10px!important;font-weight:900!important;margin:3px 0 7px!important}@media(max-width:390px){#page-hotels .hotel-detail-row{grid-template-columns:102px 1fr;font-size:12px}}`;document.head.appendChild(s)}
function refresh(){style();rebuildHotels();normalizePlaceScheduleBadges();setTimeout(decorateDocs,180)}
function run(){refresh();setTimeout(refresh,450);setTimeout(refresh,1350);setTimeout(()=>{normalizePlaceScheduleBadges();decorateDocs()},2200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
window.addEventListener('japanTripDriveSynced',()=>setTimeout(decorateDocs,80));
})();