// Japan Trip v9.15.0 — canonical hotel source and hotel page
(()=>{'use strict';
const RATE=0.0196773;
const HOTELS=[
 {key:'hotel-jr-kyushu-shinjuku',name:'JR Kyushu Hotel Blossom Shinjuku',city:'Tokyo',dates:'4–8 Nov 2026',address:'2-6-2 Yoyogi, Shibuya-ku, Tokyo',arrival:'JR Shinjuku · South Exit · כ־3 דקות',provider:'Agoda',booking:'696266027',ref:'6870831053',room:'Standard Double Room with Queen Bed · Non-Smoking',size:'19 m²',bed:'Queen · 160×200 cm',meal:'כולל ארוחת בוקר',jpy:311616,ils:Math.round(311616*RATE),payment:'תשלום מאוחר',cancel:'לפני 1 Nov 2026',map:'https://www.google.com/maps/search/?api=1&query=JR+Kyushu+Hotel+Blossom+Shinjuku'},
 {key:'hotel-daiwa-kyoto-shijo',name:'Daiwa Roynet Hotel Kyoto Shijo Karasuma',city:'Kyoto',dates:'10–14 Nov 2026',address:'678 Omandokorocho, Karasumadori, Shimogyo-ku, Kyoto 600-8413',arrival:'Kyoto Subway Shijo · Exit 5 · כ־1 דקה מהיציאה',provider:'Agoda',booking:'2048972834',ref:'',room:'Moderate Double Room · Newly Renovated · Non-Smoking',size:'21.1 m²',bed:'Double רחבה · 168×203 cm',meal:'ללא ארוחת בוקר · Wi-Fi + קפה/תה',jpy:116856,ils:Math.round(116856*RATE),payment:'תשלום מאוחר',cancel:'לפני 9 Nov 2026',map:'https://www.google.com/maps/search/?api=1&query=Daiwa+Roynet+Hotel+Kyoto+Shijo+Karasuma'},
 {key:'hotel-royal-classic-osaka',name:'Hotel Royal Classic Osaka',city:'Osaka',dates:'14–16 Nov 2026',address:'4-3-3 Namba, Chuo-ku, Osaka',arrival:'Osaka Metro Namba · Exit 12 · מחובר ישירות למלון',provider:'Agoda',booking:'693085383',ref:'GHT261114349164',room:'Standard Queen Room · Non-Smoking',size:'25.6–31 m²',bed:'מיטה זוגית אחת',meal:'כולל ארוחת בוקר + Wi-Fi',jpy:109398,ils:Math.round(109398*RATE),payment:'תשלום מאוחר',cancel:'לפני 12 Nov 2026',map:'https://www.google.com/maps/search/?api=1&query=Hotel+Royal+Classic+Osaka'},
 {key:'hotel-metropolitan-marunouchi',name:'Hotel Metropolitan Tokyo Marunouchi',city:'Tokyo',dates:'16–17 Nov 2026',address:'Sapia Tower · 1-7-12 Marunouchi, Chiyoda-ku, Tokyo',arrival:'Tokyo Station · Nihombashi Exit · כ־1 דקה',provider:'Klook',booking:'QXU287073',ref:'',room:'UTSUROI (Renovated) · Queen · Non-Smoking',size:'18 m²',bed:'Queen',meal:'ללא ארוחת בוקר',jpy:Math.round(676.61/RATE),ils:677,payment:'שולם',cancel:'עד 15 Nov 2026 · 21:59 (שעון יפן)',map:'https://www.google.com/maps/search/?api=1&query=Hotel+Metropolitan+Tokyo+Marunouchi'}
];
const money=n=>new Intl.NumberFormat('en-US').format(n);
function card(h){return `<div class="hotel-card booked" data-hotel-key="${h.key}"><b>${h.name} — הוזמן ✅</b><div class="hotel-booking-details"><div class="hotel-detail-row"><span>📅 תאריכים</span><strong>${h.dates}</strong></div><div class="hotel-detail-row"><span>📍 כתובת</span><strong>${h.address}</strong></div><div class="hotel-detail-row"><span>🚉 הגעה</span><strong>${h.arrival}</strong></div><div class="hotel-detail-row"><span>🏷️ הוזמן דרך</span><strong>${h.provider}</strong></div><div class="hotel-detail-row"><span>🔢 מספר הזמנה</span><strong>${h.booking}</strong></div>${h.ref?`<div class="hotel-detail-row"><span>🧾 Reference</span><strong>${h.ref}</strong></div>`:''}<div class="hotel-detail-row"><span>🛏️ סוג חדר</span><strong>${h.room}</strong></div><div class="hotel-detail-row"><span>📐 גודל חדר</span><strong>${h.size}</strong></div><div class="hotel-detail-row"><span>🛌 מיטה</span><strong>${h.bed}</strong></div><div class="hotel-detail-row"><span>🍳 ארוחה</span><strong>${h.meal}</strong></div><div class="hotel-detail-row hotel-price"><span>💴 מחיר</span><strong>¥${money(h.jpy)} · ≈ ₪${money(h.ils)}</strong></div><div class="hotel-detail-row"><span>💳 תשלום</span><strong>${h.payment}</strong></div><div class="hotel-detail-row"><span>🟢 ביטול חינם</span><strong>${h.cancel}</strong></div></div><div class="hotel-map-actions"><a class="map-btn" href="${h.map}" target="_blank" rel="noopener">📍 פתח מפה ↗</a></div></div>`}
function rebuild(){const p=document.getElementById('page-hotels');if(!p)return;p.dataset.canonicalHotels='v915';p.innerHTML=`<div class="page-head"><button onclick="closePage()">←</button><h2>🏨 מלונות</h2></div><div class="hotel-city"><h3>🗼 Tokyo · 4–8 Nov</h3>${card(HOTELS[0])}</div><div class="hotel-city"><h3>♨️ Hakone / Fuji · 8–10 Nov</h3><div class="hotel-note">⏳ <b>המלון עדיין לא נסגר</b></div></div><div class="hotel-city"><h3>⛩️ Kyoto · 10–14 Nov</h3>${card(HOTELS[1])}</div><div class="hotel-city"><h3>🏯 Osaka · 14–16 Nov</h3>${card(HOTELS[2])}</div><div class="hotel-city"><h3>🗼 Tokyo · 16–17 Nov</h3>${card(HOTELS[3])}</div>`;}
function style(){if(document.getElementById('v915HotelStyle'))return;const s=document.createElement('style');s.id='v915HotelStyle';s.textContent=`#page-hotels .hotel-card{padding:14px;border:1px solid #e5e7eb;border-radius:16px;background:#fff;margin:8px 0 16px}#page-hotels .hotel-booking-details{margin-top:10px;border-top:1px solid #e5e7eb}#page-hotels .hotel-detail-row{display:grid;grid-template-columns:112px 1fr;gap:9px;padding:7px 0;border-bottom:1px solid #f0f1f3;font-size:13px;align-items:start}#page-hotels .hotel-detail-row span{color:#667085}#page-hotels .hotel-detail-row strong{font-weight:600;color:#1f2937}#page-hotels .hotel-price strong{font-size:15px;color:#111827}#page-hotels .reservation-doc-actions{padding-top:10px;margin-top:10px;border-top:1px solid #e5e7eb}#page-hotels .reservation-doc-actions button{border:0;border-radius:10px;padding:9px 11px;font-weight:700}#page-hotels .hotel-map-actions{margin-top:10px}@media(max-width:390px){#page-hotels .hotel-detail-row{grid-template-columns:96px 1fr;font-size:12px}}`;document.head.appendChild(s)}
function run(){style();rebuild();window.JapanTripHotels=HOTELS}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();