// Japan Trip v9.12l - canonical hotel state, one-time only
(function(){'use strict';
const VERSION='v9.12l';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const HOTELS={
 tokyo1:{name:'JR Kyushu Hotel Blossom Shinjuku',dates:'4–8 Nov 2026',city:'Tokyo',address:'2-6-2 Yoyogi, Shibuya-ku',room:'Standard Double Queen · Non-Smoking · 2 Adults · 4 nights',extra:'Breakfast + Wi-Fi',price:'¥311,616 · Pay later',transport:'JR Shinjuku South Exit · כ־3 דקות',map:'https://www.google.com/maps/search/?api=1&query=JR+Kyushu+Hotel+Blossom+Shinjuku'},
 kyoto:{name:'Richmond Hotel Premier Kyoto Shijo',dates:'10–14 Nov 2026',city:'Kyoto',address:'50 Kasaboko Town, Shimogyo Ward',room:'Moderate Double · Non-Smoking · 2 Adults · 4 nights',extra:'Breakfast + Wi-Fi',price:'¥159,420 · Pay later',transport:'Shijo / Karasuma · Exit 24 · כ־7 דקות',map:'https://www.google.com/maps/search/?api=1&query=Richmond+Hotel+Premier+Kyoto+Shijo'},
 osaka:{name:'Hotel Royal Classic Osaka',dates:'14–16 Nov 2026',city:'Osaka',address:'4-3-3 Namba, Chuo-ku, Osaka',room:'Standard Queen · Non-Smoking · 2 Adults · 2 nights',extra:'Breakfast + Wi-Fi included',price:'¥109,398 · Pay later',transport:'Osaka Metro Namba · Exit 12 · מחובר ישירות למלון',map:'https://www.google.com/maps/search/?api=1&query=Hotel+Royal+Classic+Osaka'},
 tokyo2:{name:'Hotel Metropolitan Tokyo Marunouchi',dates:'16–17 Nov 2026',city:'Tokyo',address:'Sapia Tower · 1-7-12 Marunouchi, Chiyoda-ku, Tokyo',room:'UTSUROI (Renovated) · Queen · 18 m² · Non-Smoking · 2 Adults · 1 night',extra:'Booking QXU287073',price:'שולם ₪676.61',transport:'Tokyo Station · Nihombashi Exit · כ־1 דקה מ-Shinkansen Nihombashi Gate',map:'https://www.google.com/maps/search/?api=1&query=Hotel+Metropolitan+Tokyo+Marunouchi'}
};
function card(h,status){return `<div class="hotel-note">✅ <b>${h.name} — ${status}</b></div><div class="hotel-card booked"><b>${h.name}</b><p>📍 ${h.address}</p><p>🛏️ ${h.room}</p><p>🍳 ${h.extra}</p><p>💴 ${h.price}</p><p>🚉 ${h.transport}</p><div class="hotel-map-actions"><a class="map-btn" href="${h.map}" target="_blank" rel="noopener">📍 פתח מפה ↗</a></div></div>`}
function rebuildHotelsPage(){const p=$('#page-hotels');if(!p||p.dataset.canonicalHotels==='1')return;p.dataset.canonicalHotels='1';p.innerHTML=`<div class="page-head"><button onclick="closePage()">←</button><h2>🏨 מלונות</h2></div><div class="hotel-city"><h3>🗼 Tokyo · ${HOTELS.tokyo1.dates}</h3>${card(HOTELS.tokyo1,'הוזמן')}</div><div class="hotel-city"><h3>♨️ Hakone / Fuji · 8–10 Nov 2026</h3><div class="hotel-note">⏳ <b>המלון עדיין לא נסגר</b></div></div><div class="hotel-city"><h3>⛩️ Kyoto · ${HOTELS.kyoto.dates}</h3>${card(HOTELS.kyoto,'הוזמן')}</div><div class="hotel-city"><h3>🏯 Osaka · ${HOTELS.osaka.dates}</h3>${card(HOTELS.osaka,'הוזמן · סופי')}</div><div class="hotel-city"><h3>🗼 Tokyo · ${HOTELS.tokyo2.dates}</h3>${card(HOTELS.tokyo2,'הוזמן ושולם')}</div>`}
function replaceCancelledText(){const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{let s=n.nodeValue||'';if(/Cross Hotel Osaka/i.test(s))s=s.replace(/Cross Hotel Osaka(?:（ORIX HOTELS & RESORTS）)?/gi,'Hotel Royal Classic Osaka');if(/remm Tokyo Kyobashi/i.test(s))s=s.replace(/remm Tokyo Kyobashi/gi,'Hotel Metropolitan Tokyo Marunouchi');n.nodeValue=s});}
function normalizeItineraryHotels(){
 $$('.day .stop-card').forEach(c=>{const t=c.textContent||'';
  if(/Hotel Royal Classic Osaka|Cross Hotel Osaka/i.test(t)){const h=c.querySelector('h3');if(h)h.textContent='Hotel Royal Classic Osaka';const p=c.querySelector('p');if(p&&/Cross|Osaka Hotel|Check-in|לינה|מלון/i.test(p.textContent||''))p.textContent='המלון שלנו באוסקה · 14–16/11 · Namba · Osaka Metro Exit 12 · מחובר ישירות למלון';}
  if(/Hotel Metropolitan Tokyo Marunouchi|remm Tokyo Kyobashi/i.test(t)){const h=c.querySelector('h3');if(h)h.textContent='Hotel Metropolitan Tokyo Marunouchi';const p=c.querySelector('p');if(p&&/remm|Tokyo|לינה|מלון/i.test(p.textContent||''))p.textContent='המלון שלנו ללילה האחרון בטוקיו · 16–17/11 · Sapia Tower ליד Tokyo Station';}
 });
}
function migrateExpenses(){try{const k='japanTrip_expenses_v1';const raw=localStorage.getItem(k);if(!raw)return;const a=JSON.parse(raw);if(!Array.isArray(a))return;let changed=false;for(let i=a.length-1;i>=0;i--){if(/Cross Hotel Osaka|remm Tokyo Kyobashi/i.test(a[i].name||'')){a.splice(i,1);changed=true}}
 let o=a.find(x=>/Hotel Royal Classic Osaka/i.test(x.name||''));if(!o){a.push({id:Date.now()+1,name:'Hotel Royal Classic Osaka',status:'מוזמן',payment:'אשראי',currency:'JPY',amount:109398,category:'🏨 לינה',included:true,note:'14–16/11 · סופי'});changed=true}else{o.status='מוזמן';o.included=true;o.note='14–16/11 · סופי';}
 let m=a.find(x=>/Hotel Metropolitan Tokyo Marunouchi/i.test(x.name||''));if(!m){a.push({id:Date.now()+2,name:'Hotel Metropolitan Tokyo Marunouchi',status:'שולם',payment:'אשראי',currency:'ILS',amount:676.61,category:'🏨 לינה',included:true,note:'16–17/11 · QXU287073'});changed=true}else{Object.assign(m,{status:'שולם',currency:'ILS',amount:676.61,included:true,note:'16–17/11 · QXU287073'});changed=true}
 if(changed)localStorage.setItem(k,JSON.stringify(a));}catch(e){}}
function setVersion(){const v=$('header .logo .app-version')||$('header .logo small');if(v)v.textContent='2026 · '+VERSION;document.title='Japan Trip 2026 · '+VERSION;document.documentElement.dataset.appReady=VERSION}
function run(){rebuildHotelsPage();replaceCancelledText();normalizeItineraryHotels();migrateExpenses();setVersion()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,120),{once:true});else setTimeout(run,120);setTimeout(setVersion,1000);
})();