// Japan Trip v9.12m - one-time content audit: itinerary, places, restaurants, hotels
(function(){'use strict';
const VERSION='v9.12m';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const norm=s=>(s||'').replace(/[·⭐👓]/g,' ').replace(/\s+/g,' ').trim().toLowerCase();
const G=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
const D={
'Shinjuku':{d:'אחד המרכזים הגדולים של טוקיו: תחנת ענק, קניות, גורדי שחקים וחיי לילה. בערב הראשון נשתמש בו בעיקר להתאקלמות, ארוחה ושיטוט קצר ליד המלון.',t:'תחנת Shinjuku עצומה; לפני היציאה בדקו את שם היציאה. המלון שלנו קרוב ל-JR South Exit.',f:['מערב Shinjuku הוא אזור גורדי השחקים ובניין ממשלת טוקיו; הצד המזרחי תוסס יותר בערב.','אין צורך לנסות לכסות את כל Shinjuku בערב הראשון.'],q:'Shinjuku Tokyo'},
'JINS Shinjuku':{d:'תחנת הקניות החשובה שלנו למשקפיים: בחירת מסגרת, בדיקת ראייה והזמנת עדשות. נעדיף לבצע בתחילת השהות בטוקיו כדי להשאיר זמן לאיסוף או תיקון.',t:'להביא את המשקפיים הנוכחיים או מרשם אם יש, ולברר בזמן ההזמנה מתי בדיוק האיסוף.',f:['אם העדשות אינן זמינות מיידית, נשאיר את חלון ההשלמות בסוף הטיול לאיסוף.'],q:'JINS Shinjuku Tokyo'},
'Kaminarimon':{d:'שער הרעם האדום והכניסה המזוהה ביותר עם Asakusa ו-Sensō-ji. הפנס הגדול במרכז הוא אחד הסמלים המצולמים של טוקיו.',t:'עצירת צילום קצרה; עיקר החוויה ממשיכה דרך Nakamise אל Sensō-ji.',f:['מכאן המסלול ממשיך טבעית ברגל דרך רחוב Nakamise.'],q:'Kaminarimon Tokyo'},
'Nakamise':{d:'רחוב קניות מסורתי שמוביל מ-Kaminarimon אל Sensō-ji, עם מזכרות, ממתקים יפניים ועבודות יד.',t:'להסתכל קודם ורק אחר כך לקנות; הרחובות הצדדיים של Asakusa לרוב רגועים יותר.',f:['זה חלק מהדרך למקדש ולא יעד שצריך להקדיש לו שעות.'],q:'Nakamise Shopping Street Tokyo'},
'Sensō-ji':{d:'המקדש הבודהיסטי העתיק ביותר בטוקיו והלב ההיסטורי של Asakusa. הדרך דרך Kaminarimon ו-Nakamise היא חלק מהחוויה.',t:'כדאי להגיע מוקדם יחסית לפני שהציר הראשי מתמלא.',f:['אחרי האולם הראשי שווה להציץ גם ברחובות הצדדיים ולא רק לחזור באותה דרך.'],q:'Sensoji Tokyo'},
'Ueno':{d:'אזור שמשלב פארק גדול, מוזיאונים ותחנת תחבורה חשובה. אצלנו הוא משמש מעבר נעים בין Asakusa ל-Ameyoko.',t:'אין צורך להפוך את העצירה ליום מוזיאונים; נשמור זמן ל-Ameyoko.',f:['Ueno Park ו-Ameyoko נמצאים במרחק הליכה נוח זה מזה.'],q:'Ueno Tokyo'},
'Ameyoko Market':{d:'שוק רחוב עממי ותוסס בין Ueno ל-Okachimachi, עם בגדים, קוסמטיקה, מזון, ממתקים ודוכנים.',t:'מתאים גם לקניות קטנות ולא רק לאוכל; פשוט לשוטט ולבחור מה שמעניין.',f:['האופי כאן שונה מאוד מבתי הכלבו המסודרים של Ginza ו-Shinjuku.'],q:'Ameyoko Shopping District Tokyo'},
'Akihabara':{d:'רובע האלקטרוניקה, גיימינג, אנימה ואספנות של טוקיו. גם בלי עניין עמוק באנימה, האורות והחנויות הרב-קומתיות נותנים חוויה ייחודית.',t:'לבחור 1–2 חנויות שמעניינות אותנו במקום לנסות להיכנס לכל בניין.',f:['הערב מתאים במיוחד לאזור בגלל התאורה והאווירה.'],q:'Akihabara Tokyo'},
'Meiji Shrine':{d:'מקדש שינטו מרכזי בתוך יער גדול ליד Harajuku. ההליכה דרך היער ושערי ה-Torii היא חלק מהחוויה לא פחות מהמקדש עצמו.',t:'מתאים לפתיחת היום לפני שהחנויות ב-Harajuku נפתחות.',f:['האווירה שקטה מאוד ביחס לאזורי הקניות שנמצאים דקות הליכה ממנו.'],q:'Meiji Jingu Tokyo'},
'Harajuku':{d:'מרכז של אופנה צעירה ותרבות רחוב. Takeshita Street הוא הצד הצבעוני והעמוס, בעוד Omotesando הסמוכה אלגנטית יותר.',t:'מספיק שיטוט ממוקד; לא צריך להקדיש חצי יום ל-Takeshita Street.',f:['השילוב Meiji → Harajuku → Omotesando → Shibuya יעיל מאוד ברגל.'],q:'Harajuku Tokyo'},
'Omotesando':{d:'שדרה רחבה של אדריכלות, אופנה ובוטיקים שמחברת את Harajuku לכיוון Shibuya.',t:'נשלב אותה בהליכה ולא כנסיעה נפרדת.',f:['זה אזור טוב לשלב בו גם קניות איכותיות, כולל Onitsuka Tiger אם נרצה.'],q:'Omotesando Tokyo'},
'Shibuya Crossing':{d:'מעבר החצייה האייקוני של Shibuya, מוקף במסכי ענק, חנויות ותחנת Shibuya. פסל Hachiko נמצא ממש ליד.',t:'לחצות פעם-פעמיים ולהמשיך לשיטוט באזור; אין צורך להתעכב רק על המעבר.',f:['החוויה חזקה יותר כשהאזור כבר מואר.'],q:'Shibuya Crossing Tokyo'},
'Shibuya Sky':{d:'תצפית פתוחה מעל Shibuya Scramble Square, עם מבט רחב על העיר. היא מרשימה במיוחד סביב שקיעה אבל דורשת כרטיס לשעה מוגדרת.',t:'נשאיר כאפשרות ולא נבנה יום שלם סביב סלוט לא נוח.',f:['אם אין שעה טובה, Tokyo Metropolitan Government Building הוא גיבוי גמיש יותר.'],q:'Shibuya Sky Tokyo'},
'Tokyo Metropolitan Government Building Observatory':{d:'תצפית גבוהה ב-Shinjuku שמתאימה במיוחד כי אנחנו ממילא באזור. היתרון העיקרי הוא גמישות לעומת תצפיות שמצריכות סלוט מדויק.',t:'נעלה רק אם הראות טובה; ביום מעונן אין סיבה לבזבז זמן.',f:['מתאים לשילוב עם Shinjuku/JINS בלי נסיעה מיוחדת.'],q:'Tokyo Metropolitan Government Building Observatory'},
'Roppongi Hills Tokyo City View':{d:'תצפית באזור Roppongi עם זווית טובה על מרכז טוקיו ובמיוחד על Tokyo Tower.',t:'נבחר בה רק אם Roppongi משתלב באותו ערב; לא נוסעים במיוחד לעוד תצפית.',f:['Roppongi עצמו משלב אמנות, קניות ומסעדות ולכן כדאי רק כחלק מערב באזור.'],q:'Tokyo City View Roppongi Hills'},
'Tsukiji Outer Market':{d:'שוק האוכל החיצוני ההיסטורי של Tsukiji, עם דגים, סכינים, תה, אצות, Tamagoyaki, פירות ומנות קטנות. גם מי שלא רוצה דג נא מוצא הרבה אפשרויות.',t:'להגיע בבוקר; חלק מהחנויות נסגרות מוקדם יחסית.',f:['המטרה אצלנו היא גם האווירה והחנויות, לא רק ארוחת סושי.'],q:'Tsukiji Outer Market Tokyo'},
'Ginza':{d:'רובע קניות ובילוי אלגנטי עם בתי כלבו, חנויות דגל, גלריות ומסעדות. גם בלי קניות יוקרה יש הרבה מה לראות.',t:'לעשות חלון קניות ממוקד ולא להפוך אותו לחצי יום.',f:['Itoya וקומות האוכל בבתי הכלבו הן אפשרויות טובות גם בלי קניות אופנה.'],q:'Ginza Tokyo'},
'Imperial Palace':{d:'מתחם הארמון הקיסרי נמצא בשטח טירת Edo לשעבר. רוב אזור המגורים אינו פתוח לשיטוט חופשי, אבל החפירים, החומות והגנים נותנים תחושת מרחב והיסטוריה.',t:'אם הזמן קצר, עצירה באזור החפיר/Nijubashi מספיקה לפני Marunouchi.',f:['לא לבנות על כניסה חופשית לכל מתחם הארמון.'],q:'Imperial Palace Tokyo'},
'Tokyo Station / Marunouchi':{d:'Tokyo Station היא גם מרכז תחבורה וגם אתר: חזית הלבנים בצד Marunouchi, מתחמי אוכל וחנויות, והאזור העסקי האלגנטי שסביבה.',t:'כשאנחנו כבר באזור, כדאי לצאת לצד Marunouchi לכמה דקות ולא לקבוע ביקור נפרד.',f:['הלילה האחרון שלנו במלון Metropolitan נמצא בצד Nihombashi של אותה תחנה.'],q:'Tokyo Station Marunouchi'},
'Lake Ashi':{d:'אגם הררי שהוא אחד הסמלים של Hakone. ביום בהיר אפשר לראות ממנו את Fuji, ועל שפתו נמצא Hakone Shrine.',t:'אם הראות טובה בבוקר, לתת לנוף Fuji עדיפות לפני שהעננות מתפתחת.',f:['אפשר לשלב תצפית, הליכה קצרה או שיט בהתאם למזג האוויר.'],q:'Lake Ashi Hakone'},
'Hakone Shrine':{d:'מקדש שינטו מיוער לצד Lake Ashi, מוכר במיוחד בזכות שער ה-Torii האדום שעל שפת האגם.',t:'לשער שעל המים עשוי להיות תור לצילום; לא חייבים להמתין אם הוא ארוך.',f:['המקדש עצמו בתוך היער שווה גם בלי צילום מושלם ליד האגם.'],q:'Hakone Shrine'},
'Owakudani':{d:'עמק געשי פעיל ב-Hakone עם אדים, ריח גופרית ונוף דרמטי. ביום בהיר יש גם אפשרות לתצפית לכיוון Fuji.',t:'לבדוק בבוקר מצב תפעולי; רוח או פעילות געשית עשויות להשפיע על הגישה והרכבל.',f:['הביצים השחורות המבושלות במים הגעשיים הן אחד הסמלים המקומיים.'],q:'Owakudani Hakone'},
'Hakone Ropeway':{d:'הרכבל של Hakone עובר מעל האזור הגעשי ומחבר בין תחנות מרכזיות; הנסיעה עצמה היא חלק מהחוויה בזכות הנוף.',t:'ביום עם ראות טובה כדאי להתייחס לנסיעה כאטרקציה ולא רק תחבורה.',f:['תפעול יכול להשתנות לפי מזג אוויר ורוח.'],q:'Hakone Ropeway Owakudani'},
'Kawaguchiko':{d:'Lake Kawaguchi הוא אחד מחמשת אגמי Fuji ואחד המקומות הפופולריים לתצפית קרובה על ההר. בנובמבר האזור יכול להיות יפה במיוחד בשלכת.',t:'ניסע רק אם תחזית הראות טובה; ביום סגור הסטייה פחות משתלמת.',f:['זה יעד שתלוי יותר במזג האוויר מרוב האתרים במסלול.'],q:'Lake Kawaguchi Japan'},
'Hakone Open-Air Museum':{d:'מוזיאון פתוח גדול שמשלב פסלים מודרניים עם נוף ההרים. לפי האתר הרשמי יש כ-120 פסלים בשטח של כ-70,000 מ״ר, לצד חללים מקורים ואמבט רגליים.',t:'פתוח 09:00–17:00, כניסה אחרונה 16:30; מתאים במיוחד אם נשאר חלון נוח ביום Hakone.',f:['הביקור מרגיש יותר כמו פארק אמנות מאשר מוזיאון סגור.','תחנת Chokoku-no-Mori קרובה מאוד למוזיאון.'],q:'Hakone Open-Air Museum'},
'Gion':{d:'הרובע המסורתי של קיוטו, המזוהה עם machiya מעץ, בתי תה ותרבות geiko/maiko. האווירה טובה במיוחד לקראת ערב.',t:'לכבד מגבלות צילום ורכוש פרטי; זה אזור מגורים ועבודה, לא אתר שעשועים.',f:['Shirakawa ו-Hanamikoji הם אזורים טובים לשיטוט רגוע.'],q:'Gion Kyoto'},
'Kiyomizu-dera':{d:'אחד המקדשים הידועים בקיוטו, על מורדות Higashiyama, עם מרפסת עץ ונוף רחב על העיר. הדרך דרך הרחובות ההיסטוריים היא חלק מרכזי מהביקור.',t:'להמשיך ממנו ברגל דרך Sannenzaka/Ninenzaka ו-Higashiyama במקום לחזור באותה דרך.',f:['הגעה מוקדמת עוזרת לפני עומסי הקבוצות.'],q:'Kiyomizu-dera Kyoto'},
'Sannenzaka & Ninenzaka':{d:'רחובות היסטוריים על מדרון Higashiyama עם בתי עץ, בתי תה, קרמיקה, ממתקים וחנויות קטנות.',t:'הכי נעים מוקדם או לקראת ערב; בשעות השיא הם יכולים להיות עמוסים מאוד.',f:['הם החיבור הטבעי בין Kiyomizu-dera לאזור Yasaka/Gion.'],q:'Ninenzaka Sannenzaka Kyoto'},
'Higashiyama':{d:'אזור היסטורי במזרח קיוטו שמחבר מקדשים, רחובות ישנים ובתי עץ. אצלנו זה מקטע שיטוט ולא אתר יחיד.',t:'להתקדם בקצב דרך האזור ולא לנסות לסמן כל סמטה כיעד נפרד.',f:['המסלול הטבעי ממשיך לכיוון Yasaka ו-Gion.'],q:'Higashiyama Kyoto'},
'Pontocho':{d:'סמטה צרה ליד נהר Kamo עם מסעדות וברים קטנים, שמתאימה במיוחד לסיום ערב בקיוטו.',t:'לא חייבים לבחור את המסעדה הכי עמוסה; יש הרבה אפשרויות באזור המקביל לנהר.',f:['הערך העיקרי הוא באווירת הערב ובשיטוט.'],q:'Pontocho Kyoto'},
'Arashiyama Bamboo Grove':{d:'יער הבמבוק המפורסם הוא חלק מאזור Arashiyama הרחב יותר, שכולל Tenryu-ji, נהר, גשר ואזורים שקטים יותר לכיוון Okusaga.',t:'אם היער הראשי עמוס, לא נילחם בקהל; נמשיך ל-Giōji או Adashino Nenbutsu-ji.',f:['בנובמבר האזור פופולרי במיוחד בגלל השלכת.'],q:'Arashiyama Bamboo Forest Kyoto'},
'Tenryu-ji':{d:'מקדש זן מרכזי ב-Arashiyama עם גן שמנצל את ההרים כרקע. הוא מתחבר בצורה טבעית למסלול לכיוון יער הבמבוק.',t:'להיכנס דרך המקדש והגן ולהמשיך מהיציאה לכיוון הבמבוק, בלי הלוך-חזור.',f:['נותן גם מקדש וגם גן יפני באותה עצירה.'],q:'Tenryu-ji Kyoto'},
'Kinkaku-ji':{d:'מקדש הזהב הוא אחד הסמלים של קיוטו: ביתן מצופה זהב לצד בריכה, עם מסלול הליכה מסודר דרך הגן.',t:'האתר קומפקטי; בדרך כלל אין צורך ביותר מכשעה.',f:['זה אתר חובה במסלול שלנו, גם אם הוא עמוס.'],q:'Kinkaku-ji Kyoto'},
'Nishiki Market':{d:'שוק מקורה צר במרכז קיוטו המכונה “המטבח של קיוטו”, עם חנויות שמתמחות בתה, חמוצים, סכינים, ממתקים, טופו, דגים ותוצרת מקומית.',t:'לאכול ליד הדוכן שבו קנינו ולא ללכת עם אוכל לאורך השוק.',f:['מתאים לשיטוט וטעימות ולא רק לארוחה מלאה.'],q:'Nishiki Market Kyoto'},
'Fushimi Inari':{d:'מקדש שינטו חשוב בדרום קיוטו, מפורסם באלפי שערי Torii אדומים לאורך שבילי הר Inari. פסלי השועלים קשורים לשליחיו של Inari.',t:'אין צורך להגיע לפסגה; אחרי שמקבלים את חוויית השערים והיער אפשר להסתובב ולרדת.',f:['אצלנו: 12/11 ב-09:00, לפני Tofuku-ji.'],q:'Fushimi Inari Taisha Kyoto'},
'Tofuku-ji':{d:'מקדש זן גדול מדרום-מזרח קיוטו, מפורסם במיוחד בשלכת ובמבט מעל עמק המייפלים מאזור גשר Tsutenkyo.',t:'בנובמבר זה אחד מאתרי השלכת המבוקשים; נגיע אחרי Fushimi Inari בגלל הקרבה הגאוגרפית.',f:['השילוב עם Fushimi Inari חוסך נסיעות הלוך-חזור.'],q:'Tofuku-ji Kyoto'},
'Sanjusangen-do':{d:'אולם עץ ארוך שמכיל 1,001 דמויות של Kannon. החוויה המרכזית היא בתוך האולם והיא שונה מאוד ממקדשי הגנים והנוף.',t:'לא לדלג רק מפני שהחזית צנועה; הפנים הוא הסיבה לביקור.',f:['ביקור יחסית קומפקטי שמתאים היטב בין Tofuku-ji ל-Kyoto Station.'],q:'Sanjusangen-do Kyoto'},
'Kyoto Station':{d:'תחנת Kyoto היא גם מבנה מודרני מרשים עם חלל מרכזי עצום, מדרגות ומרפסות תצפית, ולא רק נקודת תחבורה.',t:'להרים מבט ולעלות למרפסת אם נשאר זמן לפני teamLab.',f:['Higashi Hongan-ji נמצא בקרבת התחנה ויכול להשתלב אם הזמן מאפשר.'],q:'Kyoto Station'},
'teamLab Biovortex Kyoto':{d:'מוזיאון אמנות דיגיטלית immersive קבוע של teamLab בקיוטו, שנפתח ב-2025. זו אחת מחוויות החובה של הטיול שלנו ולא אופציה.',t:'⭐ חובה · להזמין כרטיס לשעה מוגדרת מראש. לפי האתר הרשמי שעות הפעילות הן 09:00–21:00 והכניסה האחרונה 19:30, בכפוף לשינויים.',f:['כ-7 דקות הליכה מ-Kyoto Station Hachijo East Gate.','כתובת: 21-5 Higashikujo Higashi-Iwamotocho, Minami-ku, Kyoto.','נשלב בערב 12/11 אחרי אתרי היום.'],q:'teamLab Biovortex Kyoto'},
'Giōji Temple':{d:'מקדש קטן ושקט באזור Okusaga, מוכר בזכות גן טחב, במבוק ועצי מייפל. בנובמבר השילוב של טחב ירוק ושלכת יכול להיות יפה במיוחד.',t:'האלטרנטיבה המועדפת שלנו אם יער הבמבוק המרכזי עמוס.',f:['האווירה כאן אינטימית בהרבה מה-Bamboo Grove המרכזי.'],q:'Gioji Temple Kyoto'},
'Adashino Nenbutsu-ji':{d:'מקדש באזור השקט של Okusaga, מוכר באלפי פסלי אבן ובשביל במבוק קטן.',t:'מתאים אם יש כוח להמשיך מעט עמוק יותר לתוך Okusaga.',f:['נותן שילוב של היסטוריה ובמבוק בלי העומס של היער הראשי.'],q:'Adashino Nenbutsuji Kyoto'},
'Nara Park':{d:'פארק עצום בנארה שבו מסתובבים איילי sika בחופשיות, ובתוכו ובסביבתו נמצאים אתרים מרכזיים כמו Tōdai-ji. לפי אתר התיירות הרשמי האזור משתרע על כ-660 הקטרים.',t:'לקנות shika-senbei רק כשבאמת רוצים להאכיל; האיילים מזהים את הקרקרים ומתקבצים מהר.',f:['האיילים הם חלק מהדרך בין האתרים, לא האטרקציה היחידה.','אצלנו יום נארה הוא 14/11 לפני המעבר לאוסקה.'],q:'Nara Park'},
'Tōdai-ji':{d:'אחד המקדשים הבודהיסטיים החשובים ביפן. אולם Daibutsuden מכיל פסל בודהה ברונזה בגובה כ-15 מטר והוא השיא התרבותי של יום נארה.',t:'לא לוותר עליו גם אם האיילים גונבים את ההצגה.',f:['הכניסה דרך Nandaimon מוסיפה חלק מרשים לביקור.','אצלנו: 14/11 במסגרת יום Nara.'],q:'Todaiji Temple Nara'},
'Naramachi':{d:'רובע היסטורי של בתי machiya, חנויות קטנות ובתי קפה מדרום למרכז נארה. הוא מתאים כתוספת רגועה אחרי האתרים הגדולים.',t:'נשאיר כאופציה לפי הזמן והעייפות ביום נארה.',f:['לא חייבים להגיע אם יום Nara מתארך.'],q:'Naramachi Nara'},
'Kuromon Market':{d:'שוק מקורה באוסקה המכונה “המטבח של אוסקה”. לפי אתר התיירות הרשמי הוא משתרע על כ-580 מטר וכולל בערך 150 חנויות של דגים, בשר, פירות, ירקות, אוכל ועוד.',t:'השעות משתנות מחנות לחנות. נעבור קודם לאורך השוק ואז נחליט איפה לעצור.',f:['נמצא ממש ליד Nippombashi Station.','כרגע לא נקבעה לו שעה סופית במסלול, ולכן לא נציג תאריך שגוי.'],q:'Kuromon Ichiba Market Osaka'},
'Namba':{d:'מרכז התחבורה, הקניות והבילויים של דרום Osaka. Dotonbori, Shinsaibashi, Hozenji ו-Kuromon נמצאים בטווח הליכה.',t:'מרגע שמגיעים ל-Namba עדיף לעבור ברגל בין האתרים הקצרים.',f:['המלון שלנו Royal Classic מחובר ישירות ל-Osaka Metro Namba Exit 12.'],q:'Namba Osaka'},
'Hozenji Yokocho':{d:'סמטת אבן קטנה עם פנסים ליד מקדש Hozenji, דקות הליכה מ-Dotonbori. היא נותנת ניגוד שקט ואינטימי יותר לאורות של Namba.',t:'עצירה קצרה בדרך ל-Dotonbori, לא יעד של שעה.',f:['מתאימה במיוחד אחרי הצ׳ק-אין בערב הראשון באוסקה.'],q:'Hozenji Yokocho Osaka'},
'Dotonbori':{d:'אזור הבילויים והאוכל המזוהה ביותר עם Osaka סביב התעלה, עם שלטי ניאון, מסעדות וה-Glico Running Man.',t:'להגיע אחרי החשיכה. אם מקום אחד מלא, לא לעמוד שעה — יש המון חלופות באזור.',f:['זה חלק מאזור Minami/Namba ולכן משתלב ברגל עם Hozenji ו-Shinsaibashi.'],q:'Dotonbori Osaka'},
'Osaka Castle':{d:'טירת Osaka והפארק שסביבה הם אחד הסמלים ההיסטוריים של העיר. המבנה הנוכחי הוא שחזור מודרני ובתוכו מוזיאון.',t:'אם פחות מעניין אותנו מוזיאון, אפשר ליהנות מאוד מהפארק ומהטירה מבחוץ ולחסוך תור.',f:['החפירים והשטחים הירוקים הם חלק משמעותי מהביקור.'],q:'Osaka Castle'},
'Umeda':{d:'מרכז מודרני בצפון Osaka עם תחנות רכבת גדולות, קניונים וגורדי שחקים.',t:'נשתמש בו לחלון ממוקד של קניות/תצפית ולא ננסה לכסות את כל המתחם.',f:['התחנות באזור מורכבות; כדאי לבדוק מראש את היציאה ליעד הספציפי.'],q:'Umeda Osaka'},
'Shinsaibashi':{d:'אחד מאזורי הקניות המרכזיים של Osaka, עם רחוב מקורה ארוך שמתחבר כמעט ישירות ל-Dotonbori.',t:'נעשה אותו כחלק מההליכה לכיוון Dotonbori/Namba ולא כנסיעה נפרדת.',f:['יש שילוב של מותגים בינלאומיים, אופנה יפנית וקוסמטיקה.'],q:'Shinsaibashi-suji Osaka'},
'Gyukatsu Motomura Shinjuku':{d:'מסעדת gyukatsu שבה קציצת/נתח הבקר המצופה מטוגן medium-rare ומסיימים את הצלייה בעצמנו על אבן חמה. זו חוויה יפנית נגישה גם למי שלא מחפש דגים.',t:'לפי האתר הרשמי סניף Shinjuku Main פתוח 11:00–22:00, הזמנה אחרונה 21:30, ללא יום סגירה קבוע.',f:['אפשר לשלוט במידת הצלייה על האבן.','מתאים במיוחד לערב Shinjuku.'],q:'Gyukatsu Motomura Shinjuku Main Store'},
'Uobei Shibuya Dogenzaka':{d:'סושי מהיר שבו מזמינים ממסך והמנות מגיעות ישירות לעמדה. יש גם מנות מבושלות וצדדים, כך שהוא מתאים לנו גם בלי להתמקד בדג נא.',t:'בחירה טובה לארוחה מהירה באזור Shibuya; בשעות עומס ייתכן תור.',f:['היתרון הוא קצב מהיר ואפשרות להזמין פריטים בודדים לפי החשק.'],q:'Uobei Shibuya Dogenzaka'},
'Afuri Harajuku':{d:'רשת ראמן מוכרת שמזוהה עם Yuzu Shio Ramen — מרק צלול וארומטי עם יוזו — לצד tsukemen ומנות אורז.',t:'מתאים אם רוצים ראמן קל ורענן יחסית בזמן שאנחנו כבר באזור Harajuku.',f:['האתר הרשמי מציג את Harajuku כאחד מסניפי AFURI הפעילים.'],q:'AFURI Harajuku'},
'Katsukura Kyoto':{d:'רשת קיוטואית המתמחה ב-tonkatsu. סניף Kyoto Porta נוח במיוחד בגלל החיבור ל-Kyoto Station.',t:'סניף Kyoto Porta פתוח לפי האתר הרשמי 11:00–22:00, הזמנה אחרונה 21:30, ואינו מקבל הזמנות מקום.',f:['מתאים במיוחד ביום שבו אנחנו עוברים באזור Kyoto Station.'],q:'Katsukura Kyoto Porta'},
'Musashi Sushi Kyoto Station':{d:'אפשרות סושי נוחה באזור Kyoto Station עם מגוון פריטים, כולל אפשרויות מבושלות. מתאים כשצריך ארוחה פשוטה בלי סטייה מהמסלול.',t:'נשתמש בו כאפשרות ולא כיעד שחייבים להגיע אליו במיוחד.',f:['למי שפחות אוהב דג נא אפשר לבחור פריטים מבושלים וצדדים.'],q:'Musashi Sushi Kyoto Station'},
'Mizuno Osaka':{d:'מסעדת okonomiyaki ותיקה ב-Dotonbori. באתר הרשמי מופיעים Mizuno-yaki ו-Yamaimo-yaki כמנות דגל.',t:'לפי האתר הרשמי: 11:00–22:00, פתוח מדי יום; ייתכנו תורים בגלל המיקום והפופולריות.',f:['כתובת: 1-4-15 Dotonbori, כ-5 דקות הליכה מ-Namba.'],q:'Mizuno Okonomiyaki Dotonbori Osaka'},
'551 Horai':{d:'רשת אוסקאית מפורסמת במיוחד ב-butanman — לחמניות מאודות במילוי חזיר — לצד shumai ומנות נוספות.',t:'מתאים כטעימה/נשנוש מהיר ולא בהכרח כארוחה מלאה.',f:['יש מספר סניפים באזור Namba; נבחר את הקרוב לפי המסלול בפועל.'],q:'551 HORAI Namba Osaka'},
'Namba Ramen Ichiza':{d:'מתחם ראמן בקומה 9 של EDION Namba שמרכז כמה סגנונות ראמן במקום אחד, ולכן הוא נוח כשלא רוצים להתחייב למסעדה אחת מראש.',t:'אופציה טובה כשאנחנו כבר ב-Namba/Dotonbori; לבדוק באותו יום את שעות הפעילות של המתחם.',f:['המיקום בתוך EDION Namba הופך אותו לקל לשילוב בערב קניות/שיטוט.'],q:'Namba Ramen Ichiza EDION Namba'}
};
const A={
'jins shinjuku 👓':'JINS Shinjuku','kinkaku-ji · מקדש הזהב':'Kinkaku-ji','fushimi inari taisha':'Fushimi Inari','sanjūsangen-dō':'Sanjusangen-do','sanju sangen do':'Sanjusangen-do','tokyo station & marunouchi':'Tokyo Station / Marunouchi','kawaguchiko / fuji':'Kawaguchiko','fuji / kawaguchiko':'Kawaguchiko','hozenji temple + hozenji yokocho':'Hozenji Yokocho','חוויית במבוק arashiyama / okusaga':'Arashiyama Bamboo Grove'};
function key(name){const n=norm(name);if(A[n])return A[n];return Object.keys(D).find(k=>norm(k)===n)||name}
function ensureGuideButton(card,name){if(!card||card.querySelector('.guide-tips-btn,.info-modal-btn,.place-info-btn'))return;const a=card.querySelector('.stop-actions,.place-actions,.hotel-map-actions')||(()=>{const x=document.createElement('div');x.className='stop-actions';card.appendChild(x);return x})();const b=document.createElement('button');b.type='button';b.className='info-modal-btn guide-tips-btn';b.dataset.place=name;b.textContent='ℹ️ מדריך וטיפים';a.prepend(b)}
function updatePlaces(){
 $$('#placesGrid .place-card').forEach(c=>{const h=$('h3',c);if(!h)return;const k=key(h.textContent),d=D[k];if(!d)return;const p=$(':scope > p',c);if(p)p.textContent=d.d;else{const x=document.createElement('p');x.textContent=d.d;$('.place-actions',c)?.before(x)}let tip=$('.place-card-tip',c);if(!tip){tip=document.createElement('div');tip.className='place-card-tip';$('.place-actions',c)?.before(tip)}tip.textContent='💡 '+d.t;ensureGuideButton(c,k)});
 // Correct stale schedule/city metadata after the itinerary changed.
 const fix=(re,city,scheduled,label)=>{$$('#placesGrid .place-card').forEach(c=>{if(!re.test($('h3',c)?.textContent||''))return;c.dataset.city=city;c.dataset.scheduled=scheduled?'1':'0';let loc=$('.place-location',c);if(loc)loc.textContent='📍 '+city;let b=$('.scheduled-badge',c);if(scheduled){if(!b){b=document.createElement('div');b.className='scheduled-badge';$('.place-card-meta',c)?.after(b)}b.textContent='🟢 במסלול · '+label}else if(b)b.remove()})};
 fix(/Fushimi Inari/i,'קיוטו',true,'12/11 · 09:00');fix(/Nara Park/i,'נארה',true,'14/11 · יום Nara');fix(/Tōdai-ji|Todaiji/i,'נארה',true,'14/11 · יום Nara');fix(/teamLab Biovortex Kyoto/i,'קיוטו',true,'12/11 · ערב · ⭐ חובה');fix(/^Kinkaku-ji/i,'קיוטו',true,'13/11 · 12:30');fix(/Kuromon Market/i,'אוסקה',false,'');
 // Add the two new Nov-12 places if the base Places list does not have them.
 [['Tofuku-ji','קיוטו','⛩️'],['Sanjusangen-do','קיוטו','🏯']].forEach(([n,city,icon])=>{if($$('#placesGrid .place-card h3').some(h=>norm(h.textContent)===norm(n)))return;const d=D[n],a=document.createElement('article');a.className='place-card';a.dataset.cat='מקדשים';a.dataset.city=city;a.dataset.scheduled='1';a.innerHTML='<div class="place-title"><span>'+icon+'</span><h3>'+n+'</h3></div><div class="place-location">📍 '+city+'</div><div class="place-card-meta">מקדשים</div><div class="scheduled-badge">🟢 במסלול · 12/11</div><p></p><div class="place-card-tip"></div><div class="place-actions"></div>';a.querySelector('p').textContent=d.d;a.querySelector('.place-card-tip').textContent='💡 '+d.t;$('#placesGrid')?.appendChild(a);ensureGuideButton(a,n)});
 // Make Ramen Ichiza behave like every other restaurant card.
 $$('#placesGrid .place-card').forEach(c=>{if(/Namba Ramen Ichiza/i.test(c.textContent||''))ensureGuideButton(c,'Namba Ramen Ichiza')});
}
function updateRouteButtons(){
 $$('.day .stop-card').forEach(c=>{const h=$('h3',c);if(!h)return;const k=key(h.textContent);if(D[k])ensureGuideButton(c,k)});
 // Hotel itinerary stops also get the same guide behavior.
 $$('.hotel-itinerary-stop .stop-card').forEach(c=>{const n=($('h3',c)?.textContent||'').replace(/^Check-in\s*·\s*/i,'').trim();if(n)ensureGuideButton(c,n)});
}
function hotelData(name){const n=norm(name);if(n.includes('jr kyushu'))return{d:'המלון שלנו בטוקיו 4–8/11. לפי האתר הרשמי הוא כ-3 דקות הליכה מ-JR Shinjuku South Exit, ב-2-6-2 Yoyogi, Shibuya-ku.',t:'עם מזוודות לכוון ל-JR South Exit; המלון נמצא ליד Shinjuku Expressway Bus Terminal.',f:['מיקום מצוין להתחלת וסיום ימי טוקיו.'],q:'JR Kyushu Hotel Blossom Shinjuku'};if(n.includes('richmond hotel premier kyoto'))return{d:'המלון שלנו בקיוטו 10–14/11, באזור Shijo/Karasuma. הוא משמש בסיס לכל ימי קיוטו ויום Nara.',t:'לשמור את שם המלון והכתובת זמינים לנסיעות ערב וחזרה מ-Nara.',f:['הזמנה פעילה; Cross/remm אינם קשורים למלון זה.'],q:'Richmond Hotel Premier Kyoto Shijo'};if(n.includes('royal classic'))return{d:'המלון הסופי שלנו באוסקה 14–16/11, 4-3-3 Namba. לפי האתר הרשמי הוא מחובר ישירות ל-Osaka Metro Namba דרך Exit Walkway 12.',t:'זה המלון הסופי באוסקה; Cross Hotel בוטל.',f:['Nankai Namba כ-4 דקות הליכה; Dotonbori ו-Hozenji נוחים ברגל.'],q:'Hotel Royal Classic Osaka'};if(n.includes('metropolitan tokyo marunouchi'))return{d:'המלון שלנו ללילה האחרון בטוקיו 16–17/11, ב-Sapia Tower. לפי האתר הרשמי הוא מחובר ישירות ל-Tokyo Station Nihombashi Exit.',t:'מה-Shinkansen Nihombashi Gate מדובר בכדקה הליכה — יתרון גדול עם מזוודות.',f:['כתובת: 1-7-12 Marunouchi, Chiyoda-ku.','הזמנה QXU287073 · שולם ₪676.61.'],q:'Hotel Metropolitan Tokyo Marunouchi'};return null}
function updateHotels(){
 $$('#page-hotels .hotel-card').forEach(c=>{const n=($('b',c)?.textContent||'').replace(/—.*$/,'').trim(),d=hotelData(n);if(!d)return;ensureGuideButton(c,n)});
}
function openAudit(name){const k=key(name),d=D[k]||hotelData(name);if(!d)return;const m=$('#placeModal');if(!m)return;const title=$('#modalTitle',m),desc=$('#modalDesc',m),tip=$('#modalTip',m),map=$('#modalMap',m);if(title)title.textContent=k;if(desc)desc.textContent=d.d;if(tip){tip.textContent='💡 '+d.t;tip.style.display=''}if(map){map.href=G(d.q||k);map.textContent='📍 Google Maps'}let x=$('.audit-extra',m);if(!x){x=document.createElement('div');x.className='audit-extra';x.style.cssText='margin-top:12px;padding:12px;border:1px solid #e8e2d8;border-radius:14px;background:#fffdf8;font-size:12px;line-height:1.65';$('#modalTip',m)?.after(x)}x.innerHTML='<b>מידע שימושי</b><ul style="margin:7px 18px 0 0;padding:0"></ul>';const ul=$('ul',x);(d.f||[]).forEach(v=>{const li=document.createElement('li');li.textContent=v;ul.appendChild(li)});if(!(d.f||[]).length)x.remove();
 // Remove repeated expanded text if an older guide block duplicated the main description.
 const base=norm(d.d);$$('li,p',m).forEach(n=>{if(n===desc||desc?.contains(n))return;const t=norm(n.textContent);if(t.length>40&&(t===base||base.includes(t)||t.includes(base)))n.remove()});
}
function migrateExpenseDefaults(){
 try{if(typeof EXP_DEFAULTS!=='undefined'&&Array.isArray(EXP_DEFAULTS)){for(let i=EXP_DEFAULTS.length-1;i>=0;i--)if(/Cross Hotel Osaka|מלון טוקיו · לילה אחרון|^מלון טוקיו$/i.test(EXP_DEFAULTS[i].name||''))EXP_DEFAULTS.splice(i,1);if(!EXP_DEFAULTS.some(x=>/JR Kyushu Hotel Blossom/i.test(x.name||'')))EXP_DEFAULTS.push({name:'JR Kyushu Hotel Blossom Shinjuku',status:'מוזמן',payment:'אשראי',currency:'JPY',amount:311616,category:'🏨 לינה',included:true,note:'4–8/11'});if(!EXP_DEFAULTS.some(x=>/Hotel Metropolitan Tokyo Marunouchi/i.test(x.name||'')))EXP_DEFAULTS.push({name:'Hotel Metropolitan Tokyo Marunouchi',status:'שולם',payment:'אשראי',currency:'ILS',amount:676.61,category:'🏨 לינה',included:true,note:'16–17/11 · QXU287073'});}}
 catch(e){}
 try{const K='japanTrip_expenses_v1',raw=localStorage.getItem(K);if(!raw)return;let a=JSON.parse(raw);if(!Array.isArray(a))return;a=a.filter(x=>!/Cross Hotel Osaka|remm Tokyo Kyobashi|^מלון טוקיו$|מלון טוקיו · לילה אחרון/i.test(x.name||''));const up=(name,obj)=>{let x=a.find(y=>new RegExp(name,'i').test(y.name||''));if(x)Object.assign(x,obj);else a.push({id:Date.now()+a.length,name:obj.name,...obj})};up('JR Kyushu Hotel Blossom',{name:'JR Kyushu Hotel Blossom Shinjuku',status:'מוזמן',payment:'אשראי',currency:'JPY',amount:311616,category:'🏨 לינה',included:true,note:'4–8/11'});up('Richmond Hotel Premier Kyoto',{name:'Richmond Hotel Premier Kyoto Shijo',status:'מוזמן',payment:'אשראי',currency:'JPY',amount:159420,category:'🏨 לינה',included:true,note:'10–14/11'});up('Hotel Royal Classic Osaka',{name:'Hotel Royal Classic Osaka',status:'מוזמן',payment:'אשראי',currency:'JPY',amount:109398,category:'🏨 לינה',included:true,note:'14–16/11 · סופי'});up('Hotel Metropolitan Tokyo Marunouchi',{name:'Hotel Metropolitan Tokyo Marunouchi',status:'שולם',payment:'אשראי',currency:'ILS',amount:676.61,category:'🏨 לינה',included:true,note:'16–17/11 · QXU287073'});localStorage.setItem(K,JSON.stringify(a));if(typeof expRender==='function')setTimeout(expRender,0)}catch(e){}
}
function setVersion(){const v=$('header .logo .app-version')||$('header .logo small');if(v)v.textContent='2026 · '+VERSION;document.title='Japan Trip 2026 · '+VERSION;document.documentElement.dataset.appReady=VERSION}
function run(){migrateExpenseDefaults();updatePlaces();updateRouteButtons();updateHotels();setVersion()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,220),{once:true});else setTimeout(run,220);
setTimeout(run,900);setTimeout(setVersion,1800);
document.addEventListener('click',e=>{const b=e.target.closest('.guide-tips-btn,.info-modal-btn,.place-info-btn');if(!b)return;const name=b.dataset.place||b.closest('.hotel-card,.stop-card,.place-card')?.querySelector('h3,b')?.textContent||'';setTimeout(()=>openAudit(name),140)},true);
})();