// Japan Trip v9.13.1 — consolidated trip data, itinerary/UI normalization and local state
(() => {
'use strict';
const VERSION='v9.13.1';
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const G=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
const norm=s=>(s||'').replace(/^[^\p{L}\p{N}]+/u,'').replace(/[·⭐✓✔️👓]/g,' ').replace(/\s+/g,' ').trim().toLowerCase();

const HOTELS={
 tokyo1:{name:'JR Kyushu Hotel Blossom Shinjuku',dates:'4–8 Nov 2026',address:'2-6-2 Yoyogi, Shibuya-ku',room:'Standard Double Queen · Non-Smoking · 2 Adults · 4 nights',extra:'Breakfast + Wi-Fi',price:'¥311,616 · Pay later',transport:'JR Shinjuku South Exit · כ־3 דקות',map:G('JR Kyushu Hotel Blossom Shinjuku')},
 kyoto:{name:'Richmond Hotel Premier Kyoto Shijo',dates:'10–14 Nov 2026',address:'50 Kasaboko Town, Shimogyo Ward',room:'Moderate Double · Non-Smoking · 2 Adults · 4 nights',extra:'Breakfast + Wi-Fi',price:'¥159,420 · Pay later',transport:'Shijo / Karasuma',map:G('Richmond Hotel Premier Kyoto Shijo')},
 osaka:{name:'Hotel Royal Classic Osaka',dates:'14–16 Nov 2026',address:'4-3-3 Namba, Chuo-ku, Osaka',room:'Standard Queen · Non-Smoking · 2 Adults · 2 nights',extra:'Breakfast + Wi-Fi included',price:'¥109,398 · Pay later',transport:'Osaka Metro Namba · Exit 12 · מחובר ישירות למלון',map:G('Hotel Royal Classic Osaka')},
 tokyo2:{name:'Hotel Metropolitan Tokyo Marunouchi',dates:'16–17 Nov 2026',address:'Sapia Tower · 1-7-12 Marunouchi, Chiyoda-ku, Tokyo',room:'UTSUROI (Renovated) · Queen · 18 m² · Non-Smoking · 2 Adults · 1 night',extra:'Booking QXU287073',price:'שולם ₪676.61',transport:'Tokyo Station · Nihombashi Exit · כ־1 דקה מ-Shinkansen Nihombashi Gate',map:G('Hotel Metropolitan Tokyo Marunouchi')}
};

// Google rating/review counts checked 06/09/2026. Keep these as display snapshots, not live values.
const RESTAURANTS=[
 {name:'66tantan (Rokuroku Tantan)',city:'Kyoto',type:'Tantanmen / Dan Dan noodles',rating:5.0,reviews:468,desc:'Tantanmen קטן ומיוחד בגיון.',schedule:'13/11 · 13:45',place:'66tantan',map:G('66tantan Rokuroku Tantan Kyoto')},
 {name:'Gyukatsu Motomura Shinjuku',city:'Tokyo',type:'Gyukatsu · קאטסו בקר',rating:4.9,reviews:8231,desc:'Gyukatsu בשינג׳וקו — קציצת בקר מטוגנת שמסיימים על אבן חמה.',place:'Gyukatsu Motomura Shinjuku',map:G('Gyukatsu Motomura Shinjuku Main Branch')},
 {name:'AFURI Harajuku',city:'Tokyo',type:'Ramen · Yuzu Shio',rating:4.4,reviews:4980,desc:'ראמן קליל ורענן המזוהה עם Yuzu Shio.',place:'AFURI',map:G('AFURI Harajuku Tokyo')},
 {name:'Katsukura Kyoto Porta',city:'Kyoto',type:'Tonkatsu · קאטסו חזיר',rating:4.4,reviews:1290,desc:'Tonkatsu ליד Kyoto Station.',place:'Katsukura Kyoto Porta',map:G('Katsukura Kyoto Porta')},
 {name:'Mizuno Dotonbori',city:'Osaka',type:'Okonomiyaki',rating:3.8,reviews:3167,desc:'Okonomiyaki בדוטונבורי.',place:'Mizuno Dotonbori',map:G('Mizuno Dotonbori Osaka')},
 {name:'551 HORAI Honten',city:'Osaka',type:'Chinese · Butaman / Shumai',rating:4.2,reviews:4385,desc:'הסניף הראשי של 551 HORAI, מפורסם ב-Butaman וב-Shumai.',place:'551 HORAI',map:G('551 HORAI Honten Osaka')},
 {name:'Namba Ramen Ichiza',city:'Osaka',type:'Ramen food hall',rating:3.9,reviews:1488,desc:'מתחם ראמן בקומה 9 של EDION Namba עם כמה סגנונות ראמן במקום אחד.',schedule:'15/11 · אופציה לארוחה',place:'Namba Ramen Ichiza',map:G('Namba Ramen Ichiza Osaka')}
];

const TAKE_KEY='japanTrip_take_v2', SHOP_KEY='japanTrip_shop_v2';
const TAKE_DEFAULT=['דרכונים','ארנק + כרטיסי אשראי','ביטוח נסיעות','תרופות קבועות','מטענים לטלפונים','Power Bank','מתאם חשמל ליפן','eSIM / פרטי חיבור','משקפי שמש','נעלי הליכה נוחות','מעיל קל / שכבות','מטרייה מתקפלת','תיק יום קטן','צילום/עותק של מסמכי הנסיעה'];
const SHOP_DEFAULT=[
 {name:'משקפיים · JINS',done:false,note:'להזמין בתחילת הטיול כדי להשאיר זמן לאיסוף',maps:G('JINS Shinjuku Tokyo')},
 {name:'נעלי ריצה',done:false,note:'Onitsuka Tiger / חנויות ספורט לפי התאמה',maps:G('Onitsuka Tiger Omotesando Tokyo')},
 {name:'מכונת גילוח',done:false,note:'Bic Camera / Yodobashi Camera',maps:G('Bic Camera Shinjuku Tokyo')},
 {name:'מכנסי ספורט',done:false,note:'Uniqlo / חנויות ספורט',maps:G('Uniqlo Tokyo')}
];
function load(keys,defaults){for(const k of keys){try{const a=JSON.parse(localStorage.getItem(k));if(Array.isArray(a)&&a.length)return a.map((x,i)=>typeof x==='string'?{id:Date.now()+i,name:x,done:false}:x)}catch(e){}}return defaults.map((x,i)=>typeof x==='string'?{id:Date.now()+i,name:x,done:false}:{id:Date.now()+i,...x})}
function save(k,a){try{localStorage.setItem(k,JSON.stringify(a))}catch(e){}}
let take=load([TAKE_KEY,'japanTrip_take_v1','takeList'],TAKE_DEFAULT);
let shop=load([SHOP_KEY,'japanTrip_shop_v1','shoppingList','shopList'],SHOP_DEFAULT);
function move(a,i,dir){const j=i+dir;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]]}
function renderTake(){const root=$('#takeList');if(!root)return;root.innerHTML='';take.forEach((x,i)=>{const r=document.createElement('div');r.className='take-item';r.style.cssText='display:flex;align-items:center;gap:8px;padding:10px 3px;border-bottom:1px solid #eee';r.innerHTML='<input type="checkbox" style="width:20px;height:20px"><span style="flex:1"></span><button type="button" title="למעלה">↑</button><button type="button" title="למטה">↓</button><button type="button" title="מחק">×</button>';const cb=r.querySelector('input'),sp=r.querySelector('span'),bs=r.querySelectorAll('button');cb.checked=!!x.done;sp.textContent=x.name||x.text||'';if(x.done)sp.style.cssText='flex:1;text-decoration:line-through;opacity:.55';cb.onchange=()=>{x.done=cb.checked;save(TAKE_KEY,take);renderTake()};bs[0].onclick=()=>{move(take,i,-1);save(TAKE_KEY,take);renderTake()};bs[1].onclick=()=>{move(take,i,1);save(TAKE_KEY,take);renderTake()};bs[2].onclick=()=>{take.splice(i,1);save(TAKE_KEY,take);renderTake()};root.appendChild(r)});save(TAKE_KEY,take)}
window.addTake=window.addTakeItem=function(){const inp=$('#newTakeItem,#takeNew');if(!inp||!inp.value.trim())return;take.push({id:Date.now(),name:inp.value.trim(),done:false});inp.value='';save(TAKE_KEY,take);renderTake()};
function renderShop(){const root=$('#shoppingList');if(!root)return;root.innerHTML='';shop.forEach((x,i)=>{const r=document.createElement('div');r.className='shopping-item';r.style.cssText='background:#fff;border:1px solid #e5e7eb;border-radius:14px;padding:11px;margin:8px 0';r.innerHTML='<div style="display:flex;gap:8px;align-items:flex-start"><input type="checkbox" style="width:20px;height:20px"><div style="flex:1"><b></b><div class="shop-note" style="font-size:11px;color:#666;margin-top:4px"></div></div><button type="button" title="למעלה">↑</button><button type="button" title="למטה">↓</button><button type="button" title="מחק">×</button></div><div class="shop-map" style="margin-top:8px"></div>';const cb=r.querySelector('input'),b=r.querySelector('b'),note=r.querySelector('.shop-note'),bs=r.querySelectorAll('button'),map=r.querySelector('.shop-map');cb.checked=!!x.done;b.textContent=x.name||x.text||'';note.textContent=x.note||'';if(x.done)b.style.cssText='text-decoration:line-through;opacity:.55';if(x.maps){const a=document.createElement('a');a.className='map-btn';a.href=x.maps;a.target='_blank';a.rel='noopener';a.textContent='📍 חנויות / מפה ↗';map.appendChild(a)}cb.onchange=()=>{x.done=cb.checked;save(SHOP_KEY,shop);renderShop()};bs[0].onclick=()=>{move(shop,i,-1);save(SHOP_KEY,shop);renderShop()};bs[1].onclick=()=>{move(shop,i,1);save(SHOP_KEY,shop);renderShop()};bs[2].onclick=()=>{shop.splice(i,1);save(SHOP_KEY,shop);renderShop()};root.appendChild(r)});save(SHOP_KEY,shop)}
window.addShopItem=function(){const inp=$('#newShopItem');if(!inp||!inp.value.trim())return;shop.push({id:Date.now(),name:inp.value.trim(),done:false,note:'',maps:''});inp.value='';save(SHOP_KEY,shop);renderShop()};

function mkStop(time,icon,title,text,place,tag){const d=document.createElement('div');d.className='stop';d.innerHTML='<div class="time">'+time+'</div><div class="rail"><i>'+icon+'</i></div><div class="stop-card"><h3>'+title+'</h3><p>'+text+'</p>'+(tag?'<span class="trip-tag">'+tag+'</span>':'')+(place?'<div class="stop-actions"><button class="info-modal-btn guide-tips-btn" data-place="'+place+'" type="button">ℹ️ מדריך וטיפים</button></div>':'')+'</div>';return d}
function rebuildDay12(){const day=$('#day-9'),list=$('.list-view',day);if(!day||!list||day.dataset.v913Day12==='1')return;day.dataset.v913Day12='1';const hotel=$$('.stop',list).find(s=>/Richmond Hotel Premier Kyoto Shijo/i.test(s.textContent||''));$$(':scope > .stop',list).forEach(s=>s.remove());const h=$('.day-heading h2',day);if(h)h.textContent='Fushimi Inari · Tofuku-ji · Sanjūsangen-dō · teamLab';const sum=$('.summary',day);if(sum)sum.textContent='Fushimi Inari → Tofuku-ji → Sanjūsangen-dō → Kyoto Station → teamLab Biovortex Kyoto';[
 ['09:00','⛩️','Fushimi Inari Taisha','בוקר בין אלפי שערי ה־torii. אין צורך לעלות לפסגה; נחווה את השערים והיער ונרד.','Fushimi Inari',''],
 ['11:30','🍁','Tofuku-ji','מקדש זן סמוך ל-Fushimi Inari, חזק במיוחד בעונת השלכת.','Tofuku-ji',''],
 ['14:00','🏯','Sanjūsangen-dō','אולם עץ ארוך ובו 1,001 פסלי Kannon.','Sanjusangen-do',''],
 ['16:00','🚉','Kyoto Station + Higashi Hongan-ji','סיום רגוע באזור התחנה ובמידת הזמן Higashi Hongan-ji.','Kyoto Station',''],
 ['ערב','✨','teamLab Biovortex Kyoto','אחת מחוויות החובה של הטיול בקיוטו. להזמין כרטיסים מראש.','teamLab Biovortex Kyoto','⭐ חובה · להזמין מראש']
 ].forEach(x=>list.appendChild(mkStop(...x)));if(hotel)list.appendChild(hotel)}
function normalizeDay14(){const day=$('#day-11'),list=$('.list-view',day);if(!day||!list)return;$$('.stop',list).forEach(s=>{if(/Hozenji|Dotonbori · ערב ראשון|ארוחת ערב · Namba/i.test(s.textContent||''))s.remove()});const hotel=$$('.stop',list).find(s=>/Hotel Royal Classic Osaka|Cross Hotel Osaka/i.test(s.textContent||''));let after=hotel||list.lastElementChild;[
 ['19:00','🏮','Hozenji Temple + Hozenji Yokocho','אחרי הצ׳ק-אין: סמטת אבן קטנה עם פנסים ומקדש Hozenji.','Hozenji Yokocho',''],
 ['19:45','🌃','Dotonbori · ערב ראשון באוסקה','טיול לאורך התעלה, שלטי הניאון ו-Glico Man.','Dotonbori',''],
 ['20:30','🍽️','ארוחת ערב · Namba / Dotonbori','לבחור לפי החשק — אוקונומיאקי, טפניאקי או אוכל יפני אחר.','Namba','']
 ].forEach(x=>{if($$('.stop',list).some(s=>norm($('h3',s)?.textContent)===norm(x[2])))return;const s=mkStop(...x);if(after&&after.parentNode===list){after.after(s);after=s}else list.appendChild(s)});
 const note=day.querySelector('.transit-day-note');if(note)note.innerHTML='<b>🧳 תוכנית מזוודות:</b> בבוקר נבדוק עם Richmond Hotel Premier Kyoto Shijo אפשרות לשליחת המזוודות ל-<b>Hotel Royal Classic Osaka</b>. רק לאחר אישור השירות בפועל נמסור אותן; אחרת ניקח אותן איתנו/נשתמש בפתרון חלופי. ב-Nara נשתמש בלוקר רק לציוד שאיתנו.';
 $$(' .stop-card',day).forEach(c=>{if(/AONIYOSHI · Kyoto → Kintetsu-Nara/i.test($('h3',c)?.textContent||'')){const p=$('p',c);if(p)p.textContent='רכבת התיירות AONIYOSHI. בשבת: Kyoto 10:55 → Kintetsu-Nara 11:31 לפי לוח Kintetsu המעודכן למרץ 2026; נוודא שוב סמוך לפתיחת המכירה.'}})}
function add66Tantan(){document.querySelectorAll('[data-garon-v912u]').forEach(e=>e.closest('.stop')?.remove()||e.remove());const day=$('#day-10'),list=$('.list-view',day);if(!day||!list||list.querySelector('[data-tantan66-v913]'))return;const s=mkStop('13:45','🍜','66tantan (Rokuroku Tantan)','Tantanmen קטן ומיוחד בגיון · 286-6 Gionmachi Kitagawa · כ־450 מ׳ מ-Gion-Shijo.','66tantan','');s.dataset.tantan66V913='1';const stops=$$(':scope > .stop',list);let inserted=false;for(const x of stops){const t=($('.time',x)?.textContent||'').match(/(\d{1,2}):(\d{2})/);if(t&&(+t[1]>13||(+t[1]===13&&+t[2]>45))){x.before(s);inserted=true;break}}if(!inserted)list.appendChild(s)}
function dedupeDayStops(){$$('.day .list-view').forEach(list=>{const seen=new Set();$$(':scope > .stop',list).forEach(s=>{const h=norm($('h3',s)?.textContent),t=norm($('.time',s)?.textContent);if(!h)return;const k=t+'|'+h;if(seen.has(k))s.remove();else seen.add(k)})})}

function hotelCard(h,status){return `<div class="hotel-note">✅ <b>${h.name} — ${status}</b></div><div class="hotel-card booked"><b>${h.name}</b><p>📍 ${h.address}</p><p>🛏️ ${h.room}</p><p>🍳 ${h.extra}</p><p>💴 ${h.price}</p><p>🚉 ${h.transport}</p><div class="hotel-map-actions"><a class="map-btn" href="${h.map}" target="_blank" rel="noopener">📍 פתח מפה ↗</a></div></div>`}
function rebuildHotels(){const p=$('#page-hotels');if(!p)return;p.dataset.v913Hotels='1';p.innerHTML=`<div class="page-head"><button onclick="closePage()">←</button><h2>🏨 מלונות</h2></div><div class="hotel-city"><h3>🗼 Tokyo · ${HOTELS.tokyo1.dates}</h3>${hotelCard(HOTELS.tokyo1,'הוזמן')}</div><div class="hotel-city"><h3>♨️ Hakone / Fuji · 8–10 Nov 2026</h3><div class="hotel-note">⏳ <b>המלון עדיין לא נסגר</b></div></div><div class="hotel-city"><h3>⛩️ Kyoto · ${HOTELS.kyoto.dates}</h3>${hotelCard(HOTELS.kyoto,'הוזמן')}</div><div class="hotel-city"><h3>🏯 Osaka · ${HOTELS.osaka.dates}</h3>${hotelCard(HOTELS.osaka,'הוזמן · סופי')}</div><div class="hotel-city"><h3>🗼 Tokyo · ${HOTELS.tokyo2.dates}</h3>${hotelCard(HOTELS.tokyo2,'הוזמן ושולם')}</div>`}
function removeStaleHotelAlternatives(){
 const patterns=/שתי הזמנות פעילות|שתי הזמנות|2 הזמנות פעילות|two active bookings/i;
 $$('p,div,span,small,li').forEach(el=>{const text=(el.textContent||'').trim();if(patterns.test(text)&&/Hotel Royal Classic Osaka|Cross Hotel Osaka/i.test(text)){if(el.children.length===0||text.length<260)el.remove()}});
}
function normalizeHotels(){const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{let s=n.nodeValue||'';s=s.replace(/Cross Hotel Osaka(?:（ORIX HOTELS & RESORTS）)?/gi,'Hotel Royal Classic Osaka').replace(/remm Tokyo Kyobashi/gi,'Hotel Metropolitan Tokyo Marunouchi');n.nodeValue=s});removeStaleHotelAlternatives();$$('.day .stop-card').forEach(c=>{const t=c.textContent||'';if(/Hotel Royal Classic Osaka/i.test(t)){const h=$('h3',c);if(h)h.textContent='Hotel Royal Classic Osaka'}if(/Hotel Metropolitan Tokyo Marunouchi/i.test(t)){const h=$('h3',c);if(h)h.textContent='Hotel Metropolitan Tokyo Marunouchi'}});const hotelDefs=[[/JR Kyushu Hotel Blossom Shinjuku/i,'JR Kyushu Hotel Blossom Shinjuku'],[/Richmond Hotel Premier Kyoto Shijo/i,'Richmond Hotel Premier Kyoto Shijo'],[/Hotel Royal Classic Osaka/i,'Hotel Royal Classic Osaka'],[/Hotel Metropolitan Tokyo Marunouchi/i,'Hotel Metropolitan Tokyo Marunouchi']];$$('.day .stop-card').forEach(c=>{const hit=hotelDefs.find(([re])=>re.test(c.textContent||''));if(!hit)return;c.querySelectorAll('a.map-btn,a[href*="google.com/maps"],a[href*="maps.google"]').forEach(a=>a.remove());let a=$('.stop-actions',c);if(!a){a=document.createElement('div');a.className='stop-actions';c.appendChild(a)}let b=$('.guide-tips-btn,.info-modal-btn,.place-info-btn',a);$$('.guide-tips-btn,.info-modal-btn,.place-info-btn',a).slice(1).forEach(x=>x.remove());if(!b){b=document.createElement('button');b.type='button';a.appendChild(b)}b.className='info-modal-btn guide-tips-btn';b.dataset.place=hit[1];b.textContent='ℹ️ מדריך וטיפים'})}
function migrateExpenses(){try{const k='japanTrip_expenses_v1';const raw=localStorage.getItem(k);if(!raw)return;let a=JSON.parse(raw);if(!Array.isArray(a))return;a=a.filter(x=>!/Cross Hotel Osaka|remm Tokyo Kyobashi|^מלון טוקיו$|מלון טוקיו · לילה אחרון/i.test(x.name||''));const up=(re,obj)=>{let x=a.find(y=>re.test(y.name||''));if(x)Object.assign(x,obj);else a.push({id:Date.now()+a.length,...obj})};up(/JR Kyushu Hotel Blossom/i,{name:'JR Kyushu Hotel Blossom Shinjuku',status:'מוזמן',payment:'אשראי',currency:'JPY',amount:311616,category:'🏨 לינה',included:true,note:'4–8/11'});up(/Richmond Hotel Premier Kyoto/i,{name:'Richmond Hotel Premier Kyoto Shijo',status:'מוזמן',payment:'אשראי',currency:'JPY',amount:159420,category:'🏨 לינה',included:true,note:'10–14/11'});up(/Hotel Royal Classic Osaka/i,{name:'Hotel Royal Classic Osaka',status:'מוזמן',payment:'אשראי',currency:'JPY',amount:109398,category:'🏨 לינה',included:true,note:'14–16/11 · סופי'});up(/Hotel Metropolitan Tokyo Marunouchi/i,{name:'Hotel Metropolitan Tokyo Marunouchi',status:'שולם',payment:'אשראי',currency:'ILS',amount:676.61,category:'🏨 לינה',included:true,note:'16–17/11 · QXU287073'});localStorage.setItem(k,JSON.stringify(a));if(typeof expRender==='function')setTimeout(expRender,0)}catch(e){}}

function setFlights(){const page=$('#page-flights');if(!page)return;const head=$('.page-head',page);page.querySelectorAll('.flight-card,.connection-card,.ticket-summary-v912p,.ticket-summary-v913').forEach(x=>x.remove());const wrap=document.createElement('div');wrap.className='ticket-summary-v913';wrap.innerHTML=`<div style="margin:8px 0 12px;padding:11px 12px;border:1px solid #e5e7eb;border-radius:14px;background:#fff"><b>Emirates · Booking IG4JDF · Economy Flex</b><div style="font-size:12px;margin-top:5px">Azriel + Ayala · כבודה לבטן המטוס: 30 ק״ג לכל נוסע בכל מקטע · תיק יד Economy: עד 7 ק״ג</div></div><div class="flight-card"><b>03/11 · TLV → DXB</b><strong>13:50 → 18:55</strong><span>EK2269 / FZ1636 · Flydubai · TLV T3 → DXB T3</span></div><div class="connection-card">⏱️ קונקשן בדובאי: 3:50</div><div class="flight-card"><b>03–04/11 · DXB → NRT</b><strong>22:45 → 13:10 (+1)</strong><span>EK320 · Emirates · DXB T3 → Narita T2 · מושבים: Azriel 48K · Ayala 48J</span></div><div class="flight-card"><b>17–18/11 · NRT → DXB</b><strong>21:30 → 04:40 (+1)</strong><span>EK321 · Emirates · Narita T2 → DXB T3 · מושבים: Azriel 32K · Ayala 32J</span></div><div class="connection-card">⏱️ קונקשן בדובאי: 1:35</div><div class="flight-card"><b>18/11 · DXB → TLV</b><strong>06:15 → 08:05</strong><span>EK2120 / FZ1073 · Flydubai · DXB T3 → TLV T3</span></div>`;if(head)head.insertAdjacentElement('afterend',wrap);else page.prepend(wrap);const d0=$('#day-0');$$('.stop-card',d0||document).forEach(c=>{if(/Dubai → Tokyo Narita/i.test($('h3',c)?.textContent||'')){const p=$('p',c);if(p)p.textContent='EK320 · Economy Flex · מושבים: Azriel 48K · Ayala 48J · DXB Terminal 3 → Narita Terminal 2.'}})}

// Places contains only real visitable destinations or named restaurants/shops — never itinerary actions.
const nonPlaceRe=/^(?:check[ -]?in|check[ -]?out|צ[׳']?ק\s*אין|צ[׳']?ק\s*אאוט|בוקר חופשי|בוקר רגוע|ערב חופשי|יום חופשי|זמן חופשי|זמן להשלמות|קניות\s*[\/.+–-]?\s*השלמות|השלמות|קניות\s*\/\s*השלמות|ארוחת בוקר|ארוחת צהריים|ארוחת ערב|מנוחה|התארגנות|איסוף מזוודות|שמירת מזוודות|שליחת מזוודות|קבלת מזוודות|החזרת רכב|החזרת.*רכב|לקיחת רכב|קבלת רכב|איסוף רכב|השכרת רכב|המשך לפי מקום לינה|המשך לפי|המשך בהתאם|לפי מקום הלינה|נסיעה|מעבר|יום מעבר|חזרה למלון|יציאה מהמלון|יציאה ל|טיסה|קונקשן|נחיתה|המראה|רכבת|שינקנסן|אוטובוס|מונית|לינה)(?:\b|\s|$)/i;
const hotelRe=/\bhotel\b|מלון|JR Kyushu|Richmond|Royal Classic|Metropolitan|Cross Hotel|remm Tokyo/i;
const restaurantRe=/66tantan|Rokuroku Tantan|Gyukatsu Motomura|Uobei|AFURI|Katsukura|Musashi Sushi|Mizuno|551\s*HORAI|Namba Ramen Ichiza/i;
function placeTitle(c){return ($('h3',c)?.textContent||'').trim()}
function restaurantForTitle(raw){return RESTAURANTS.find(r=>{const a=norm(raw),b=norm(r.name),p=norm(r.place);return a===b||a.includes(b)||b.includes(a)||a===p||a.includes(p)||p.includes(a)})}
function restaurantMetaHtml(r){return `<div class="restaurant-quick-meta" style="font-size:12px;color:#555;margin:4px 0 6px;line-height:1.45"><b>${r.type}</b><br>⭐ ${r.rating.toFixed(1)} Google · ${new Intl.NumberFormat('he-IL').format(r.reviews)} דירוגים</div>`}
function decorateRestaurantCard(c,r){if(!c||!r)return;c.dataset.cat='🍽️ מסעדות';c.dataset.type='restaurant';const h=$('h3',c);if(h&&norm(h.textContent)!==norm(r.name))h.textContent=r.name;let meta=$('.restaurant-quick-meta',c);if(meta)meta.outerHTML=restaurantMetaHtml(r);else{const titleWrap=$('.place-title',c)||h;if(titleWrap)titleWrap.insertAdjacentHTML('afterend',restaurantMetaHtml(r))}}
function cleanPlaces(){const grid=$('#placesGrid');if(!grid)return;const seen=new Set();$$('.place-card',grid).forEach(c=>{const raw=placeTitle(c),n=norm(raw);if(!n||hotelRe.test(raw)||nonPlaceRe.test(raw)){c.remove();return}const r=restaurantForTitle(raw);const key=r?'restaurant:'+norm(r.name):n;if(seen.has(key)){c.remove();return}seen.add(key);if(r)decorateRestaurantCard(c,r);c.querySelectorAll('.planned-badge-v912x,.restaurant-badge-v912x').forEach(x=>x.remove())});ensureRestaurants(grid);ensureRestaurantFilter(grid);fixAliases()}
function ensureRestaurants(grid){const present=()=>new Set($$('.place-card',grid).map(c=>norm(placeTitle(c))));RESTAURANTS.forEach(r=>{const names=present(),n=norm(r.name);let card=$$('.place-card',grid).find(c=>restaurantForTitle(placeTitle(c))===r);if(card){decorateRestaurantCard(card,r);return}if([...names].some(x=>x===n))return;const c=document.createElement('article');c.className='place-card';c.dataset.city=r.city;c.dataset.cat='🍽️ מסעדות';c.dataset.type='restaurant';c.innerHTML=`<div class="place-title"><span>🍽️</span><h3>${r.name}</h3></div>${restaurantMetaHtml(r)}<div class="place-location">📍 ${r.city}</div>${r.schedule?`<div class="scheduled-badge">${r.schedule}</div>`:''}<p>${r.desc}</p><div class="place-actions"><button type="button" class="guide-tips-btn info-modal-btn" data-place="${r.place}">ℹ️ מדריך וטיפים</button></div>`;grid.appendChild(c)})}
function ensureRestaurantFilter(grid){let bar=$('#placesRestaurantFilter');if(!bar){bar=document.createElement('div');bar.id='placesRestaurantFilter';bar.style.cssText='display:flex;gap:8px;margin:8px 0 12px;overflow:auto';const all=document.createElement('button'),rest=document.createElement('button');[all,rest].forEach(b=>{b.type='button';b.style.cssText='border:1px solid #ddd;background:#fff;border-radius:999px;padding:7px 11px;font-weight:700;white-space:nowrap'});all.textContent='כל המקומות';rest.textContent='🍽️ מסעדות';all.onclick=()=>$$('.place-card',grid).forEach(c=>c.style.display='');rest.onclick=()=>$$('.place-card',grid).forEach(c=>c.style.display=(c.dataset.cat==='🍽️ מסעדות'||c.dataset.type==='restaurant')?'':'none');bar.append(all,rest);grid.before(bar)}}
function fixAliases(){const aliases=[[/^Meiji Jingu$/i,'Meiji Shrine'],[/^Tokyo Station & Marunouchi$/i,'Tokyo Station / Marunouchi'],[/^(Fuji \/ Kawaguchiko|Kawaguchiko \/ Fuji)$/i,'Kawaguchiko'],[/^Fushimi Inari Taisha$/i,'Fushimi Inari'],[/^Sanjūsangen-dō$/i,'Sanjusangen-do'],[/^Kinkaku-ji · מקדש הזהב$/i,'Kinkaku-ji']];$$('.place-card,.stop-card').forEach(c=>{const h=$('h3',c);if(!h)return;const hit=aliases.find(([re])=>re.test(h.textContent.trim()));if(hit)c.querySelectorAll('.guide-tips-btn,.info-modal-btn,.place-info-btn').forEach(b=>b.dataset.place=hit[1])})}
function fixDay2Order(){const d=$('#day-2');if(!d)return;const s=$$('.stop',d).find(x=>/^Nakamise$/i.test($('h3',x)?.textContent||''));const t=$('.time',s);if(t&&t.textContent.trim()==='08:45')t.textContent='09:15'}

function openConsolidatedGuide(name){const m=$('#placeModal');if(!m)return;const key=String(name||'').replace(/^🍽️\s*/,'').trim();const r=RESTAURANTS.find(x=>norm(x.name)===norm(key)||norm(x.place)===norm(key));const hd=Object.values(HOTELS).find(x=>norm(x.name)===norm(key));if(!r&&!hd)return;const title=$('#modalTitle',m),desc=$('#modalDesc',m),map=$('#modalMap',m);if(title)title.textContent=r?r.name:hd.name;if(desc)desc.textContent=r?(r.type+' · Google '+r.rating.toFixed(1)+' ('+new Intl.NumberFormat('he-IL').format(r.reviews)+' דירוגים) · '+r.desc):(hd.name+' · '+hd.dates+' · '+hd.transport);if(map){map.href=r?r.map:hd.map;map.textContent='📍 Google Maps'}}

function setTitleAndVersion(){const h=$('#day-0 .day-heading h2');if(h)h.textContent='עזרי ואיילי יוצאים לדרך ✈️';const v=$('header .logo .app-version')||$('header .logo small');if(v)v.textContent='2026 · '+VERSION;document.title='Japan Trip 2026 · '+VERSION;document.documentElement.dataset.appReady=VERSION}
function run(){setTitleAndVersion();renderTake();renderShop();rebuildDay12();normalizeDay14();add66Tantan();dedupeDayStops();rebuildHotels();normalizeHotels();migrateExpenses();setFlights();fixDay2Order();cleanPlaces()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,250),{once:true});else setTimeout(run,250);
setTimeout(run,1100);
document.addEventListener('click',e=>{const b=e.target.closest('.guide-tips-btn,.info-modal-btn,.place-info-btn');if(!b)return;setTimeout(()=>openConsolidatedGuide(b.dataset.place||''),120)},true);
window.JapanTripData={version:VERSION,restaurants:RESTAURANTS,hotels:HOTELS,refresh:run};
})();