// Japan Trip v9.12t - reservation document Picker: choose Japan folder once, then list view only
(function(){'use strict';
const VERSION='v9.12t';
const DOCS_KEY='japanTrip_docs_v1';
const FOLDER_KEY='japanTrip_docsFolder_v1';
const API_KEY='AIzaSyAwA1aYbnhZENDGbx77MoW-JhR5bW9kvVM';
const MIME_TYPES='application/pdf,image/png,image/jpeg,image/webp';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const ITEMS=[
 {key:'hotel-jr-kyushu-shinjuku',label:'JR Kyushu Hotel Blossom Shinjuku',re:/JR Kyushu Hotel Blossom Shinjuku/i,type:'hotel'},
 {key:'hotel-richmond-kyoto-shijo',label:'Richmond Hotel Premier Kyoto Shijo',re:/Richmond Hotel Premier Kyoto Shijo/i,type:'hotel'},
 {key:'hotel-royal-classic-osaka',label:'Hotel Royal Classic Osaka',re:/Hotel Royal Classic Osaka/i,type:'hotel'},
 {key:'hotel-metropolitan-marunouchi',label:'Hotel Metropolitan Tokyo Marunouchi',re:/Hotel Metropolitan Tokyo Marunouchi/i,type:'hotel'},
 {key:'teamlab-biovortex-kyoto',label:'teamLab Biovortex Kyoto',re:/teamLab Biovortex Kyoto/i,type:'activity'},
 {key:'aoniyoshi-kyoto-nara',label:'AONIYOSHI Kyoto → Nara',re:/AONIYOSHI/i,type:'activity'}
];
function parse(key,fallback){try{const v=JSON.parse(localStorage.getItem(key)||'');return v??fallback}catch(e){return fallback}}
function docs(){const d=parse(DOCS_KEY,{});return d&&typeof d==='object'&&!Array.isArray(d)?d:{}}
function folder(){const f=parse(FOLDER_KEY,null);return f&&f.id?f:null}
function saveFolder(f){localStorage.setItem(FOLDER_KEY,JSON.stringify(f));window.JapanDrive?.schedulePush?.()}
function saveDocs(d){localStorage.setItem(DOCS_KEY,JSON.stringify(d));window.JapanDrive?.schedulePush?.();renderAll()}
function loadPickerApi(){return new Promise((resolve,reject)=>{if(window.google?.picker)return resolve();let s=document.querySelector('script[data-japan-picker-api]');if(!s){s=document.createElement('script');s.src='https://apis.google.com/js/api.js';s.async=true;s.defer=true;s.dataset.japanPickerApi='1';document.head.appendChild(s)}const started=Date.now();const t=setInterval(()=>{if(window.gapi?.load){clearInterval(t);gapi.load('picker',{callback:resolve,onerror:()=>reject(new Error('Google Picker לא נטען'))})}else if(Date.now()-started>12000){clearInterval(t);reject(new Error('Google API לא נטען'))}},150)})}
async function token(){let t=window.JapanDrive?.getAccessToken?.()||'';if(!t){if(!window.JapanDrive?.ensureInteractive)throw new Error('Drive sync לא זמין');t=await window.JapanDrive.ensureInteractive()}return t}
async function chooseJapanFolder(){await loadPickerApi();const t=await token();return new Promise((resolve,reject)=>{const view=new google.picker.DocsView(google.picker.ViewId.FOLDERS);view.setIncludeFolders(true);view.setSelectFolderEnabled(true);view.setMode(google.picker.DocsViewMode.LIST);const picker=new google.picker.PickerBuilder().addView(view).setOAuthToken(t).setDeveloperKey(API_KEY).setOrigin(location.protocol+'//'+location.host).setTitle('בחר פעם אחת את תיקיית Japan').setCallback(data=>{if(data.action===google.picker.Action.CANCEL){reject(new Error('CANCELLED'));return}if(data.action!==google.picker.Action.PICKED)return;const f=data.docs?.[0];if(!f?.id){reject(new Error('לא נבחרה תיקייה'));return}const chosen={id:f.id,name:f.name||'Japan',linkedAt:new Date().toISOString()};saveFolder(chosen);resolve(chosen)}).build();picker.setVisible(true)})}
async function ensureFolder(){return folder()||await chooseJapanFolder()}
async function choose(key,label){try{const fldr=await ensureFolder();await loadPickerApi();const t=await token();const view=new google.picker.DocsView(google.picker.ViewId.DOCS);view.setParent(fldr.id);view.setIncludeFolders(false);view.setSelectFolderEnabled(false);view.setMimeTypes(MIME_TYPES);view.setMode(google.picker.DocsViewMode.LIST);const picker=new google.picker.PickerBuilder().addView(view).enableFeature(google.picker.Feature.NAV_HIDDEN).setOAuthToken(t).setDeveloperKey(API_KEY).setOrigin(location.protocol+'//'+location.host).setTitle('בחר אסמכתא מתוך '+(fldr.name||'Japan')+' עבור '+label).setCallback(data=>{if(data.action!==google.picker.Action.PICKED)return;const f=data.docs?.[0];if(!f)return;const d=docs();d[key]={id:f.id,name:f.name||label,mimeType:f.mimeType||'',url:f.url||('https://drive.google.com/file/d/'+encodeURIComponent(f.id)+'/view'),linkedAt:new Date().toISOString()};saveDocs(d)}).build();picker.setVisible(true)}catch(e){if(String(e.message)==='CANCELLED')return;console.warn('Document picker:',e);alert('לא ניתן לפתוח את Google Drive כרגע. לחץ קודם על "חבר / סנכרן" ונסה שוב.') }}
function openDoc(key){const f=docs()[key];if(!f)return;window.open(f.url||('https://drive.google.com/file/d/'+encodeURIComponent(f.id)+'/view'),'_blank','noopener')}
function unlink(key,label){if(!confirm('לנתק את האסמכתא מ-'+label+'? הקובץ עצמו לא יימחק מ-Google Drive.'))return;const d=docs();delete d[key];saveDocs(d)}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function actionHtml(key,label){const f=docs()[key];if(f)return '<div class="reservation-doc-actions" data-doc-key="'+key+'" style="display:flex;gap:7px;flex-wrap:wrap;margin-top:8px"><button type="button" class="reservation-doc-open">📄 הצג אסמכתא</button><button type="button" class="reservation-doc-replace">↻ החלף</button><button type="button" class="reservation-doc-unlink" title="נתק אסמכתא">✕</button><span style="font-size:11px;opacity:.72;align-self:center;max-width:210px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+escapeHtml(f.name||'')+'</span></div>';return '<div class="reservation-doc-actions" data-doc-key="'+key+'" style="margin-top:8px"><button type="button" class="reservation-doc-link">📎 חבר אסמכתא</button></div>'}
function wire(root,item){const a=$('.reservation-doc-actions',root);if(!a)return;a.querySelector('.reservation-doc-link')?.addEventListener('click',()=>choose(item.key,item.label));a.querySelector('.reservation-doc-open')?.addEventListener('click',()=>openDoc(item.key));a.querySelector('.reservation-doc-replace')?.addEventListener('click',()=>choose(item.key,item.label));a.querySelector('.reservation-doc-unlink')?.addEventListener('click',()=>unlink(item.key,item.label))}
function renderInto(root,item){if(!root)return;root.querySelectorAll('.reservation-doc-actions').forEach(x=>x.remove());root.insertAdjacentHTML('beforeend',actionHtml(item.key,item.label));wire(root,item)}
function renderKnownCards(){ITEMS.forEach(item=>{const selectors=item.type==='hotel'?['#page-hotels .hotel-card','.day .stop-card']:['.day .stop-card','#page-places .place-card','.place-card'];selectors.forEach(sel=>{$$(sel).forEach(card=>{if(item.re.test(card.textContent||''))renderInto(card,item)})})})}
function renderFlights(){const wrap=$('#page-flights .ticket-summary-v912p');if(!wrap)return;let box=$('.flight-docs-v912s',wrap);if(!box){box=document.createElement('div');box.className='flight-docs-v912s';box.style.cssText='margin:8px 0 12px;padding:11px 12px;border:1px solid #e5e7eb;border-radius:14px;background:#fff';wrap.insertBefore(box,wrap.children[1]||null)}const passengerItems=[{key:'flight-emirates-IG4JDF-azriel',label:'Emirates e-ticket · Azriel'},{key:'flight-emirates-IG4JDF-ayala',label:'Emirates e-ticket · Ayala'}];box.innerHTML='<b>📄 אסמכתאות לטיסות · Booking IG4JDF</b>';passengerItems.forEach(item=>{const row=document.createElement('div');row.style.cssText='margin-top:8px;padding-top:6px;border-top:1px solid #eef2f7';row.innerHTML='<div style="font-size:12px;font-weight:600">'+escapeHtml(item.label)+'</div>'+actionHtml(item.key,item.label);box.appendChild(row);wire(row,item)})}
function renderAll(){renderKnownCards();renderFlights();setVersion()}
function setVersion(){const v=$('header .logo .app-version')||$('header .logo small');if(v)v.textContent='2026 · '+VERSION;document.title='Japan Trip 2026 · '+VERSION;document.documentElement.dataset.appReady=VERSION}
function run(){renderAll()}
window.JapanDocs={resetFolder(){localStorage.removeItem(FOLDER_KEY);alert('בחירת תיקיית Japan אופסה. בפעם הבאה שתבחר אסמכתא תתבקש לבחור אותה מחדש.')},getFolder:folder};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,950),{once:true});else setTimeout(run,950);setTimeout(run,1900);window.addEventListener('japanTripDriveSynced',()=>setTimeout(renderAll,50));setTimeout(setVersion,2600);
})();