// Japan Trip v9.13.0 — consolidated Google Drive sync + reservation document picker
(() => {
'use strict';
const TAKE_KEY='japanTrip_take_v2', SHOP_KEY='japanTrip_shop_v2', DOCS_KEY='japanTrip_docs_v1';
const CLIENT_KEY='japanTrip_googleClientId_v1', DEFAULT_CLIENT_ID='390490824-v3k40tus28ujfcc9n2e5o138flbgfddc.apps.googleusercontent.com';
const META_KEY='japanTrip_driveSyncMeta_v1', TOKEN_KEY='japanTrip_driveAccessToken_v1', TOKEN_EXP_KEY='japanTrip_driveAccessTokenExp_v1';
const FILE_NAME='JapanTripSync.json', SCOPE='https://www.googleapis.com/auth/drive.file';
const FOLDER_KEY='japanTrip_docsFolder_v1';
const API_KEY='AIzaSyAwA1aYbnhZENDGbx77MoW-JhR5bW9kvVM';
const MIME_TYPES='application/pdf,image/png,image/jpeg,image/webp';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
let tokenClient=null, accessToken='', driveFileId='', applyingRemote=false, pushTimer=null;
const nowIso=()=>new Date().toISOString();
function parse(key,fallback){try{const v=JSON.parse(localStorage.getItem(key)||'');return v??fallback}catch(e){return fallback}}
function getMeta(){return parse(META_KEY,{})}
function setMeta(patch){const m={...getMeta(),...patch};localStorage.setItem(META_KEY,JSON.stringify(m));return m}
function getClientId(){return localStorage.getItem(CLIENT_KEY)||DEFAULT_CLIENT_ID}
function loadSessionToken(){try{const exp=Number(sessionStorage.getItem(TOKEN_EXP_KEY)||0),t=sessionStorage.getItem(TOKEN_KEY)||'';if(t&&exp>Date.now()+30000){accessToken=t;return true}}catch(e){}return false}
function saveSessionToken(resp){accessToken=resp.access_token||'';const expires=Math.max(60,Number(resp.expires_in||3600));try{sessionStorage.setItem(TOKEN_KEY,accessToken);sessionStorage.setItem(TOKEN_EXP_KEY,String(Date.now()+expires*1000))}catch(e){}}
function clearSessionToken(){accessToken='';try{sessionStorage.removeItem(TOKEN_KEY);sessionStorage.removeItem(TOKEN_EXP_KEY)}catch(e){}}
function state(){const take=parse(TAKE_KEY,[]),shop=parse(SHOP_KEY,[]),docs=parse(DOCS_KEY,{});return {schema:2,updatedAt:nowIso(),take:Array.isArray(take)?take:[],shop:Array.isArray(shop)?shop:[],docs:docs&&typeof docs==='object'&&!Array.isArray(docs)?docs:{}}}
function status(text,ok){$$('.drive-sync-status').forEach(el=>{el.textContent=text;el.style.color=ok?'#176b3a':'#666'})}
function injectGIS(){return new Promise((resolve,reject)=>{if(window.google?.accounts?.oauth2)return resolve();let s=document.querySelector('script[data-japan-gis]');if(!s){s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.defer=true;s.dataset.japanGis='1';document.head.appendChild(s)}const started=Date.now(),t=setInterval(()=>{if(window.google?.accounts?.oauth2){clearInterval(t);resolve()}else if(Date.now()-started>12000){clearInterval(t);reject(new Error('Google Identity Services לא נטען'))}},150)})}
async function requestTokenInteractive(){const clientId=getClientId();if(!clientId)throw new Error('חסר Google OAuth Client ID');await injectGIS();if(!tokenClient)tokenClient=google.accounts.oauth2.initTokenClient({client_id:clientId,scope:SCOPE,callback:()=>{}});return new Promise((resolve,reject)=>{tokenClient.callback=resp=>{if(resp.error)return reject(new Error(resp.error));saveSessionToken(resp);resolve(accessToken)};tokenClient.requestAccessToken({prompt:'consent'})})}
async function api(url,opt={}){if(!accessToken&&!loadSessionToken())throw new Error('AUTH_REQUIRED');const r=await fetch(url,{...opt,headers:{Authorization:'Bearer '+accessToken,...(opt.headers||{})}});if(r.status===401){clearSessionToken();throw new Error('AUTH_REQUIRED')}if(!r.ok)throw new Error('Drive API '+r.status);return r}
async function findFile(){const q=encodeURIComponent("name='"+FILE_NAME+"' and trashed=false");const r=await api('https://www.googleapis.com/drive/v3/files?q='+q+'&fields=files(id,name,modifiedTime)&spaces=drive&pageSize=10'),j=await r.json();if(j.files?.length){driveFileId=j.files[0].id;setMeta({fileId:driveFileId});return j.files[0]}return null}
async function createFile(payload){const boundary='japantrip_'+Date.now(),meta={name:FILE_NAME,mimeType:'application/json'},body='--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n'+JSON.stringify(meta)+'\r\n--'+boundary+'\r\nContent-Type: application/json\r\n\r\n'+JSON.stringify(payload)+'\r\n--'+boundary+'--';const r=await api('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,modifiedTime',{method:'POST',headers:{'Content-Type':'multipart/related; boundary='+boundary},body}),j=await r.json();driveFileId=j.id;setMeta({fileId:driveFileId,lastCloudSyncAt:payload.updatedAt,lastLocalChangeAt:payload.updatedAt});return j}
async function readCloud(){if(!driveFileId)driveFileId=getMeta().fileId||'';if(!driveFileId){const f=await findFile();if(!f)return null}const r=await api('https://www.googleapis.com/drive/v3/files/'+encodeURIComponent(driveFileId)+'?alt=media');return await r.json()}
async function writeCloud(payload){if(!driveFileId){const f=await findFile();if(!f)return createFile(payload)}await api('https://www.googleapis.com/upload/drive/v3/files/'+encodeURIComponent(driveFileId)+'?uploadType=media',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});setMeta({fileId:driveFileId,lastCloudSyncAt:payload.updatedAt,lastLocalChangeAt:payload.updatedAt});status('✓ מסונכרן ל-Google Drive',true)}
function applyCloud(c){if(!c||!Array.isArray(c.take)||!Array.isArray(c.shop))return;applyingRemote=true;localStorage.setItem(TAKE_KEY,JSON.stringify(c.take));localStorage.setItem(SHOP_KEY,JSON.stringify(c.shop));if(c.docs&&typeof c.docs==='object'&&!Array.isArray(c.docs))localStorage.setItem(DOCS_KEY,JSON.stringify(c.docs));applyingRemote=false;setMeta({lastCloudSyncAt:c.updatedAt||nowIso(),lastLocalChangeAt:c.updatedAt||nowIso()});window.dispatchEvent(new CustomEvent('japanTripDriveSynced',{detail:{docs:c.docs||{}}}));window.JapanTripData?.refresh?.()}
async function doSync(interactive){try{status('מסנכרן…');if(!accessToken&&!loadSessionToken()){if(!interactive){status('☁️ לא מחובר כרגע · לחץ חבר / סנכרן');return}await requestTokenInteractive()}const cloud=await readCloud();if(!cloud){const s=state();await createFile(s);status('✓ נוצר קובץ Sync ב-Google Drive',true);return}const meta=getMeta(),cloudAt=Date.parse(cloud.updatedAt||0)||0,localAt=Date.parse(meta.lastLocalChangeAt||0)||0,syncedAt=Date.parse(meta.lastCloudSyncAt||0)||0;if(cloudAt>Math.max(localAt,syncedAt)){applyCloud(cloud);status('✓ נטען מ-Google Drive',true);return}if(localAt>syncedAt){await writeCloud(state());return}setMeta({lastCloudSyncAt:cloud.updatedAt||nowIso(),fileId:driveFileId});status('✓ מסונכרן ל-Google Drive',true)}catch(e){console.warn('Drive sync:',e);if(String(e.message)==='AUTH_REQUIRED'){clearSessionToken();status('☁️ החיבור פג · לחץ חבר / סנכרן')}else status('Drive לא מחובר / נדרש אישור Google')}}
const syncNow=()=>doSync(true),syncQuiet=()=>doSync(false);
function schedulePush(){if(applyingRemote)return;setMeta({lastLocalChangeAt:nowIso()});clearTimeout(pushTimer);pushTimer=setTimeout(()=>{if(accessToken||loadSessionToken())syncQuiet();else status('נשמר בטלפון · יסונכרן בפעם הבאה שתתחבר')},900)}
function addUi(){['#takeList','#shoppingList'].forEach(sel=>{const root=$(sel);if(!root||root.parentElement.querySelector('.drive-sync-card'))return;const parent=root.parentElement,card=document.createElement('div');card.className='drive-sync-card';card.style.cssText='background:#f8fafc;border:1px solid #d9e2ec;border-radius:14px;padding:11px 12px;margin:8px 0 12px;font-size:12px';card.innerHTML='<div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap"><b style="flex:1">☁️ Google Drive Sync</b><button type="button" class="drive-sync-connect">חבר / סנכרן</button><button type="button" class="drive-sync-settings">הגדרה</button></div><div class="drive-sync-status" style="margin-top:6px;color:#666">'+((accessToken||loadSessionToken())?'מחובר לסשן Google':'לא ייפתח חלון Google ברענון')+'</div>';parent.insertBefore(card,root);$('.drive-sync-connect',card).onclick=syncNow;$('.drive-sync-settings',card).onclick=()=>{const id=prompt('Google OAuth Client ID:',getClientId());if(id===null)return;if(id.trim())localStorage.setItem(CLIENT_KEY,id.trim());else localStorage.removeItem(CLIENT_KEY);clearSessionToken();tokenClient=null;status('הגדרת Google נשמרה. לחץ חבר / סנכרן.')};if(!parent.dataset.driveSyncWatch){parent.dataset.driveSyncWatch='1';parent.addEventListener('change',e=>{if(!e.target.closest('.drive-sync-card'))schedulePush()},true);parent.addEventListener('click',e=>{if(!e.target.closest('.drive-sync-card')&&(e.target.closest('button')||e.target.closest('input')))setTimeout(schedulePush,0)},true)}})}

const ITEMS=[
 {key:'hotel-jr-kyushu-shinjuku',label:'JR Kyushu Hotel Blossom Shinjuku',re:/JR Kyushu Hotel Blossom Shinjuku/i,type:'hotel'},
 {key:'hotel-richmond-kyoto-shijo',label:'Richmond Hotel Premier Kyoto Shijo',re:/Richmond Hotel Premier Kyoto Shijo/i,type:'hotel'},
 {key:'hotel-royal-classic-osaka',label:'Hotel Royal Classic Osaka',re:/Hotel Royal Classic Osaka/i,type:'hotel'},
 {key:'hotel-metropolitan-marunouchi',label:'Hotel Metropolitan Tokyo Marunouchi',re:/Hotel Metropolitan Tokyo Marunouchi/i,type:'hotel'},
 {key:'teamlab-biovortex-kyoto',label:'teamLab Biovortex Kyoto',re:/teamLab Biovortex Kyoto/i,type:'activity'},
 {key:'aoniyoshi-kyoto-nara',label:'AONIYOSHI Kyoto → Nara',re:/AONIYOSHI/i,type:'activity'}
];
function docs(){const d=parse(DOCS_KEY,{});return d&&typeof d==='object'&&!Array.isArray(d)?d:{}}
function folder(){const f=parse(FOLDER_KEY,null);return f&&f.id?f:null}
function saveFolder(f){localStorage.setItem(FOLDER_KEY,JSON.stringify(f))}
function saveDocs(d){localStorage.setItem(DOCS_KEY,JSON.stringify(d));schedulePush();renderAllDocs()}
function loadPickerApi(){return new Promise((resolve,reject)=>{if(window.google?.picker)return resolve();let s=document.querySelector('script[data-japan-picker-api]');if(!s){s=document.createElement('script');s.src='https://apis.google.com/js/api.js';s.async=true;s.defer=true;s.dataset.japanPickerApi='1';document.head.appendChild(s)}const started=Date.now(),t=setInterval(()=>{if(window.gapi?.load){clearInterval(t);gapi.load('picker',{callback:resolve,onerror:()=>reject(new Error('Google Picker לא נטען'))})}else if(Date.now()-started>12000){clearInterval(t);reject(new Error('Google API לא נטען'))}},150)})}
async function pickerToken(){let t=accessToken||(loadSessionToken()?accessToken:'');if(!t)t=await requestTokenInteractive();return t}
async function chooseJapanFolder(){await loadPickerApi();const t=await pickerToken();return new Promise((resolve,reject)=>{const view=new google.picker.DocsView(google.picker.ViewId.FOLDERS);view.setIncludeFolders(true);view.setSelectFolderEnabled(true);view.setMode(google.picker.DocsViewMode.LIST);new google.picker.PickerBuilder().addView(view).setOAuthToken(t).setDeveloperKey(API_KEY).setOrigin(location.protocol+'//'+location.host).setTitle('בחר פעם אחת את תיקיית Japan').setCallback(data=>{if(data.action===google.picker.Action.CANCEL)return reject(new Error('CANCELLED'));if(data.action!==google.picker.Action.PICKED)return;const f=data.docs?.[0];if(!f?.id)return reject(new Error('לא נבחרה תיקייה'));const chosen={id:f.id,name:f.name||'Japan',linkedAt:nowIso()};saveFolder(chosen);resolve(chosen)}).build().setVisible(true)})}
async function ensureFolder(){return folder()||await chooseJapanFolder()}
async function chooseDoc(key,label){try{const fldr=await ensureFolder();await loadPickerApi();const t=await pickerToken(),view=new google.picker.DocsView(google.picker.ViewId.DOCS);view.setParent(fldr.id);view.setIncludeFolders(false);view.setSelectFolderEnabled(false);view.setMimeTypes(MIME_TYPES);view.setMode(google.picker.DocsViewMode.LIST);new google.picker.PickerBuilder().addView(view).enableFeature(google.picker.Feature.NAV_HIDDEN).setOAuthToken(t).setDeveloperKey(API_KEY).setOrigin(location.protocol+'//'+location.host).setTitle('בחר אסמכתא מתוך '+(fldr.name||'Japan')+' עבור '+label).setCallback(data=>{if(data.action!==google.picker.Action.PICKED)return;const f=data.docs?.[0];if(!f)return;const d=docs();d[key]={id:f.id,name:f.name||label,mimeType:f.mimeType||'',url:f.url||('https://drive.google.com/file/d/'+encodeURIComponent(f.id)+'/view'),linkedAt:nowIso()};saveDocs(d)}).build().setVisible(true)}catch(e){if(String(e.message)==='CANCELLED')return;console.warn('Document picker:',e);alert('לא ניתן לפתוח את Google Drive כרגע. לחץ קודם על "חבר / סנכרן" ונסה שוב.')}}
function openDoc(key){const f=docs()[key];if(f)window.open(f.url||('https://drive.google.com/file/d/'+encodeURIComponent(f.id)+'/view'),'_blank','noopener')}
function unlink(key,label){if(!confirm('לנתק את האסמכתא מ-'+label+'? הקובץ עצמו לא יימחק מ-Google Drive.'))return;const d=docs();delete d[key];saveDocs(d)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function actionHtml(key,label){const f=docs()[key];if(f)return '<div class="reservation-doc-actions" data-doc-key="'+key+'" style="display:flex;gap:7px;flex-wrap:wrap;margin-top:8px"><button type="button" class="reservation-doc-open">📄 הצג אסמכתא</button><button type="button" class="reservation-doc-replace">↻ החלף</button><button type="button" class="reservation-doc-unlink">✕</button><span style="font-size:11px;opacity:.72;align-self:center;max-width:210px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+esc(f.name||'')+'</span></div>';return '<div class="reservation-doc-actions" data-doc-key="'+key+'" style="margin-top:8px"><button type="button" class="reservation-doc-link">📎 חבר אסמכתא</button></div>'}
function wire(root,item){const a=$('.reservation-doc-actions',root);if(!a)return;$('.reservation-doc-link',a)?.addEventListener('click',()=>chooseDoc(item.key,item.label));$('.reservation-doc-open',a)?.addEventListener('click',()=>openDoc(item.key));$('.reservation-doc-replace',a)?.addEventListener('click',()=>chooseDoc(item.key,item.label));$('.reservation-doc-unlink',a)?.addEventListener('click',()=>unlink(item.key,item.label))}
function renderInto(root,item){if(!root)return;root.querySelectorAll('.reservation-doc-actions').forEach(x=>x.remove());root.insertAdjacentHTML('beforeend',actionHtml(item.key,item.label));wire(root,item)}
function renderKnownCards(){ITEMS.forEach(item=>{const selectors=item.type==='hotel'?['#page-hotels .hotel-card','.day .stop-card']:['.day .stop-card','#page-places .place-card','.place-card'];selectors.forEach(sel=>$$(sel).forEach(card=>{if(item.re.test(card.textContent||''))renderInto(card,item)}))})}
function renderFlights(){const wrap=$('#page-flights .ticket-summary-v913,#page-flights .ticket-summary-v912p');if(!wrap)return;let box=$('.flight-docs-v913',wrap);if(!box){box=document.createElement('div');box.className='flight-docs-v913';box.style.cssText='margin:8px 0 12px;padding:11px 12px;border:1px solid #e5e7eb;border-radius:14px;background:#fff';wrap.insertBefore(box,wrap.children[1]||null)}const items=[{key:'flight-emirates-IG4JDF-azriel',label:'Emirates e-ticket · Azriel'},{key:'flight-emirates-IG4JDF-ayala',label:'Emirates e-ticket · Ayala'}];box.innerHTML='<b>📄 אסמכתאות לטיסות · Booking IG4JDF</b>';items.forEach(item=>{const row=document.createElement('div');row.style.cssText='margin-top:8px;padding-top:6px;border-top:1px solid #eef2f7';row.innerHTML='<div style="font-size:12px;font-weight:600">'+esc(item.label)+'</div>'+actionHtml(item.key,item.label);box.appendChild(row);wire(row,item)})}
function renderAllDocs(){renderKnownCards();renderFlights()}
function run(){loadSessionToken();driveFileId=getMeta().fileId||'';addUi();renderAllDocs();if(accessToken)setTimeout(syncQuiet,900)}
window.JapanDrive={getAccessToken(){return accessToken||(loadSessionToken()?accessToken:'')},ensureInteractive:requestTokenInteractive,schedulePush,syncNow,syncQuiet};
window.JapanDocs={resetFolder(){localStorage.removeItem(FOLDER_KEY);alert('בחירת תיקיית Japan אופסה. בפעם הבאה שתבחר אסמכתא תתבקש לבחור אותה מחדש.')},getFolder:folder};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,850),{once:true});else setTimeout(run,850);
window.addEventListener('japanTripDriveSynced',()=>setTimeout(renderAllDocs,50));
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&(accessToken||loadSessionToken()))syncQuiet()});
window.addEventListener('focus',()=>{if(accessToken||loadSessionToken())syncQuiet()});
})();