// Japan Trip v9.12s - Drive sync with reservation document references
(function(){'use strict';
const VERSION='v9.12s';
const TAKE_KEY='japanTrip_take_v2';
const SHOP_KEY='japanTrip_shop_v2';
const DOCS_KEY='japanTrip_docs_v1';
const CLIENT_KEY='japanTrip_googleClientId_v1';
const DEFAULT_CLIENT_ID='390490824-v3k40tus28ujfcc9n2e5o138flbgfddc.apps.googleusercontent.com';
const META_KEY='japanTrip_driveSyncMeta_v1';
const TOKEN_KEY='japanTrip_driveAccessToken_v1';
const TOKEN_EXP_KEY='japanTrip_driveAccessTokenExp_v1';
const FILE_NAME='JapanTripSync.json';
const SCOPE='https://www.googleapis.com/auth/drive.file';
let tokenClient=null, accessToken='', driveFileId='', applyingRemote=false, pushTimer=null;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const nowIso=()=>new Date().toISOString();
function parse(key,fallback){try{const v=JSON.parse(localStorage.getItem(key)||'');return v??fallback}catch(e){return fallback}}
function getMeta(){return parse(META_KEY,{})}
function setMeta(patch){const m={...getMeta(),...patch};localStorage.setItem(META_KEY,JSON.stringify(m));return m}
function getClientId(){return localStorage.getItem(CLIENT_KEY)||DEFAULT_CLIENT_ID}
function loadSessionToken(){try{const exp=Number(sessionStorage.getItem(TOKEN_EXP_KEY)||0);const t=sessionStorage.getItem(TOKEN_KEY)||'';if(t&&exp>Date.now()+30000){accessToken=t;return true}}catch(e){}return false}
function saveSessionToken(resp){accessToken=resp.access_token||'';const expires=Math.max(60,Number(resp.expires_in||3600));try{sessionStorage.setItem(TOKEN_KEY,accessToken);sessionStorage.setItem(TOKEN_EXP_KEY,String(Date.now()+expires*1000))}catch(e){}}
function clearSessionToken(){accessToken='';try{sessionStorage.removeItem(TOKEN_KEY);sessionStorage.removeItem(TOKEN_EXP_KEY)}catch(e){}}
function state(){const take=parse(TAKE_KEY,[]),shop=parse(SHOP_KEY,[]),docs=parse(DOCS_KEY,{});return {schema:2,updatedAt:nowIso(),take:Array.isArray(take)?take:[],shop:Array.isArray(shop)?shop:[],docs:docs&&typeof docs==='object'&&!Array.isArray(docs)?docs:{}}}
function status(text,ok){$$('.drive-sync-status').forEach(el=>{el.textContent=text;el.style.color=ok?'#176b3a':'#666'})}
function injectGIS(){return new Promise((resolve,reject)=>{if(window.google?.accounts?.oauth2)return resolve();let s=document.querySelector('script[data-japan-gis]');if(!s){s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.defer=true;s.dataset.japanGis='1';document.head.appendChild(s)}const started=Date.now();const t=setInterval(()=>{if(window.google?.accounts?.oauth2){clearInterval(t);resolve()}else if(Date.now()-started>12000){clearInterval(t);reject(new Error('Google Identity Services לא נטען'))}},150)})}
async function requestTokenInteractive(){const clientId=getClientId();if(!clientId)throw new Error('חסר Google OAuth Client ID');await injectGIS();if(!tokenClient)tokenClient=google.accounts.oauth2.initTokenClient({client_id:clientId,scope:SCOPE,callback:()=>{}});return new Promise((resolve,reject)=>{tokenClient.callback=(resp)=>{if(resp.error)return reject(new Error(resp.error));saveSessionToken(resp);resolve(accessToken)};tokenClient.requestAccessToken({prompt:'consent'})})}
async function api(url,opt={}){if(!accessToken&&!loadSessionToken())throw new Error('AUTH_REQUIRED');const r=await fetch(url,{...opt,headers:{Authorization:'Bearer '+accessToken,...(opt.headers||{})}});if(r.status===401){clearSessionToken();throw new Error('AUTH_REQUIRED')}if(!r.ok)throw new Error('Drive API '+r.status);return r}
async function findFile(){const q=encodeURIComponent("name='"+FILE_NAME+"' and trashed=false");const r=await api('https://www.googleapis.com/drive/v3/files?q='+q+'&fields=files(id,name,modifiedTime)&spaces=drive&pageSize=10');const j=await r.json();if(j.files?.length){driveFileId=j.files[0].id;setMeta({fileId:driveFileId});return j.files[0]}return null}
async function createFile(payload){const boundary='japantrip_'+Date.now();const meta={name:FILE_NAME,mimeType:'application/json'};const body='--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n'+JSON.stringify(meta)+'\r\n--'+boundary+'\r\nContent-Type: application/json\r\n\r\n'+JSON.stringify(payload)+'\r\n--'+boundary+'--';const r=await api('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,modifiedTime',{method:'POST',headers:{'Content-Type':'multipart/related; boundary='+boundary},body});const j=await r.json();driveFileId=j.id;setMeta({fileId:driveFileId,lastCloudSyncAt:payload.updatedAt,lastLocalChangeAt:payload.updatedAt});return j}
async function readCloud(){if(!driveFileId){driveFileId=getMeta().fileId||''}if(!driveFileId){const f=await findFile();if(!f)return null}const r=await api('https://www.googleapis.com/drive/v3/files/'+encodeURIComponent(driveFileId)+'?alt=media');return await r.json()}
async function writeCloud(payload){if(!driveFileId){const f=await findFile();if(!f)return createFile(payload)}await api('https://www.googleapis.com/upload/drive/v3/files/'+encodeURIComponent(driveFileId)+'?uploadType=media',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});setMeta({fileId:driveFileId,lastCloudSyncAt:payload.updatedAt,lastLocalChangeAt:payload.updatedAt});status('✓ מסונכרן ל-Google Drive',true)}
function applyCloud(c){if(!c||!Array.isArray(c.take)||!Array.isArray(c.shop))return;applyingRemote=true;localStorage.setItem(TAKE_KEY,JSON.stringify(c.take));localStorage.setItem(SHOP_KEY,JSON.stringify(c.shop));if(c.docs&&typeof c.docs==='object'&&!Array.isArray(c.docs))localStorage.setItem(DOCS_KEY,JSON.stringify(c.docs));applyingRemote=false;setMeta({lastCloudSyncAt:c.updatedAt||nowIso(),lastLocalChangeAt:c.updatedAt||nowIso()});window.dispatchEvent(new CustomEvent('japanTripDriveSynced',{detail:{docs:c.docs||{}}}))}
async function doSync(interactive){try{status('מסנכרן…');if(!accessToken&&!loadSessionToken()){if(!interactive){status('☁️ לא מחובר כרגע · לחץ חבר / סנכרן');return}await requestTokenInteractive()}const cloud=await readCloud();if(!cloud){const s=state();await createFile(s);status('✓ נוצר קובץ Sync ב-Google Drive',true);return}const meta=getMeta();const cloudAt=Date.parse(cloud.updatedAt||0)||0;const localAt=Date.parse(meta.lastLocalChangeAt||0)||0;const syncedAt=Date.parse(meta.lastCloudSyncAt||0)||0;if(cloudAt>Math.max(localAt,syncedAt)){applyCloud(cloud);return}if(localAt>syncedAt){await writeCloud(state());return}setMeta({lastCloudSyncAt:cloud.updatedAt||nowIso(),fileId:driveFileId});status('✓ מסונכרן ל-Google Drive',true)}catch(e){console.warn('Drive sync:',e);if(String(e.message)==='AUTH_REQUIRED'){clearSessionToken();status('☁️ החיבור פג · לחץ חבר / סנכרן')}else status('Drive לא מחובר / נדרש אישור Google')}}
const syncNow=()=>doSync(true), syncQuiet=()=>doSync(false);
function schedulePush(){if(applyingRemote)return;setMeta({lastLocalChangeAt:nowIso()});clearTimeout(pushTimer);pushTimer=setTimeout(()=>{if(accessToken||loadSessionToken())syncQuiet();else status('נשמר בטלפון · יסונכרן בפעם הבאה שתתחבר')},900)}
function addUi(){const targets=['#takeList','#shoppingList'];targets.forEach(sel=>{const root=$(sel);if(!root||root.parentElement.querySelector('.drive-sync-card'))return;const parent=root.parentElement;const card=document.createElement('div');card.className='drive-sync-card';card.style.cssText='background:#f8fafc;border:1px solid #d9e2ec;border-radius:14px;padding:11px 12px;margin:8px 0 12px;font-size:12px';card.innerHTML='<div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap"><b style="flex:1">☁️ Google Drive Sync</b><button type="button" class="drive-sync-connect">חבר / סנכרן</button><button type="button" class="drive-sync-settings">הגדרה</button></div><div class="drive-sync-status" style="margin-top:6px;color:#666">'+((accessToken||loadSessionToken())?'מחובר לסשן Google':'לא ייפתח חלון Google ברענון')+'</div>';parent.insertBefore(card,root);card.querySelector('.drive-sync-connect').onclick=syncNow;card.querySelector('.drive-sync-settings').onclick=()=>{const cur=getClientId();const id=prompt('Google OAuth Client ID:',cur);if(id===null)return;if(id.trim()){localStorage.setItem(CLIENT_KEY,id.trim());clearSessionToken();tokenClient=null;status('Client ID נשמר. לחץ חבר / סנכרן.')}else{localStorage.removeItem(CLIENT_KEY);clearSessionToken();tokenClient=null;status('חזרה ל-Client ID המובנה.')}};if(!parent.dataset.driveSyncWatch){parent.dataset.driveSyncWatch='1';parent.addEventListener('change',e=>{if(!e.target.closest('.drive-sync-card'))schedulePush()},true);parent.addEventListener('click',e=>{if(!e.target.closest('.drive-sync-card')&&(e.target.closest('button')||e.target.closest('input')))setTimeout(schedulePush,0)},true)}})}
function setVersion(){const v=$('header .logo .app-version')||$('header .logo small');if(v)v.textContent='2026 · '+VERSION;document.title='Japan Trip 2026 · '+VERSION;document.documentElement.dataset.appReady=VERSION}
function run(){loadSessionToken();addUi();setVersion();driveFileId=getMeta().fileId||'';if(accessToken)setTimeout(syncQuiet,900)}
window.JapanDrive={getAccessToken(){return accessToken||(loadSessionToken()?accessToken:'')},ensureInteractive:requestTokenInteractive,schedulePush,syncNow,syncQuiet};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,700),{once:true});else setTimeout(run,700);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&(accessToken||loadSessionToken()))syncQuiet()});window.addEventListener('focus',()=>{if(accessToken||loadSessionToken())syncQuiet()});setTimeout(setVersion,2400);
})();