// Japan Trip v9.15.7 — keep optional evening walks visible after itinerary rerenders
(()=>{'use strict';
const ASSIGN=[['day-2','asakusa','Asakusa Lights'],['day-3','ueno','Ueno → Akihabara'],['day-4','shibuya','Shibuya After Dark'],['day-7','gion','Gion · Yasaka · Shirakawa'],['day-8','pontocho','Pontocho · Kiyamachi · Kawaramachi'],['day-10','gion','Gion · Yasaka · Shirakawa'],['day-12','umeda','Umeda Night Lights'],['day-13','marunouchi','Marunouchi → Ginza']];
function ensure(){ASSIGN.forEach(([id,key,title])=>{const day=document.getElementById(id);const list=day?.querySelector('.list-view');if(!list)return;const existing=[...list.querySelectorAll('.evening-walk-stop')];if(existing.length>1)existing.slice(1).forEach(x=>x.remove());if(existing.length)return;const s=document.createElement('div');s.className='stop evening-walk-stop';s.innerHTML=`<div class="time">19:30</div><div class="rail"><i>🌙</i></div><div class="stop-card" style="border:1px solid #d9d9e8;background:linear-gradient(180deg,#fff,#f8f8ff)"><h3>🌙 המלצה לטיול ערב · ${title}</h3><p>אופציונלי בלבד — התוכנית המקורית של היום נשארת. יציאה מהמלון ב־19:30.</p><div class="stop-actions"><button type="button" class="evening-walk-btn" data-walk="${key}">פתח המלצת ערב</button></div></div>`;list.appendChild(s)})}
function fixKyotoText(){const m=document.getElementById('eveningWalkModal');if(!m)return;['#ewOut','#ewBack'].forEach(sel=>{const el=m.querySelector(sel);if(el)el.textContent=(el.textContent||'').replace(/Richmond Kyoto Shijo/g,'Daiwa Roynet Hotel Kyoto Shijo Karasuma')})}
function run(){ensure();[700,1500,2800,4500].forEach(ms=>setTimeout(ensure,ms))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
document.addEventListener('click',e=>{if(e.target.closest('.evening-walk-btn'))setTimeout(fixKyotoText,0);const b=e.target.closest('button');if(b&&/מסלול/.test(b.textContent||''))setTimeout(ensure,120)},true);
window.addEventListener('japanTripDriveSynced',()=>setTimeout(ensure,150));
})();