// Japan Trip — optional evening-walk recommendations. Additive only: never replaces the day's original plan.
(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const ROUTES={
 asakusa:{title:'Asakusa Lights',duration:'כ־3–3.5 שעות כולל נסיעות וארוחת ערב',out:'🚆 יציאה 19:30 מהמלון · Shinjuku → Kanda ב-JR Chuo Line, החלפה ל-Tokyo Metro Ginza Line → Asakusa. כ־30–35 דק׳.',back:'🚆 חזרה · Asakusa → Kanda ב-Ginza Line, החלפה ל-JR Chuo Line → Shinjuku. כ־30–35 דק׳.',stops:[['Sensō-ji','המקדש והאזור המואר בלילה.'],['Nakamise & side streets','סמטאות אסקוסה באווירת ערב רגועה.'],['Sumida River Promenade','הליכה לאורך הנהר והגשרים.'],['Skytree view','סיום מול ה-Skytree המואר.']],dinner:'🍽️ ארוחת ערב: באזור Asakusa, לפני הנהר או בסיום.',map:'https://www.google.com/maps/dir/?api=1&origin=Senso-ji+Tokyo&destination=Sumida+Park+Tokyo&waypoints=Nakamise+Shopping+Street+Tokyo&travelmode=walking',image:'./images/evening-walks/asakusa.jpg'},
 ueno:{title:'Ueno → Akihabara',duration:'כ־3–3.5 שעות כולל נסיעות וארוחת ערב',out:'🚆 יציאה 19:30 מהמלון · Shinjuku → Ueno ב-JR Yamanote Line. כ־25 דק׳.',back:'🚆 חזרה · Akihabara → Shinjuku ב-JR Chuo-Sobu Line. כ־20 דק׳.',stops:[['Ueno Park','מתחילים בפארק Ueno כשהאזור כבר מואר.'],['Ameyoko Market','ממשיכים דרך השוק, האוכל והרחובות התוססים.'],['Okachimachi','הליכה דרומה ברחובות המקומיים.'],['Akihabara Electric Town','מסיימים בניאון, אלקטרוניקה ואנימה.']],dinner:'🍽️ ארוחת ערב: Ameyoko או Akihabara, לפי הקצב.',map:'https://www.google.com/maps/dir/?api=1&origin=Ueno+Park+Tokyo&destination=Akihabara+Electric+Town&waypoints=Ameyoko+Shopping+District+Tokyo%7COkachimachi+Station&travelmode=walking',image:'./images/evening-walks/ueno-akihabara.jpg'},
 shibuya:{title:'Shibuya After Dark',duration:'כ־3 שעות כולל נסיעות וארוחת ערב',out:'🚆 יציאה 19:30 מהמלון · Shinjuku → Shibuya ב-JR Yamanote Line. כ־7 דק׳.',back:'🚆 חזרה · Shibuya → Shinjuku ב-JR Yamanote Line. כ־7 דק׳.',stops:[['Hachikō + Shibuya Crossing','פתיחה בכיכר ובמעבר החצייה כשהמסכים מוארים.'],['Center-gai','רחובות צפופים, אוכל ואנרגיה עירונית.'],['Nonbei Yokocho','סמטת ברים קטנה ליד פסי הרכבת.'],['Miyashita Park','סיום באזור המודרני של Miyashita Park.']],dinner:'🍽️ ארוחת ערב: Shibuya, באמצע המסלול או בסיום.',map:'https://www.google.com/maps/dir/?api=1&origin=Hachiko+Memorial+Statue&destination=Miyashita+Park&waypoints=Shibuya+Center-gai%7CNonbei+Yokocho&travelmode=walking',image:'./images/evening-walks/shibuya.jpg'},
 marunouchi:{title:'Marunouchi → Ginza',duration:'כ־2.5–3 שעות כולל ארוחת ערב',out:'🚶 יציאה 19:30 מהמלון · המלון מחובר ל-Tokyo Station; כ־10–15 דק׳ הליכה לצד Marunouchi של התחנה. אין צורך ברכבת.',back:'🚶 חזרה · Ginza → Hotel Metropolitan Tokyo Marunouchi כ־15–20 דק׳ הליכה; אם עייפים, Tokyo Metro Marunouchi Line מ-Ginza ל-Tokyo היא תחנה אחת.',stops:[['Tokyo Station · Marunouchi','החזית המוארת של התחנה.'],['Marunouchi Lights','הליכה ברחובות האלגנטיים והמוארים.'],['Imperial Palace Outer Gardens','קטע רגוע ליד הארמון והחפיר.'],['Ginza','סיום ברחובות המוארים וארוחת ערב.']],dinner:'🍽️ ארוחת ערב: Ginza.',map:'https://www.google.com/maps/dir/?api=1&origin=Tokyo+Station+Marunouchi&destination=Ginza+Tokyo&waypoints=Marunouchi+Naka-dori%7CImperial+Palace+Outer+Gardens+Tokyo&travelmode=walking',image:'./images/evening-walks/marunouchi-ginza.jpg'},
 gion:{title:'Gion · Yasaka · Shirakawa',duration:'כ־2.5–3 שעות כולל ארוחת ערב',out:'🚶 יציאה 19:30 מהמלון · Richmond Kyoto Shijo → Gion/Yasaka כ־20–25 דק׳ הליכה. אם לא רוצים ללכת: אוטובוס/מונית קצרה עד Shijo-Kawaramachi/Gion.',back:'🚶 חזרה · Gion-Shijo / Shijo-Kawaramachi → המלון כ־20–25 דק׳ הליכה; אפשר גם מונית קצרה.',stops:[['Yasaka Shrine','פתיחה באזור המקדש והפנסים.'],['Hanamikoji','רחוב גיון המסורתי.'],['Gion Shirakawa','תעלה, גשרים ובתי machiya.'],['Shijo-Kawaramachi','סיום באזור מרכזי עם אוכל ותחבורה.']],dinner:'🍽️ ארוחת ערב: Gion או Shijo-Kawaramachi.',map:'https://www.google.com/maps/dir/?api=1&origin=Yasaka+Shrine+Kyoto&destination=Shijo+Kawaramachi+Kyoto&waypoints=Hanamikoji+Street%7CGion+Shirakawa&travelmode=walking'},
 pontocho:{title:'Pontocho · Kiyamachi · Kawaramachi',duration:'כ־2.5–3 שעות כולל ארוחת ערב',out:'🚶 יציאה 19:30 מהמלון · כ־20 דק׳ הליכה מ-Richmond Kyoto Shijo ל-Shijo-Kawaramachi/Pontocho; אין צורך ברכבת.',back:'🚶 חזרה · Kawaramachi → המלון כ־20 דק׳ הליכה לאורך Shijo-dori.',stops:[['Shijo Bridge','פתיחה על נהר Kamo.'],['Pontocho Alley','הסמטה הצרה והמפורסמת של קיוטו.'],['Kiyamachi','הליכה לאורך התעלה והרחובות הסמוכים.'],['Shijo-Kawaramachi','סיום באזור הקניות והאוכל.']],dinner:'🍽️ ארוחת ערב: Pontocho/Kawaramachi.',map:'https://www.google.com/maps/dir/?api=1&origin=Shijo+Bridge+Kyoto&destination=Shijo+Kawaramachi+Kyoto&waypoints=Pontocho+Alley%7CKiyamachi+Street&travelmode=walking'},
 umeda:{title:'Umeda Night Lights',duration:'כ־3 שעות כולל נסיעות וארוחת ערב',out:'🚆 יציאה 19:30 מהמלון · Namba → Umeda ב-Osaka Metro Midosuji Line. כ־9 דק׳, ללא החלפה.',back:'🚆 חזרה · Umeda → Namba ב-Midosuji Line. כ־9 דק׳, ללא החלפה.',stops:[['Osaka Station','מתחילים במתחם התחנה המודרני.'],['Grand Front Osaka','אזור עירוני מואר ונעים להליכה.'],['Umeda Sky Building','מגיעים לאזור הבניין והרחבה.'],['Umeda','חזרה לכיוון התחנה והמסעדות.']],dinner:'🍽️ ארוחת ערב: Umeda / Grand Front.',map:'https://www.google.com/maps/dir/?api=1&origin=Osaka+Station&destination=Umeda+Osaka&waypoints=Grand+Front+Osaka%7CUmeda+Sky+Building&travelmode=walking'}
};
// Recommendations only. Days with a major fixed evening plan (e.g. teamLab) are deliberately excluded.
const ASSIGN=[['day-2','asakusa'],['day-3','ueno'],['day-4','shibuya'],['day-7','gion'],['day-8','pontocho'],['day-10','gion'],['day-12','umeda'],['day-13','marunouchi']];
function modal(){let m=$('#eveningWalkModal');if(m)return m;m=document.createElement('div');m.id='eveningWalkModal';m.style.cssText='display:none;position:fixed;inset:0;z-index:99999;background:rgba(0,0,0,.5);padding:18px;align-items:center;justify-content:center';m.innerHTML='<div style="background:#fff;border-radius:22px;max-width:440px;width:100%;max-height:88vh;overflow:auto;padding:18px;direction:rtl"><button id="ewClose" style="float:left;border:0;background:#eee;border-radius:50%;width:34px;height:34px;font-size:20px">×</button><h2 id="ewTitle"></h2><div id="ewDuration" style="color:#666;margin-bottom:12px"></div><button id="ewImageBtn" type="button" style="display:none;width:100%;margin:4px 0 10px;padding:10px;border:1px solid #ddd;border-radius:12px;background:#fff;font-weight:700">🖼️ תמונת המסלול</button><div id="ewOut" style="background:#f3f4f6;padding:10px;border-radius:12px;margin:8px 0"></div><div id="ewStops"></div><div id="ewDinner" style="padding:10px 0;font-weight:600"></div><div id="ewBack" style="background:#f3f4f6;padding:10px;border-radius:12px;margin:8px 0"></div><a id="ewMap" target="_blank" rel="noopener" style="display:block;text-align:center;margin-top:14px;padding:11px;border-radius:12px;background:#111;color:#fff;text-decoration:none;font-weight:700">📍 פתח מסלול הליכה במפה</a></div>';document.body.appendChild(m);$('#ewClose',m).onclick=()=>m.style.display='none';m.onclick=e=>{if(e.target===m)m.style.display='none'};return m}
function imageModal(){let m=$('#eveningWalkImageModal');if(m)return m;m=document.createElement('div');m.id='eveningWalkImageModal';m.style.cssText='display:none;position:fixed;inset:0;z-index:100000;background:rgba(0,0,0,.92);padding:12px;align-items:center;justify-content:center';m.innerHTML='<button id="ewImgClose" style="position:absolute;top:14px;left:14px;border:0;background:#fff;border-radius:50%;width:38px;height:38px;font-size:24px;z-index:2">×</button><img id="ewImg" alt="תמונת מסלול ערב" style="max-width:100%;max-height:94vh;object-fit:contain;border-radius:12px">';document.body.appendChild(m);$('#ewImgClose',m).onclick=()=>m.style.display='none';m.onclick=e=>{if(e.target===m)m.style.display='none'};return m}
function imageExists(src,cb){const i=new Image();i.onload=()=>cb(true);i.onerror=()=>cb(false);i.src=src+'?v=9136'}
function open(k){const w=ROUTES[k],m=modal();if(!w)return;$('#ewTitle',m).textContent='🌙 '+w.title;$('#ewDuration',m).textContent='יציאה מהמלון 19:30 · '+w.duration;$('#ewOut',m).textContent=w.out;$('#ewStops',m).innerHTML=w.stops.map((s,i)=>'<div style="display:flex;gap:11px;margin:12px 0"><b style="background:#111;color:#fff;border-radius:50%;min-width:28px;height:28px;text-align:center;line-height:28px">'+(i+1)+'</b><div><strong>'+s[0]+'</strong><div style="font-size:13px;color:#555">'+s[1]+'</div></div></div>').join('');$('#ewDinner',m).textContent=w.dinner;$('#ewBack',m).textContent=w.back;$('#ewMap',m).href=w.map;const ib=$('#ewImageBtn',m);ib.style.display='none';ib.onclick=null;if(w.image)imageExists(w.image,ok=>{if(!ok)return;ib.style.display='block';ib.onclick=()=>{const im=imageModal();$('#ewImg',im).src=w.image+'?v=9136';im.style.display='flex'}});m.style.display='flex'}
function render(){ASSIGN.forEach(([id,k])=>{const d=$('#'+id),list=$('.list-view',d);if(!list)return;$$('.evening-walk-stop',list).forEach(x=>x.remove());const w=ROUTES[k],s=document.createElement('div');s.className='stop evening-walk-stop';s.innerHTML='<div class="time">19:30</div><div class="rail"><i>🌙</i></div><div class="stop-card" style="border:1px solid #d9d9e8;background:linear-gradient(180deg,#fff,#f8f8ff)"><h3>🌙 המלצה לטיול ערב · '+w.title+'</h3><p>אופציונלי בלבד — התוכנית המקורית של היום נשארת. יציאה מהמלון ב־19:30.</p><div class="stop-actions"><button type="button" class="evening-walk-btn" data-walk="'+k+'">פתח המלצת ערב</button></div></div>';list.appendChild(s)});if(!window.__eveningWalkClick){window.__eveningWalkClick=1;document.addEventListener('click',e=>{const b=e.target.closest('.evening-walk-btn');if(b)open(b.dataset.walk)})}}
function init(){render()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();setTimeout(init,900);
})();