// Japan Trip v9.14.1 — hotel cards, itinerary hotel links, expense de-duplication
(()=>{'use strict';
const HOTEL_PAGE='page-hotels';
const HOTELS=[
 {re:/JR Kyushu Hotel Blossom Shinjuku/i,name:'JR Kyushu Hotel Blossom Shinjuku',dates:'4–8 Nov',address:'2-6-2 Yoyogi, Shibuya-ku, Tokyo',arrival:'JR Shinjuku · South Exit · כ־3 דקות',meal:'כולל ארוחת בוקר'},
 {re:/Daiwa Roynet Hotel Kyoto Shijo Karasuma/i,name:'Daiwa Roynet Hotel Kyoto Shijo Karasuma',dates:'10–14 Nov',address:'678 Omandokorocho, Karasumadori, Shimogyo-ku, Kyoto',arrival:'Kyoto Subway Shijo · Exit 5 · כ־1 דקה מהיציאה',meal:'ללא ארוחת בוקר'},
 {re:/Hotel Royal Classic Osaka/i,name:'Hotel Royal Classic Osaka',dates:'14–16 Nov',address:'4-3-3 Namba, Chuo-ku, Osaka',arrival:'Osaka Metro Namba · Exit 12 · מחובר ישירות',meal:'כולל ארוחת בוקר'},
 {re:/Hotel Metropolitan Tokyo Marunouchi/i,name:'Hotel Metropolitan Tokyo Marunouchi',dates:'16–17 Nov',address:'Sapia Tower · 1-7-12 Marunouchi, Chiyoda-ku, Tokyo',arrival:'Tokyo Station · Nihombashi Exit · כ־1 דקה',meal:'ללא ארוחת בוקר'}
];
function openHotels(){if(typeof window.openPage==='function')window.openPage(HOTEL_PAGE);else document.getElementById(HOTEL_PAGE)?.classList.add('open');setTimeout(()=>document.getElementById(HOTEL_PAGE)?.scrollIntoView({block:'start'}),30)}
function itinerary(){document.querySelectorAll('.day .stop-card').forEach(card=>{const h=HOTELS.find(x=>x.re.test(card.textContent||''));if(!h)return;card.querySelectorAll('.reservation-doc-actions,.booking-doc-actions,.doc-actions').forEach(x=>x.remove());const p=card.querySelector('p')||document.createElement('p');p.innerHTML=`📅 ${h.dates}<br>📍 ${h.address}<br>🚉 ${h.arrival}<br>🍳 ${h.meal}`;if(!p.parentNode)card.appendChild(p);let a=card.querySelector('.hotel-details-link');if(!a){a=document.createElement('button');a.type='button';a.className='hotel-details-link';a.textContent='🏨 פרטי המלון והאסמכתה';a.style.cssText='margin-top:8px;border:0;border-radius:10px;padding:8px 10px;font-weight:700';a.onclick=openHotels;card.appendChild(a)}})}
function hotelDocs(){const page=document.getElementById(HOTEL_PAGE);if(!page)return;page.querySelectorAll('.hotel-card').forEach(card=>{const h=HOTELS.find(x=>x.re.test(card.textContent||''));if(!h)return;const ph=card.querySelector('.hotel-doc-placeholder');const act=card.querySelector('.reservation-doc-actions');if(ph&&act)ph.remove();if(ph&&!act)ph.innerHTML='<span>📎 אסמכתה</span><strong>לחץ על חבר אסמכתא למטה</strong>';if(act){act.style.marginTop='10px';act.querySelector('.reservation-doc-link')?.replaceChildren(document.createTextNode('📎 הוסף אסמכתא'));act.querySelector('.reservation-doc-open')?.replaceChildren(document.createTextNode('📄 צפייה באסמכתא'));act.querySelector('.reservation-doc-replace')?.replaceChildren(document.createTextNode('✏️ עריכת אסמכתא'))}})}
function cleanBudget(){const K='japanTrip_expenses_v1';let a;try{a=JSON.parse(localStorage.getItem(K)||'[]')}catch(e){return}if(!Array.isArray(a)||!a.length)return;const hotelGroup=x=>{const n=String(x.name||'');if(/Richmond Hotel Premier Kyoto Shijo|Daiwa Roynet Hotel Kyoto Shijo Karasuma/i.test(n))return'daiwa';if(/Cross Hotel Osaka/i.test(n))return'cross';return''};let seen=false,changed=false;const out=[];for(const x of a){const g=hotelGroup(x);if(g==='cross'){changed=true;continue}if(g==='daiwa'){if(seen){changed=true;continue}seen=true;const y={...x,name:'Daiwa Roynet Hotel Kyoto Shijo Karasuma',currency:'JPY',amount:116856,status:'מוזמן',included:true,note:'Agoda · Booking 2048972834'};if(JSON.stringify(y)!==JSON.stringify(x))changed=true;out.push(y);continue}out.push(x)}if(!seen){out.push({id:Date.now(),name:'Daiwa Roynet Hotel Kyoto Shijo Karasuma',status:'מוזמן',payment:'אשראי',currency:'JPY',amount:116856,category:'🏨 לינה',included:true,note:'Agoda · Booking 2048972834'});changed=true}if(changed){localStorage.setItem(K,JSON.stringify(out));if(typeof window.expRender==='function')window.expRender()}}
function run(){cleanBudget();itinerary();hotelDocs()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,1450),{once:true});else setTimeout(run,1450);
window.addEventListener('japanTripDriveSynced',()=>setTimeout(run,180));document.addEventListener('click',e=>{if(e.target.closest('[onclick*="page-hotels"],.hotel-details-link'))setTimeout(hotelDocs,120)},true);
})();