// Japan Trip v9.14.2 — exactly one current hotel card per itinerary day
(()=>{'use strict';
const HOTEL_PAGE='page-hotels';
const OLD=/Richmond Hotel Premier Kyoto Shijo|Cross Hotel Osaka/i;
const H={
 tokyo1:{name:'JR Kyushu Hotel Blossom Shinjuku',dates:'4–8 Nov 2026',address:'2-6-2 Yoyogi, Shibuya-ku, Tokyo',arrival:'JR Shinjuku · South Exit · כ־3 דקות',meal:'כולל ארוחת בוקר'},
 kyoto:{name:'Daiwa Roynet Hotel Kyoto Shijo Karasuma',dates:'10–14 Nov 2026',address:'678 Omandokorocho, Karasumadori, Shimogyo-ku, Kyoto',arrival:'Kyoto Subway Shijo · Exit 5 · כ־1 דקה מהיציאה',meal:'ללא ארוחת בוקר'},
 osaka:{name:'Hotel Royal Classic Osaka',dates:'14–16 Nov 2026',address:'4-3-3 Namba, Chuo-ku, Osaka',arrival:'Osaka Metro Namba · Exit 12 · מחובר ישירות למלון',meal:'כולל ארוחת בוקר'},
 tokyo2:{name:'Hotel Metropolitan Tokyo Marunouchi',dates:'16–17 Nov 2026',address:'Sapia Tower · 1-7-12 Marunouchi, Chiyoda-ku, Tokyo',arrival:'Tokyo Station · Nihombashi Exit · כ־1 דקה',meal:'ללא ארוחת בוקר'}
};
const currentRe=/JR Kyushu Hotel Blossom Shinjuku|Daiwa Roynet Hotel Kyoto Shijo Karasuma|Hotel Royal Classic Osaka|Hotel Metropolitan Tokyo Marunouchi/i;
function hotelForDay(day){const id=day.id||'';const n=Number((id.match(/day-(\d+)/)||[])[1]);if(!Number.isFinite(n))return null;/* day-1=04 Nov ... day-14=17 Nov */if(n>=1&&n<=5)return H.tokyo1;if(n>=7&&n<=11)return H.kyoto;if(n>=11&&n<=13)return H.osaka;if(n>=13&&n<=14)return H.tokyo2;return null}
function openHotels(name){if(typeof window.openPage==='function')window.openPage(HOTEL_PAGE);else document.getElementById(HOTEL_PAGE)?.classList.add('open');setTimeout(()=>{const page=document.getElementById(HOTEL_PAGE);const c=[...(page?.querySelectorAll('.hotel-card')||[])].find(x=>(x.textContent||'').includes(name));c?.scrollIntoView({behavior:'smooth',block:'center'})},100)}
function make(h){const s=document.createElement('div');s.className='stop hotel-itinerary-stop';s.dataset.canonicalHotel='1';s.innerHTML=`<div class="time">🏨</div><div class="rail"><i>🏨</i></div><div class="stop-card"><h3>${h.name}</h3><p>📅 ${h.dates}<br>📍 ${h.address}<br>🚉 ${h.arrival}<br>🍳 ${h.meal}</p><button type="button" class="hotel-details-link">פרטים נוספים ›</button></div>`;s.querySelector('button').onclick=()=>openHotels(h.name);return s}
function itinerary(){document.querySelectorAll('.day').forEach(day=>{const h=hotelForDay(day),list=day.querySelector('.list-view');if(!list)return;/* remove every hotel card, current or legacy, then add only canonical hotel for this date */[...list.querySelectorAll(':scope > .stop')].forEach(s=>{const t=s.textContent||'';if(OLD.test(t)||currentRe.test(t)||s.classList.contains('hotel-itinerary-stop')||s.dataset.canonicalHotel==='1')s.remove()});if(h)list.appendChild(make(h))})}
function hotelDocs(){const page=document.getElementById(HOTEL_PAGE);if(!page)return;page.querySelectorAll('.hotel-card').forEach(card=>{if(OLD.test(card.textContent||''))card.remove()});}
function cleanBudget(){const K='japanTrip_expenses_v1';let a;try{a=JSON.parse(localStorage.getItem(K)||'[]')}catch(e){return}if(!Array.isArray(a))return;let daiwa=false;const out=[];for(const x of a){const n=String(x.name||'');if(/Cross Hotel Osaka|Richmond Hotel Premier Kyoto Shijo/i.test(n))continue;if(/Daiwa Roynet Hotel Kyoto Shijo Karasuma/i.test(n)){if(daiwa)continue;daiwa=true;out.push({...x,name:H.kyoto.name,currency:'JPY',amount:116856,status:'מוזמן',included:true,note:'Agoda · Booking 2048972834'});continue}out.push(x)}if(!daiwa)out.push({id:Date.now(),name:H.kyoto.name,status:'מוזמן',payment:'אשראי',currency:'JPY',amount:116856,category:'🏨 לינה',included:true,note:'Agoda · Booking 2048972834'});localStorage.setItem(K,JSON.stringify(out));if(typeof window.expRender==='function')window.expRender()}
function run(){cleanBudget();itinerary();hotelDocs()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,1600),{once:true});else setTimeout(run,1600);setTimeout(run,2800);window.addEventListener('japanTripDriveSynced',()=>setTimeout(run,250));
})();