// Japan Trip v9.15.0 — one correct hotel per itinerary day
(()=>{'use strict';
const HOTEL_PAGE='page-hotels';
const H={
 tokyo1:{name:'JR Kyushu Hotel Blossom Shinjuku',dates:'4–8 Nov 2026',address:'2-6-2 Yoyogi, Shibuya-ku, Tokyo',arrival:'JR Shinjuku · South Exit · כ־3 דקות',meal:'כולל ארוחת בוקר'},
 hakone:{name:'Hakone / Fuji · המלון עדיין לא נסגר',dates:'8–10 Nov 2026',address:'—',arrival:'פרטי הגעה יעודכנו לאחר בחירת המלון',meal:'—',pending:true},
 kyoto:{name:'Daiwa Roynet Hotel Kyoto Shijo Karasuma',dates:'10–14 Nov 2026',address:'678 Omandokorocho, Karasumadori, Shimogyo-ku, Kyoto 600-8413',arrival:'Kyoto Subway Shijo · Exit 5 · כ־1 דקה מהיציאה',meal:'ללא ארוחת בוקר'},
 osaka:{name:'Hotel Royal Classic Osaka',dates:'14–16 Nov 2026',address:'4-3-3 Namba, Chuo-ku, Osaka',arrival:'Osaka Metro Namba · Exit 12 · מחובר ישירות למלון',meal:'כולל ארוחת בוקר'},
 tokyo2:{name:'Hotel Metropolitan Tokyo Marunouchi',dates:'16–17 Nov 2026',address:'Sapia Tower · 1-7-12 Marunouchi, Chiyoda-ku, Tokyo',arrival:'Tokyo Station · Nihombashi Exit · כ־1 דקה',meal:'ללא ארוחת בוקר'}
};
const ANY_HOTEL=/JR Kyushu Hotel Blossom Shinjuku|Daiwa Roynet Hotel Kyoto Shijo Karasuma|Richmond Hotel Premier Kyoto Shijo|Hotel Royal Classic Osaka|Cross Hotel Osaka|Hotel Metropolitan Tokyo Marunouchi|remm Tokyo Kyobashi|Hakone|Fuji|מלון/i;
function hotelForDay(day){const n=Number((String(day.id||'').match(/day-(\d+)/)||[])[1]);if(!Number.isFinite(n))return null;if(n>=1&&n<=4)return H.tokyo1;if(n===5||n===6)return H.hakone;if(n>=7&&n<=10)return H.kyoto;if(n===11||n===12)return H.osaka;if(n===13||n===14)return H.tokyo2;return null}
function openHotels(name){if(typeof window.openPage==='function')window.openPage(HOTEL_PAGE);else document.getElementById(HOTEL_PAGE)?.classList.add('open');setTimeout(()=>{const page=document.getElementById(HOTEL_PAGE);const c=[...(page?.querySelectorAll('.hotel-card')||[])].find(x=>(x.textContent||'').includes(name));(c||page)?.scrollIntoView({behavior:'smooth',block:'center'})},80)}
function make(h){const s=document.createElement('div');s.className='stop hotel-itinerary-stop';s.dataset.canonicalHotel='v915';s.innerHTML=`<div class="time">לינה</div><div class="rail"><i>🏨</i></div><div class="stop-card"><h3>${h.name}</h3><p>📅 ${h.dates}<br>📍 ${h.address}<br>🚉 ${h.arrival}<br>🍳 ${h.meal}</p>${h.pending?'':`<button type="button" class="hotel-details-link">פרטים נוספים ›</button>`}</div>`;const b=s.querySelector('button');if(b)b.onclick=()=>openHotels(h.name);return s}
function itinerary(){document.querySelectorAll('.day').forEach(day=>{const h=hotelForDay(day),list=day.querySelector('.list-view');if(!list)return;[...list.querySelectorAll(':scope > .stop')].forEach(s=>{const t=s.textContent||'';if(s.classList.contains('hotel-itinerary-stop')||s.dataset.canonicalHotel||ANY_HOTEL.test(t)&&/לינה|hotel|check-?in|מלון/i.test(t))s.remove()});if(h)list.appendChild(make(h))})}
function cleanBudget(){const K='japanTrip_expenses_v1';let a;try{a=JSON.parse(localStorage.getItem(K)||'[]')}catch(e){return}if(!Array.isArray(a))return;const activeNames=['JR Kyushu Hotel Blossom Shinjuku','Daiwa Roynet Hotel Kyoto Shijo Karasuma','Hotel Royal Classic Osaka','Hotel Metropolitan Tokyo Marunouchi'];const hotelish=x=>String(x.category||'').includes('לינה')||/hotel|מלון|richmond|cross|remm|daiwa|blossom|metropolitan/i.test(String(x.name||''));const keep=[];for(const x of a){if(!hotelish(x)){keep.push(x);continue}const n=String(x.name||'');if(/Hakone|האקונה/i.test(n)){if(!keep.some(y=>/Hakone|האקונה/i.test(String(y.name||''))))keep.push(x);continue}if(activeNames.some(nm=>n.includes(nm)))continue}
keep.push({id:Date.now()+1,name:H.tokyo1.name,status:'מוזמן',payment:'אשראי',currency:'JPY',amount:311616,category:'🏨 לינה',included:true,note:'Agoda · 4–8/11'});keep.push({id:Date.now()+2,name:H.kyoto.name,status:'מוזמן',payment:'אשראי',currency:'JPY',amount:116856,category:'🏨 לינה',included:true,note:'Agoda · 10–14/11'});keep.push({id:Date.now()+3,name:H.osaka.name,status:'מוזמן',payment:'אשראי',currency:'JPY',amount:109398,category:'🏨 לינה',included:true,note:'Agoda · 14–16/11'});keep.push({id:Date.now()+4,name:H.tokyo2.name,status:'שולם',payment:'אשראי',currency:'ILS',amount:676.61,category:'🏨 לינה',included:true,note:'Klook · 16–17/11 · QXU287073'});localStorage.setItem(K,JSON.stringify(keep));if(typeof window.expRender==='function')window.expRender()}
function run(){cleanBudget();itinerary()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,1200),{once:true});else setTimeout(run,1200);setTimeout(run,2200);window.addEventListener('japanTripDriveSynced',()=>setTimeout(run,180));
})();