const VERSION='v9.13.6';
const CACHE='japan-trip-v9-13-6';
const MODULES=['./data.js','./drive.js','./evening-walks.js'];
const CORE=['./','./index.html','./manifest.json','./icon.svg','./styles.css','./app.js','./index.htm',...MODULES];
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil((async()=>{const ks=await caches.keys();await Promise.all(ks.filter(k=>k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim();const cs=await self.clients.matchAll({type:'window',includeUncontrolled:true});for(const c of cs){try{const u=new URL(c.url);if(u.origin===self.location.origin&&!u.searchParams.has('v9136')){u.searchParams.set('v9136',Date.now());await c.navigate(u.href)}}catch(x){}}})()));
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);
if(url.origin===self.location.origin&&/\/app\.js$/.test(url.pathname)){event.respondWith((async()=>{const br=await fetch(event.request,{cache:'no-store'});if(!br.ok)return br;let merged=await br.text();merged=merged.replace(/v9\.10/g,VERSION).replace(/Japan Trip 2026 · v9\.10/g,'Japan Trip 2026 · '+VERSION);const mt=[];for(const f of MODULES){const r=await fetch(f+'?v=9136',{cache:'no-store'});if(r.ok){let t=await r.text();t=t.replace(/v9\.13\.[1-5]/g,VERSION).replace(/🍽️ מסעדות/g,'מסעדות');mt.push(t)}}
const fin=`\n;(function JapanTripFinalUi(){'use strict';const V='${VERSION}',$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clean=s=>String(s||'').replace(/\\s+/g,' ').trim();function version(){const v=$('header .logo .app-version')||$('header .logo small');if(v)v.textContent='2026 · '+V;document.title='Japan Trip 2026 · '+V;document.documentElement.dataset.appReady=V}function osakaHotel(){const day=$('#day-11'),list=$('.list-view',day);if(!day||!list)return;let hs=$$(':scope > .stop',list).filter(s=>/Hotel Royal Classic Osaka|Cross Hotel Osaka/i.test(s.textContent||''));hs.slice(1).forEach(s=>s.remove());if(!hs[0]){const h=document.createElement('div');h.className='stop hotel-itinerary-stop';h.innerHTML='<div class="time">אחה״צ</div><div class="rail"><i>🏨</i></div><div class="stop-card"><h3>Check-in · Hotel Royal Classic Osaka</h3><p>הגעה מ-Nara, צ׳ק-אין והתארגנות.</p></div>';const ev=$$(':scope > .stop',list).find(s=>/Hozenji|Dotonbori/i.test(s.textContent||''));ev?ev.before(h):list.appendChild(h)}}function places(){const page=$('#page-places'),grid=$('#placesGrid');if(!page||!grid)return;const junk=/^(?:החזרת רכב|החזר(?:ת)? רכב|לקיחת רכב|קבלת רכב|איסוף רכב|המשך לפי מקום לינה|המשך לפי המלון|לפי מקום לינה|חזרה ל.+|שינקנסן(?:\\s*→.*)?|shinkansen(?:\\s*→.*)?|train(?:\\s*→.*)?|רכבת(?:\\s*→.*)?|נסיעה(?:\\s*→.*)?|מעבר(?:\\s*→.*)?|check[ -]?in|check[ -]?out)$/i;$$('.place-card',grid).forEach(c=>{const title=clean($('h3',c)?.textContent);if(junk.test(title)){c.remove();return}if(c.dataset.type==='restaurant'||/66tantan|Rokuroku Tantan|Gyukatsu Motomura|Uobei|AFURI|Katsukura|Musashi Sushi|Mizuno|551\\s*HORAI|Namba Ramen Ichiza/i.test(title)){c.dataset.cat='מסעדות';c.dataset.type='restaurant'}$$('.place-card-meta,.place-meta,.place-category',c).forEach(el=>{let t=clean(el.textContent);if(/במסלול/i.test(t)){t=t.replace(/\\s*[·•-]?\\s*במסלול\\s*[:·]?\\s*.*$/i,'').trim();t?el.textContent=t:el.remove()}})});$('#placesRestaurantFilter')?.remove();if(typeof applyPF==='function')applyPF()}function run(){version();osakaHotel();places()}run();setTimeout(run,300);setTimeout(run,1200);})();`;
merged+='\n\n;(function __japanTripLoadConsolidated(){\n'+"if(document.documentElement.dataset.appReady==='"+VERSION+"'||document.documentElement.dataset.appReady==='error'){\n"+mt.join('\n\n')+fin+'\nreturn;}\nsetTimeout(__japanTripLoadConsolidated,50);\n})();';return new Response(merged,{status:200,headers:{'Content-Type':'application/javascript; charset=utf-8','Cache-Control':'no-store'}})})().catch(()=>caches.match(event.request)));return}
if(url.origin===self.location.origin&&(/\/index\.html$/.test(url.pathname)||url.pathname.endsWith('/Japan/')||url.pathname.endsWith('/Japan'))){event.respondWith(fetch(event.request,{cache:'no-store'}).then(async r=>{if(!r.ok)return r;let h=await r.text();h=h.replace(/v9\.5/g,VERSION).replace(/v9\.6/g,VERSION).replace(/>יוצאים לדרך ✈️</g,'>עזרי ואיילי יוצאים לדרך ✈️<');return new Response(h,{status:r.status,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}})}).catch(()=>caches.match('./index.html')));return}
if(url.origin===self.location.origin){event.respondWith(fetch(event.request,{cache:'no-store'}).then(r=>{if(r&&r.ok){const cp=r.clone();caches.open(CACHE).then(c=>c.put(event.request,cp))}return r}).catch(()=>caches.match(event.request).then(r=>r||caches.match('./index.html'))));return}event.respondWith(fetch(event.request).catch(()=>caches.match(event.request)))});