// Japan Trip v9.12k - stable one-time fixes, no DOM rebuild loops
(function(){'use strict';
const VERSION='v9.12k';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
function mkStop(time,icon,title,text,place,tag){const d=document.createElement('div');d.className='stop v912k-stop';d.innerHTML='<div class="time">'+time+'</div><div class="rail"><i>'+icon+'</i></div><div class="stop-card"><h3>'+title+'</h3><p>'+text+'</p>'+(tag?'<span class="trip-tag">'+tag+'</span>':'')+(place?'<div class="stop-actions"><button class="info-modal-btn guide-tips-btn" data-place="'+place+'" type="button">ℹ️ מדריך וטיפים</button></div>':'')+'</div>';return d}
function rebuild12(){const day=$('#day-9');if(!day||day.dataset.v912k==='1')return;const list=$('.list-view',day);if(!list)return;day.dataset.v912k='1';const hotel=$$('.stop',list).find(s=>/Richmond Hotel Premier Kyoto Shijo/i.test(s.textContent||''));$$('.stop',list).forEach(s=>s.remove());const h=$('.day-heading h2',day);if(h)h.textContent='Fushimi Inari · Tofuku-ji · Sanjūsangen-dō · teamLab';const sum=$('.summary',day);if(sum)sum.textContent='Fushimi Inari → Tofuku-ji → Sanjūsangen-dō → Kyoto Station → teamLab Biovortex Kyoto';[
['09:00','⛩️','Fushimi Inari Taisha','בוקר בין אלפי שערי ה־torii. אין צורך לעלות לפסגה; נמשיך עד שנקבל את חוויית השערים והיער ואז נחזור.','Fushimi Inari',''],
['11:30','🍁','Tofuku-ji','מקדש זן סמוך ל-Fushimi Inari, מפורסם במיוחד בשלכת ובמראה מעמק המייפלים ליד גשר Tsutenkyo.','Tofuku-ji',''],
['14:00','🏯','Sanjūsangen-dō','אולם עץ ארוך ובו 1,001 פסלי Kannon. חוויה שונה משאר המקדשים במסלול.','Sanjusangen-do',''],
['16:00','🚉','Kyoto Station + Higashi Hongan-ji','סיום רגוע באזור התחנה ובמידת הזמן קפיצה ל-Higashi Hongan-ji הסמוך.','Kyoto Station',''],
['ערב','✨','teamLab Biovortex Kyoto','אחת מחוויות החובה של הטיול בקיוטו. נשלב אותה בערב ונזמין כרטיסים מראש.','teamLab Biovortex Kyoto','⭐ חובה · להזמין מראש']
].forEach(x=>list.appendChild(mkStop(...x)));if(hotel)list.appendChild(hotel);const map=$('.map-view .route-map-card',day);if(map)map.innerHTML='<div class="route-map-icon">🗺️</div><h3>מסלול 12/11</h3><ol><li>Fushimi Inari Taisha</li><li>Tofuku-ji Temple</li><li>Sanjusangen-do</li><li>Kyoto Station</li><li>teamLab Biovortex Kyoto</li></ol><a class="open-day-route" href="https://www.google.com/maps/dir/?api=1&origin=Fushimi+Inari+Taisha&destination=teamLab+Biovortex+Kyoto&travelmode=transit&waypoints=Tofuku-ji+Temple|Sanjusangen-do|Kyoto+Station" target="_blank" rel="noopener">פתח את מסלול היום ↗</a>'}
function fix14(){const day=$('#day-11');if(!day||day.dataset.v912k==='1')return;const list=$('.list-view',day);if(!list)return;day.dataset.v912k='1';$$('.stop',list).forEach(s=>{if(/Hozenji|Dotonbori · ערב ראשון|ארוחת ערב · Namba/i.test(s.textContent||''))s.remove()});const hotel=$$('.stop',list).find(s=>/Hotel Royal Classic Osaka|Cross Hotel Osaka/i.test(s.textContent||''));let after=hotel||list.lastElementChild;[
['19:00','🏮','Hozenji Temple + Hozenji Yokocho','אחרי הצ׳ק-אין: סמטת אבן קטנה עם פנסים ומקדש Hozenji, במרחק הליכה קצר מ-Namba.','Hozenji Yokocho',''],
['19:45','🌃','Dotonbori · ערב ראשון באוסקה','טיול לאורך התעלה, שלטי הניאון ו-Glico Man. ערב קל אחרי יום Nara.','Dotonbori',''],
['20:30','🍽️','ארוחת ערב · Namba / Dotonbori','לבחור לפי החשק — אוקונומיאקי, טפניאקי או אוכל יפני אחר.','Namba','']
].forEach(x=>{const s=mkStop(...x);if(after&&after.parentNode===list){after.after(s);after=s}else list.appendChild(s)})}
function dedupeDayStops(){ $$('.day .list-view').forEach(list=>{const seen=new Set();$$(':scope > .stop',list).forEach(s=>{const t=($('.time',s)?.textContent||'').trim().toLowerCase(),h=($('h3',s)?.textContent||'').trim().toLowerCase();if(!h)return;const k=t+'|'+h;if(seen.has(k))s.remove();else seen.add(k)})}) }
function sim(a,b){const n=s=>(s||'').replace(/[^\p{L}\p{N}]+/gu,' ').replace(/\s+/g,' ').trim().toLowerCase();a=n(a);b=n(b);if(!a||!b)return 0;if(a===b||a.includes(b)||b.includes(a))return 1;const A=new Set(a.split(' ').filter(x=>x.length>2)),B=new Set(b.split(' ').filter(x=>x.length>2));let hit=0;A.forEach(x=>B.has(x)&&hit++);return hit/Math.max(1,Math.min(A.size,B.size))}
const GUIDE={
'Fushimi Inari':{tip:'אין צורך להגיע לפסגה; אחרי שהשערים נעשים פחות צפופים אפשר להסתובב ולרדת.',extra:['המקדש מוקדש לאינארי, הקשור לשגשוג, ולכן תראו לאורך הדרך פסלי שועלים — שליחיו המסורתיים.','הגעה מוקדמת נותנת חוויה רגועה יותר משמעותית.']},
'Tofuku-ji':{tip:'בנובמבר זה אחד מאתרי השלכת החזקים בקיוטו, ולכן הגיוני במיוחד לשלב אותו ביום הזה.',extra:['גשר Tsutenkyo עובר מעל עמק מייפלים ונחשב לנקודת המבט המזוהה ביותר עם המקדש.','המיקום קרוב יחסית ל-Fushimi Inari ולכן השילוב חוסך נסיעות מיותרות.']},
'Sanjusangen-do':{tip:'הייחוד כאן הוא בפנים — לא לדלג עליו רק בגלל שהמבנה החיצוני צנוע יחסית.',extra:['האולם מכיל 1,001 דמויות של Kannon ומייצר חוויה שונה מאוד ממקדשי הגנים והנוף.','הביקור קומפקטי יחסית ולכן מתאים היטב בין Tofuku-ji לאזור Kyoto Station.']},
'Kyoto Station':{tip:'שווה להרים מבט למבנה עצמו, למדרגות ולמרפסות — לא רק לעבור בתחנה.',extra:['זהו אחד המבנים המודרניים הבולטים בקיוטו ויוצר ניגוד מעניין לימים ההיסטוריים בעיר.']},
'teamLab Biovortex Kyoto':{tip:'⭐ חובה במסלול שלנו; להזמין מראש לשעת ערב שמתאימה ליום 12.',extra:['החוויה בנויה כחלל אמנות דיגיטלית immersive ולא כמוזיאון רגיל, ולכן כדאי להשאיר לה זמן ולא לדחוס אותה בין תחנות.','נגיע אחרי שסיימנו את אתרי היום, כך שהערב מוקדש לחוויה עצמה.']}
};
function cleanPopup(place){const m=$('#placeModal')||$('.place-modal');if(!m)return;const desc=$('#modalDesc',m)||$('.modal-desc',m);if(!desc)return;const base=desc.textContent||'';const heads=$$('h2,h3,h4,b,strong',m).filter(x=>/למה.*שווה|why.*worth/i.test(x.textContent||''));heads.forEach(h=>{const box=h.closest('.why-worth,.modal-section,.guide-section,.info-box,.detail-box')||h.parentElement;if(!box)return;$$('li,p',box).forEach(n=>{if(n===desc||desc.contains(n))return;if(sim(base,n.textContent||'')>.58)n.remove()})});const g=GUIDE[place];if(g){let tip=$('#modalTip',m);if(tip){tip.textContent='💡 '+g.tip;tip.style.display=''}let why=heads[0]?.closest('.why-worth,.modal-section,.guide-section,.info-box,.detail-box')||heads[0]?.parentElement;if(why){let ul=$('ul',why);if(!ul){ul=document.createElement('ul');why.appendChild(ul)}const existing=$$('li',ul).map(x=>x.textContent||'');g.extra.forEach(x=>{if(!existing.some(e=>sim(e,x)>.7)){const li=document.createElement('li');li.textContent=x;ul.appendChild(li)}})}}}
function setVersion(){const v=$('header .logo .app-version')||$('header .logo small');if(v&&v.textContent!=='2026 · '+VERSION)v.textContent='2026 · '+VERSION;document.title='Japan Trip 2026 · '+VERSION;document.documentElement.dataset.appReady=VERSION}
function init(){rebuild12();fix14();dedupeDayStops();setVersion()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,50),{once:true});else setTimeout(init,50);
setTimeout(setVersion,800);setTimeout(setVersion,1800);
document.addEventListener('click',e=>{const b=e.target.closest('.guide-tips-btn,.info-modal-btn,.place-info-btn');if(!b)return;setTimeout(()=>cleanPopup(b.dataset.place||''),180)},true);
})();