// Japan Trip v9.12 - itinerary helpers
(function(){
'use strict';
const WALK_PAIRS=[['Kaminarimon','Nakamise'],['Nakamise','Sensō-ji'],['Ueno','Ameyoko'],['Ameyoko','Akihabara'],['Meiji Jingu','Takeshita'],['Takeshita','Omotesando'],['Omotesando','Shibuya'],['Tsukiji','Ginza'],['Ginza','Imperial Palace'],['Imperial Palace','Tokyo Station'],['Kiyomizu','Higashiyama'],['Higashiyama','Gion'],['Gion','Pontocho'],['Nara Park','Tōdai'],['Tōdai','Naramachi'],['Shinsaibashi','Dotonbori']];
function norm(s){return(s||'').toLowerCase().replace(/[^a-z0-9\u0590-\u05ff]+/g,' ').trim()}
function hit(a,b){a=norm(a);b=norm(b);return WALK_PAIRS.some(([x,y])=>{x=norm(x);y=norm(y);return(a.includes(x)&&b.includes(y))||(a.includes(y)&&b.includes(x))})}
function replaceRemm(){
 document.querySelectorAll('.hotel-card,.booking-card,.card,.stop-card').forEach(card=>{
   if(!/remm Tokyo Kyobashi/i.test(card.textContent||''))return;
   card.innerHTML=card.innerHTML.replace(/remm Tokyo Kyobashi/gi,'Hotel Metropolitan Tokyo Marunouchi').replace(/2-6-21 Kyobashi[^<]*/gi,'1-7-12 Marunouchi, Chiyoda · Sapia Tower').replace(/E874633747/gi,'QXU287073');
 });
 document.querySelectorAll('[data-metropolitan-v912]').forEach(x=>x.remove());
}
function addHotelExits(){const tips=[['JR Kyushu Hotel Blossom Shinjuku','🚉 JR Shinjuku · South Exit · כ־3 דק׳ הליכה'],['Richmond Hotel Premier Kyoto Shijo','🚉 Shijo / Karasuma · Exit 24 · כ־7 דק׳ הליכה'],['Hotel Royal Classic Osaka','🚉 Osaka Metro Namba · Exit 12 · מחובר ישירות למלון'],['Cross Hotel Osaka','🚉 Namba · Exit 14 · כ־3–5 דק׳ הליכה'],['Hotel Metropolitan Tokyo Marunouchi','🚄 Tokyo Station · Nihombashi Exit · Sapia Tower · כ־1 דק׳ מ־Shinkansen Nihombashi Gate']];document.querySelectorAll('.hotel-card,.booking-card,.card,.stop-card').forEach(card=>{if(card.querySelector('.hotel-exit-v912'))return;const txt=card.textContent||'',t=tips.find(([n])=>txt.toLowerCase().includes(n.toLowerCase()));if(!t)return;const d=document.createElement('div');d.className='hotel-exit-v912';d.textContent=t[1];card.appendChild(d)})}
function addRamenIchiza(){const day=document.getElementById('day-12');if(!day||day.querySelector('[data-ramen-ichiza]'))return;const list=day.querySelector('.list-view');if(!list)return;const stop=document.createElement('div');stop.className='stop';stop.dataset.ramenIchiza='1';stop.innerHTML='<div class="time">אופציה</div><div class="rail"><i>🍜</i></div><div class="stop-card"><h3>Ramen Ichiza · Namba</h3><p>אופציה לארוחה כשאנחנו באזור Namba / Dotonbori. מתחם ראמן בקומה 9 של EDION Namba עם כמה חנויות ראמן במקום אחד.</p><div class="stop-actions"><a class="map-btn" href="https://www.google.com/maps/search/?api=1&query=Namba+Ramen+Ichiza+EDION+Namba+Osaka" rel="noopener" target="_blank">📍 פתח מפה ↗</a></div></div>';list.appendChild(stop)}
function decorate(){replaceRemm();document.querySelectorAll('.route-map-card').forEach(card=>{if(card.querySelector('.walk-pref-v912'))return;const stops=[...card.querySelectorAll('ol li')].map(x=>x.textContent.trim()).filter(Boolean),walks=[];for(let i=0;i<stops.length-1;i++)if(hit(stops[i],stops[i+1]))walks.push(stops[i]+' → '+stops[i+1]);if(!walks.length)return;const box=document.createElement('div');box.className='walk-pref-v912';box.innerHTML='<b>🚶 עדיפות להליכה</b><span>'+walks.join(' · ')+'</span><small>במעברים של עד כ־20–25 דקות נעדיף ללכת. מטרו/רכבת נשארים חלופה לעייפות או מזג אוויר.</small>';card.appendChild(box)});addRamenIchiza();addHotelExits();const v=document.querySelector('header .logo small');if(v)v.textContent='2026 · v9.12'}
function css(){if(document.getElementById('walk-v912-css'))return;const s=document.createElement('style');s.id='walk-v912-css';s.textContent='.walk-pref-v912,.hotel-exit-v912{margin:9px 0;padding:10px 11px;border-radius:12px;background:#f4f8f2;border:1px solid #dce9d7;font-size:11px}.walk-pref-v912 b{display:block;font-size:12px;margin-bottom:4px}.hotel-exit-v912{font-weight:700;line-height:1.5}';document.head.appendChild(s)}
function run(){css();decorate()}new MutationObserver(()=>setTimeout(run,60)).observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();
})();